### dash-cytoscape

In [1]:
import sys
from pathlib import Path

ROOT0 = Path("/home/flavio/uv/perturb_agent/")
ROOT_SRC = ROOT0 / "src"

if str(ROOT_SRC) not in sys.path:
    sys.path.append(str(ROOT_SRC))

print("ROOT0:", ROOT0)
print("ROOT_SRC added:", ROOT_SRC)

from libs.Basic import *
from libs.dashcyto_lib import DASH_CYTO

ROOT0: /home/flavio/uv/perturb_agent
ROOT_SRC added: /home/flavio/uv/perturb_agent/src

In [2]:
dcy = DASH_CYTO(ROOT0=ROOT0)

Loaded gene annotation table: /home/flavio/uv/perturb_agent/data/ncbi/hugo_gene_table_refseq_uniprot.tsv
Rows: 39,740
Symbols: 39,537
Ensembl IDs: 39,740
Loaded alias rows: 121,273
Unique aliases: 95,784
DEBUG TSP1:
            alias alias_upper  symbol       ensembl_id  \
alias_upper
TSP1         TSP1        TSP1  CRISP2  ENSG00000124490
TSP1         TSP1        TSP1   THBS1  ENSG00000137801
TSP1         TSP1        TSP1  PRSS55  ENSG00000184647

                                          name uniprot_id  \
alias_upper
TSP1         cysteine rich secretory protein 2     P16562
TSP1                          thrombospondin 1     P07996
TSP1                        serine protease 55     Q6UWB4

                                                refseq_summary
alias_upper
TSP1         Predicted to be involved in sexual reproductio...
TSP1         The protein encoded by this gene is a subunit ...
TSP1         This gene encodes a member of a group of membr...

In [3]:
owl_file = "R-HSA-165159_level3.owl"
owl_file = "R-HSA-114608_level3.owl"

pathway = 'Platelet degranulation'
pathway_id = "R-HSA-114608"

rdf = dcy.read_owl(pathway_id, pathway)

```Python
G.nodes[gene_id]["log2FC"] = log2fc
G.nodes[gene_id]["FDR"] = fdr
G.nodes[gene_id]["mutated"] = True
```

### OWL to Graph

In [4]:
saved_positions = dcy.load_positions(pathway_id)

Data loaded from /home/flavio/uv/perturb_agent/data/owl/positions_R-HSA-114608.json

In [5]:
i=0
for key, posi in saved_positions.items():
    print(key, posi)
    i+=1
    if i==3: break

Protein46 {'x': 1089.2281544150715, 'y': 170.56669566144214}
PhysicalEntity6 {'x': 188.53386155690094, 'y': 447.28101611825684}
PhysicalEntity4 {'x': 46.6583784124059, 'y': 227.10534621909645}

### Synonyms table

In [ ]:
# df = pdreadcsv(dcy.fname_hugo, dcy.root_ncbi)
# df.head(2)

,ensembl_id,symbol,name,uniprot_id,ncbi_gene_id,synonyms,refseq_summary
0,ENSG00000000003,TSPAN6,tetraspanin 6,O43657,7105.0,T245; TM4SF6; TSPAN-6,The protein encoded by this gene is a member o...
1,ENSG00000000005,TNMD,tenomodulin,Q9H2S6,64102.0,BRICD4; CHM1L; TEM,This gene encodes a protein that is related to...

In [ ]:
force=False
verbose=True

# dfsyn = dcy.build_gene_alias_table(force=force, verbose=verbose)
# dfsyn.head(3)

Table opened ((121273, 7)) at '/home/flavio/uv/perturb_agent/data/ncbi/hugo_gene_alias_table.tsv'

,alias,alias_upper,symbol,ensembl_id,name,uniprot_id,refseq_summary
0,TSPAN6,TSPAN6,TSPAN6,ENSG00000000003,tetraspanin 6,O43657,The protein encoded by this gene is a member o...
1,T245,T245,TSPAN6,ENSG00000000003,tetraspanin 6,O43657,The protein encoded by this gene is a member o...
2,TM4SF6,TM4SF6,TSPAN6,ENSG00000000003,tetraspanin 6,O43657,The protein encoded by this gene is a member o...

### Dash

In [9]:
height = "95%"
width = "100%"
marginTop="20px"

dcy.run_app(height=height, width=width, marginTop=marginTop)

Data loaded from /home/flavio/uv/perturb_agent/data/owl/positions_R-HSA-114608.json
Open in browser: http://localhost:8050
Dash app running on http://127.0.0.1:8050/

ANNOT: {'alias': 'TSP1', 'symbol': 'CRISP2', 'ensembl_id': 'ENSG00000124490', 'name': 'cysteine rich secretory protein 2', 'uniprot_id': 'P16562', 'refseq_summary': 'Predicted to be involved in sexual reproduction. Predicted to be located in extracellular region. Predicted to be active in extracellular space. [provided by Alliance of Genome Resources, Apr 2025]', 'matches': [{'alias': 'TSP1', 'symbol': 'CRISP2', 'ensembl_id': 'ENSG00000124490', 'name': 'cysteine rich secretory protein 2', 'uniprot_id': 'P16562', 'refseq_summary': 'Predicted to be involved in sexual reproduction. Predicted to be located in extracellular region. Predicted to be active in extracellular space. [provided by Alliance of Genome Resources, Apr 2025]'}, {'alias': 'TSP1', 'symbol': 'THBS1', 'ensembl_id': 'ENSG00000137801', 'name': 'thrombospondin 1', 'uniprot_id': 'P07996', 'refseq_summary': 'The protein encoded by this gene is a subunit of a disulfide-linked homotrimeric protein. This protein is an adhesive glycoprotein that mediates cell-to-cell and cell-to-matrix interactions. This protein can bind to fibrinogen, fibronectin, laminin, type V collagen and integrins alpha-V/beta-1. This protein has been shown to play roles in platelet aggregation, angiogenesis, and tumorigenesis. [provided by RefSeq, Jul 2008]'}, {'alias': 'TSP1', 'symbol': 'PRSS55', 'ensembl_id': 'ENSG00000184647', 'name': 'serine protease 55', 'uniprot_id': 'Q6UWB4', 'refseq_summary': 'This gene encodes a member of a group of membrane-anchored chymotrypsin (S1)-like serine proteases. The enocoded protein is primarily expressed in the Leydig and Sertoli cells of the testis and may be involved in male fertility. Alternate splicing results in multiple transcript variants. [provided by RefSeq, Sep 2010]'}], 'n_matches': 3}
REFSEQ: Predicted to be involved in sexual reproduction. Predicted to be located in extracellular region. Predicted to be active in extracellular space. [provided by Alliance of Genome Resources, Apr 2025]
>>> n_matches 0