In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd
import requests
import time

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [3]:
ROOT_DATA = '../data'
ROOT_DATA = Path(ROOT_DATA)

gdc = GDC(ROOT_DATA0=ROOT_DATA)

os.listdir(ROOT_DATA)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'GTEx', 'gdc_programs.txt']

In [4]:
os.listdir(gdc.root_data)[:10]

['app_main_local.py',
 'gtex_normal_tissue.ipynb',
 'docker_config.ipynb',
 'tcga_gdc_run_R_expression_dvlp.ipynb']

### Get all programs

In [5]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

np.array(prog_list)

File read at '../data/gdc_programs.txt'

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.self.cancer.gov/projects'

In [7]:
prog_id = 'TCGA'

df_psi = gdc.get_primary_sites(prog_id=prog_id, force=False, verbose=verbose)
print(len(df_psi))

df_psi.head(3)

Table opened ((33, 5)) at '../data/TCGA/primary_site_program_TCGA.tsv'
33

,psi_id,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma

### GTEx

In [8]:
ROOT_GTEx = ROOT_DATA / Path('GTEx')

os.listdir(ROOT_GTEx)[:10]

['tcga_primary_site_to_gtex_ids.tsv']

In [9]:
fname_gtex = 'tcga_primary_site_to_gtex_ids.tsv'

dfg = pdreadcsv(fname_gtex, ROOT_GTEx)
print(len(dfg))

dfg.head(6)

33

,tcga_project_id,tcga_primary_site,gtex_dataset_id,preferred_gtex_id,gtex_tissue_site_detail_ids,mapping_confidence,notes,source_gtex_api
0,TCGA-ACC,Adrenal Gland,gtex_v8,Adrenal_Gland,Adrenal_Gland,high,Adrenocortical carcinoma; direct adrenal gland...,https://gtexportal.org/api/v2/redoc
1,TCGA-BLCA,Bladder,gtex_v8,Bladder,Bladder,high,"Direct bladder GTEx tissue, but GTEx bladder s...",https://gtexportal.org/api/v2/redoc
2,TCGA-BRCA,Breast,gtex_v8,Breast_Mammary_Tissue,Breast_Mammary_Tissue,high,Breast carcinoma; GTEx mammary/breast tissue.,https://gtexportal.org/api/v2/redoc
3,TCGA-CESC,Cervix Uteri,gtex_v8,Cervix_Ectocervix,Cervix_Ectocervix|Cervix_Endocervix|Uterus,medium,Cervical cancer may involve ectocervix/endocer...,https://gtexportal.org/api/v2/redoc
4,TCGA-CHOL,Bile Duct,gtex_v8,Liver,Liver,low,No direct bile duct/cholangiocyte GTEx tissue;...,https://gtexportal.org/api/v2/redoc
5,TCGA-COAD,Colon,gtex_v8,Colon_Transverse,Colon_Transverse|Colon_Sigmoid,high,Colon cancer; transverse/sigmoid are both vali...,https://gtexportal.org/api/v2/redoc

In [10]:
psi_id = 'TCGA-BRCA'
psi_id = 'TCGA-LUAD'

dfa = dfg[dfg.tcga_project_id == psi_id]

gtex_id = None

if len(dfa) == 1:
    row = dfa.iloc[0]

    gtex_id = row.preferred_gtex_id
    gtex_tissue_ids = row.gtex_tissue_site_detail_ids
    print(f"Found '{gtex_id}' tissue '{gtex_tissue_ids}'")
elif len(dfa) == 0:
    print("Not found")
else:
    print("Multiple matches found")
    for i, row in dfa.iterrows():
        gtex_id = row.preferred_gtex_id
        gtex_tissue_ids = row.gtex_tissue_site_detail_ids

        print(f"{row.tcga_project_id} -> '{gtex_id}' tissue '{gtex_tissue_ids}'")

Found 'Lung' tissue 'Lung'

### Get df_tumor

In [11]:
psi_id

'TCGA-LUAD'

In [12]:
verbose=False

dic_tumor, dic_normal = gdc.get_file_expression_tumor_and_normal(psi_id=psi_id, force=False, verbose=verbose)
df_tumor, df_normal = gdc.merge_normal_tumor_tables(dic_tumor, dic_normal,  imax_tumor=12, imax_normal=12, verbose=verbose)

len(df_tumor), len(df_normal)

>>> TCGA-LUAD
>>> TCGA-LUAD
0.........10.........20.........30.........40.........50.........60.........70.........80.........90......... -> 100
Dowloading tumor files: 0.........10.........20.........30.........40.........50.........60.........70.........80.........90.........100........ -> 109
>>> Processing normal data: 100
1 2 3 4 5 6 7 8 9 10 11 12 13
>>> Processing tumor data: 11
1 2 3 4 5 6 7 8 9 10 11

(150684, 240796)

In [13]:
df_tumor.head(3)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11
0,ENSG00000000003,TSPAN6,protein_coding,1604,2392,1373,803,799,5095,2,792,1489,3870,522
1,ENSG00000000005,TNMD,protein_coding,0,0,8,2,1,0,14,0,0,1,0
2,ENSG00000000419,DPM1,protein_coding,459,816,713,799,400,3372,39,1043,345,1380,678

In [41]:
from scipy.stats import f_oneway

def add_entropy(df, read_limit:int=50, min_read:int=200, n_quantiles:int=10):
    # select tumor columns
    cols = [c for c in df.columns if c.startswith("tumor_")]

    def row_entropy(values):
        values = np.asarray(values, dtype=float)

        # remove NaNs
        values = values[np.isfinite(values)]

        if len(values) == 0:
            return np.nan

        # all equal → entropy = 0
        if np.allclose(values, values[0]):
            return 0.0

        # shift to positive (important if negative values exist)
        values = values - values.min()

        # avoid all zeros
        if np.allclose(values.sum(), 0):
            return 0.0

        probs = values / values.sum()

        # avoid log(0)
        probs = probs[probs > 0]

        entropy = -np.sum(probs * np.log2(probs))
        return entropy

    min_cols = int(len(cols) * 0.4)
    good = (df[cols] < read_limit).sum(axis=1) <= min_cols
    df = df[good].copy()

    df["total_sum"] = df[cols].sum(axis=1)

    df = df[df.total_sum > len(cols)*min_read]

    df["entropy"] = df[cols].apply(lambda row: row_entropy(row.values), axis=1)

    df["entropy_q"] = pd.qcut(df["entropy"], q=n_quantiles, labels=False, duplicates="drop" )

    return df


print(len(df_tumor))
df_tumor2 = add_entropy(df_tumor)
print(len(df_tumor2))
df_tumor2.head(3)

150684
15817

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000000003,TSPAN6,protein_coding,1604,2392,1373,803,799,5095,2,792,1489,3870,522,2.954896,5,18741
2,ENSG00000000419,DPM1,protein_coding,459,816,713,799,400,3372,39,1043,345,1380,678,2.911364,4,10044
3,ENSG00000000457,SCYL3,protein_coding,542,432,557,699,264,995,168,352,283,1706,471,2.852843,3,6469

In [46]:
def select_top_entropy(df, q=0.1):

    df = df[df.entropy_q <= q].copy()
    df = df.sort_values('entropy', ascending=True)
    df.reset_index(drop=True, inplace=True)

    return df

tumor_cols = [c for c in df_tumor.columns if c.startswith("tumor_")]

df_tumor3 = select_top_entropy(df_tumor2, q=0.1)
print(len(df_tumor3))
df_tumor3.head(3)

1582

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000135919,SERPINE2,protein_coding,189,821,1026,2040,1170,216535,5,599,193,1394,754,0.329341,0,224726
1,ENSG00000235162,C12orf75,protein_coding,627,56,231,253,47,22188,52,620,113,203,70,0.563498,0,24460
2,ENSG00000235174,RPL39P3,processed_pseudogene,73,87,72,89,12,13687,0,213,11,663,58,0.612907,0,14965

In [47]:
df_tumor3.head(30)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000135919,SERPINE2,protein_coding,189,821,1026,2040,1170,216535,5,599,193,1394,754,0.329341,0,224726
1,ENSG00000235162,C12orf75,protein_coding,627,56,231,253,47,22188,52,620,113,203,70,0.563498,0,24460
2,ENSG00000235174,RPL39P3,processed_pseudogene,73,87,72,89,12,13687,0,213,11,663,58,0.612907,0,14965
3,ENSG00000080823,MOK,protein_coding,61,120,114,166,139,13949,15,93,79,424,112,0.614011,0,15272
4,ENSG00000101955,SRPX,protein_coding,52,600,238,82,183,16806,0,96,36,284,78,0.672237,0,18455
5,ENSG00000178031,ADAMTSL1,protein_coding,62,58,148,28,107,6498,10,10,53,170,82,0.673331,0,7226
6,ENSG00000164266,SPINK1,protein_coding,64067,83,10713,10,85,63,0,11,81,252,41,0.677665,0,75406
7,ENSG00000108602,ALDH3A1,protein_coding,4439,635,54,70,10533,17,1,22,4,114336,293,0.696827,0,130404
8,ENSG00000152049,KCNE4,protein_coding,33,73,417,128,104,184,1,331,34,15081,243,0.701489,0,16629
9,ENSG00000174028,FAM3C2P,processed_pseudogene,29,224,115,23,69,8168,0,215,95,249,122,0.887762,0,9309
10,ENSG00000183287,CCBE1,protein_coding,40,96,204,22,118,5339,0,160,28,89,87,0.969824,0,6183
11,ENSG00000100302,RASD2,protein_coding,33,55,280,6833,72,278,1,39,171,48,146,0.972276,0,7956
12,ENSG00000234851,RPL23AP42,processed_pseudogene,78,41,115,87,21,5254,0,139,29,315,55,0.983687,0,6134
13,ENSG00000164465,DCBLD1,protein_coding,383,833,818,261,658,37806,72,809,459,1049,1732,1.018384,0,44880
14,ENSG00000101842,VSIG1,protein_coding,76,485,151,26,24,36,12,6823,68,586,55,1.026197,0,8342
15,ENSG00000218426,AL590867.2,processed_pseudogene,83,100,103,78,15,5620,0,55,39,617,49,1.041269,0,6759
16,ENSG00000229867,STEAP3-AS1,lncRNA,65,149,236,70,222,5696,82,168,77,516,167,1.046433,0,7448
17,ENSG00000174837,ADGRE1,protein_coding,60,61,60,2,63,2084,0,9,22,58,59,1.089716,0,2478
18,ENSG00000101938,CHRDL1,protein_coding,53,469,533,313,245,14553,0,27,86,1080,239,1.116503,0,17598
19,ENSG00000152128,TMEM163,protein_coding,244,390,389,186,88,323,19,553,415,14020,251,1.117022,0,16878
20,ENSG00000246859,STARD4-AS1,lncRNA,482,473,1155,25030,454,1092,2704,822,506,1523,805,1.117713,0,35046
21,ENSG00000118308,IRAG2,protein_coding,14,53,179,5050,126,219,23,36,117,288,124,1.133032,0,6229
22,ENSG00000214548,MEG3,lncRNA,241,36,137,75,40,320,3,75,87,5238,106,1.147645,0,6358
23,ENSG00000168679,SLC16A4,protein_coding,1699,139,294,52,1017,1593,483,48,391,23929,190,1.148941,0,29835
24,ENSG00000021826,CPS1,protein_coding,10262,280,57,27,2854,278,1,38,6,71,67,1.169496,0,13941
25,ENSG00000159228,CBR1,protein_coding,1100,1651,1315,971,1617,6124,1,1062,735,72218,2014,1.217479,0,88808
26,ENSG00000007402,CACNA2D2,protein_coding,888,382,1797,76,477,1301,70,322,94,19349,285,1.239488,0,25041
27,ENSG00000164867,NOS3,protein_coding,104,152,460,118,371,581,6,482,707,13430,225,1.253099,0,16636
28,ENSG00000153446,C16orf89,protein_coding,802,825,2975,30,286,1695,1,264,1407,32931,264,1.262399,0,41480
29,ENSG00000169550,MUC15,protein_coding,132,818,115,29,13,1399,48,102,430,102,10439,1.265104,0,13627

In [49]:
df_tumor3.tail(30)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
1552,ENSG00000205542,TMSB4X,protein_coding,10410,56120,50469,23782,14338,247913,25,24118,22609,87685,15153,2.558076,0,552622
1553,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,0,0,55,476,409,1057,608,2.558131,0,4015
1554,ENSG00000169093,ASMTL,protein_coding,474,0,936,819,417,0,55,476,0,1057,0,2.558485,0,4234
1555,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,417,2019,0,0,409,1057,608,2.558664,0,5920
1556,ENSG00000133134,BEX2,protein_coding,218,120,511,948,36,2379,0,428,6,680,538,2.558702,0,5864
1557,ENSG00000169093,ASMTL,protein_coding,474,766,936,0,0,0,55,476,409,1057,0,2.558892,0,4173
1558,ENSG00000169093,ASMTL,protein_coding,0,0,936,0,417,2019,0,476,409,1057,608,2.559029,0,5922
1559,ENSG00000144120,TMEM177,protein_coding,356,214,316,271,153,2433,0,398,145,535,175,2.559243,0,4996
1560,ENSG00000096088,PGC,protein_coding,632,757,1394,10,621,2151,4,20,182,2587,149,2.559266,0,8507
1561,ENSG00000272288,AL451165.2,lncRNA,150,137,196,208,141,335,131,136,126,341,347,2.559293,0,2248
1562,ENSG00000182378,PLCXD1,protein_coding,0,173,353,790,216,845,9,411,0,0,1140,2.559420,0,3937
1563,ENSG00000169093,ASMTL,protein_coding,474,766,0,819,417,0,55,0,409,1057,0,2.559435,0,3997
1564,ENSG00000143502,SUSD4,protein_coding,48,843,258,164,39,32,1,150,142,886,142,2.559459,0,2705
1565,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,417,0,55,476,0,1057,608,2.559572,0,4023
1566,ENSG00000162757,C1orf74,protein_coding,193,133,234,379,171,774,106,207,139,811,187,2.559629,0,3334
1567,ENSG00000169093,ASMTL,protein_coding,0,766,0,819,417,0,55,476,409,1057,0,2.559692,0,3999
1568,ENSG00000174791,RIN1,protein_coding,146,186,221,51,254,1592,1,402,149,269,86,2.559761,0,3357
1569,ENSG00000182378,PLCXD1,protein_coding,315,173,353,0,0,0,0,411,321,424,1140,2.559801,0,3137
1570,ENSG00000169093,ASMTL,protein_coding,474,766,936,0,417,0,55,476,0,1057,0,2.560384,0,4181
1571,ENSG00000112936,C7,protein_coding,893,1329,3357,490,1824,5631,1,28,449,8843,1269,2.560412,0,24114
1572,ENSG00000285830,AL109628.2,lncRNA,240,341,592,290,318,1050,1219,393,293,1489,377,2.560413,0,6602
1573,ENSG00000169093,ASMTL,protein_coding,0,0,936,819,417,0,55,0,409,1057,608,2.560624,0,4301
1574,ENSG00000005020,SKAP2,protein_coding,1495,695,1753,810,1372,11674,2,1429,702,2302,1562,2.560761,0,23796
1575,ENSG00000221890,NPTXR,protein_coding,663,93,185,742,160,2272,1,229,123,491,189,2.561256,0,5148
1576,ENSG00000169093,ASMTL,protein_coding,474,0,0,819,417,0,55,0,409,1057,608,2.561270,0,3839
1577,ENSG00000115009,CCL20,protein_coding,53,164,572,79,709,227,5,3214,1272,2316,3080,2.561322,0,11691
1578,ENSG00000169093,ASMTL,protein_coding,0,0,0,819,417,0,55,476,409,1057,608,2.561507,0,3841
1579,ENSG00000182378,PLCXD1,protein_coding,0,173,353,790,216,845,9,0,0,424,1140,2.561659,0,3950
1580,ENSG00000169093,ASMTL,protein_coding,474,766,0,819,0,2019,0,476,409,0,608,2.561991,0,5571
1581,ENSG00000169093,ASMTL,protein_coding,0,766,936,0,417,0,55,0,409,1057,608,2.562234,0,4248

In [50]:
geneid_list = np.unique(df_tumor3['gene_id'])

len(geneid_list)

1018

### GTEx portal

In [68]:
print(len(geneid_list))
np.array(geneid_list[:50])

1018

array(['ENSG00000001626', 'ENSG00000003989', 'ENSG00000004468',
       'ENSG00000005020', 'ENSG00000005059', 'ENSG00000006007',
       'ENSG00000006016', 'ENSG00000006210', 'ENSG00000006534',
       'ENSG00000006747', 'ENSG00000007402', 'ENSG00000008226',
       'ENSG00000008735', 'ENSG00000008853', 'ENSG00000012171',
       'ENSG00000017483', 'ENSG00000018236', 'ENSG00000019102',
       'ENSG00000019186', 'ENSG00000021300', 'ENSG00000021826',
       'ENSG00000022267', 'ENSG00000022556', 'ENSG00000023171',
       'ENSG00000023839', 'ENSG00000025423', 'ENSG00000025708',
       'ENSG00000026103', 'ENSG00000026508', 'ENSG00000029153',
       'ENSG00000034053', 'ENSG00000038002', 'ENSG00000040531',
       'ENSG00000043039', 'ENSG00000047457', 'ENSG00000047662',
       'ENSG00000047936', 'ENSG00000048052', 'ENSG00000049247',
       'ENSG00000051128', 'ENSG00000053918', 'ENSG00000057294',
       'ENSG00000060718', 'ENSG00000060982', 'ENSG00000062038',
       'ENSG00000064199', 'ENSG00000064205', 'ENSG00000064225',
       'ENSG00000064763', 'ENSG00000064787'], dtype=object)

In [69]:
GTEX_API = "https://gtexportal.org/api/v2"

In [70]:
def resolve_gtex_gencode_id(gene_id, datasetId="gtex_v8", timeout=60):
    gene_base = str(gene_id).split(".")[0]

    url = f"{GTEX_API}/reference/gene"

    params = {
        "geneId": gene_base,
        "datasetId": datasetId,
    }

    r = requests.get(url, params=params, timeout=timeout)
    r.raise_for_status()

    data = r.json().get("data", [])

    if not data:
        return None

    return data[0].get("gencodeId")

In [74]:


def get_gtex_expression_for_geneid_list(
    gtex_id:str,
    geneid_list:list,
    datasetId:str="gtex_v8",
    page_size:int=1000,
    sleep: float = 0.1,
    timeout:int=60,
    verbose:bool=False,
):
    """
    Download GTEx normal tissue expression for selected genes.
    Returns long-format dataframe:
    geneSymbol | gencodeId | tissueSiteDetailId | sampleId | tpm | log2Tpm
    """

    all_rows = []

    print(">>>", len(geneid_list))
    for i, geneid in enumerate(geneid_list):
        page = 0

        while True:

            gencode_id = resolve_gtex_gencode_id(geneid)
            print(">>>", gencode_id, end=" ")

            if gencode_id is None:
                print("?")
                if verbose: print(f"Nothing found for {geneid}")
                break
            
            url = f"{GTEX_API}/expression/geneExpression"

            params = {
                "datasetId": datasetId,
                "gencodeId": gencode_id,
                "tissueSiteDetailId": gtex_id,
                "page": page,
                "itemsPerPage": page_size,
            }

            r = requests.get(url, params=params, timeout=timeout)
            r.raise_for_status()

            js = r.json()
            data = js.get("data", [])

            if not data:
                print("x")
                if verbose: print(f"Error: could not retrieve data for {gtex_id} for geneid '{geneid}'")
                break

            print("Ok")

            all_rows.extend(data)

            paging = js.get("paging_info", {})
            n_pages = paging.get("numberOfPages", 1)

            page += 1
            if page >= n_pages:
                break

            time.sleep(sleep)

    print("")
    df = pd.DataFrame(all_rows)
    return df

In [75]:
gtex_id

'Lung'

In [ ]:
df_gtex = get_gtex_expression_for_geneid_list(
                gtex_id=gtex_id,
                geneid_list=geneid_list,
                datasetId="gtex_v8",
                page_size=1000,
                sleep = 0.1,
                timeout=60)

print(df_gtex.shape)

>>> 1018
>>> ENSG00000001626.14 Ok
>>> ENSG00000003989.17 Ok
>>> ENSG00000004468.12 Ok
>>> ENSG00000005020.12 Ok
>>> ENSG00000005059.15 Ok
>>> ENSG00000006007.11 Ok
>>> ENSG00000006016.10 Ok
>>> ENSG00000006210.6 Ok
>>> ENSG00000006534.15 Ok
>>> ENSG00000006747.14 Ok
>>> ENSG00000007402.11 Ok
>>> ENSG00000008226.19 Ok
>>> ENSG00000008735.13 Ok
>>> ENSG00000008853.16 Ok
>>> ENSG00000012171.19 Ok
>>> ENSG00000017483.14 Ok
>>> ENSG00000018236.14 Ok
>>> ENSG00000019102.11 Ok
>>> ENSG00000019186.9 Ok
>>> ENSG00000021300.13 Ok
>>> ENSG00000021826.14 Ok
>>> ENSG00000022267.16 Ok
>>> ENSG00000022556.15 Ok
>>> ENSG00000023171.16 Ok
>>> ENSG00000023839.10 Ok
>>> ENSG00000025423.11 Ok
>>> ENSG00000025708.13 Ok
>>> ENSG00000026103.21 Ok
>>> ENSG00000026508.17 Ok
>>> ENSG00000029153.14 Ok
>>> ENSG00000034053.14 Ok
>>> ENSG00000038002.8 Ok
>>> ENSG00000040531.14 Ok
>>> ENSG00000043039.6 Ok
>>> ENSG00000047457.13 Ok
>>> ENSG00000047662.4 Ok
>>> ENSG00000047936.10 Ok
>>> ENSG00000048052.21 Ok
>>> ENSG00000049247.13 Ok
>>> ENSG00000051128.18 Ok
>>> ENSG00000053918.15 Ok
>>> ENSG00000057294.14 Ok
>>> ENSG00000060718.20 Ok
>>> ENSG00000060982.14 Ok
>>> ENSG00000062038.13 Ok
>>> ENSG00000064199.6 Ok
>>> ENSG00000064205.10 Ok
>>> ENSG00000064225.12 Ok
>>> ENSG00000064763.10 Ok
>>> ENSG00000064787.13 Ok
>>> ENSG00000064886.13 Ok
>>> ENSG00000065328.16 Ok
>>> ENSG00000066405.12 Ok
>>> ENSG00000066855.15 Ok
>>> ENSG00000067057.16 Ok
>>> ENSG00000068078.17 Ok
>>> ENSG00000069122.18 Ok
>>> ENSG00000069188.16 Ok
>>> ENSG00000069535.13 Ok
>>> ENSG00000070019.4 Ok
>>> ENSG00000070182.19 Ok
>>> ENSG00000070961.15 Ok
>>> ENSG00000072210.18 Ok
>>> ENSG00000072756.16 Ok
>>> ENSG00000072858.10 Ok
>>> ENSG00000072864.14 Ok
>>> ENSG00000073282.12 Ok
>>> ENSG00000073756.11 Ok
>>> ENSG00000073792.15 Ok
>>> ENSG00000074706.13 Ok
>>> ENSG00000075213.10 Ok
>>> ENSG00000075239.13 Ok
>>> ENSG00000075461.5 Ok
>>> ENSG00000075643.5 Ok
>>> ENSG00000075975.15 Ok
>>> ENSG00000076864.19 Ok
>>> ENSG00000078018.19 Ok
>>> ENSG00000080293.9 Ok
>>> ENSG00000080819.6 Ok
>>> ENSG00000080823.22 Ok
>>> ENSG00000081059.19 Ok
>>> ENSG00000085276.17 Ok
>>> ENSG00000085662.13 Ok
>>> ENSG00000085788.13 Ok
>>> ENSG00000085998.13 Ok
>>> ENSG00000087128.9 Ok
>>> ENSG00000087470.17 Ok
>>> ENSG00000087842.10 Ok
>>> ENSG00000088205.12 Ok
>>> ENSG00000088305.18 Ok
>>> ENSG00000088992.17 Ok
>>> ENSG00000089041.16 Ok
>>> ENSG00000090530.9 Ok
>>> ENSG00000091129.19 Ok
>>> ENSG00000091136.13 Ok
>>> ENSG00000091651.8 Ok
>>> ENSG00000091831.22 Ok
>>> ENSG00000091844.7 Ok
>>> ENSG00000092621.11 Ok
>>> ENSG00000093009.9 Ok
>>> ENSG00000095303.14 Ok
>>> ENSG00000095539.15 Ok
>>> ENSG00000095713.13 Ok
>>> ENSG00000095739.10 Ok
>>> ENSG00000096088.16 Ok
>>> ENSG00000096696.13 Ok
>>> ENSG00000099204.18 Ok
>>> ENSG00000099377.13 Ok
>>> ENSG00000099804.8 Ok
>>> ENSG00000099812.8 Ok
>>> ENSG00000099937.10 Ok
>>> ENSG00000099994.10 Ok
>>> ENSG00000100003.17 Ok
>>> ENSG00000100065.14 Ok
>>> ENSG00000100097.11 Ok
>>> ENSG00000100167.19 Ok
>>> ENSG00000100302.6 Ok
>>> ENSG00000100473.15 Ok
>>> ENSG00000100567.12 Ok
>>> ENSG00000100749.7 Ok
>>> ENSG00000101003.9 Ok
>>> ENSG00000101057.15 Ok
>>> ENSG00000101210.10 Ok
>>> ENSG00000101336.13 Ok
>>> ENSG00000101457.12 Ok
>>> ENSG00000101670.11 Ok
>>> ENSG00000101842.13 Ok
>>> ENSG00000101928.12 Ok
>>> ENSG00000101938.14 Ok
>>> ENSG00000101955.14 Ok
>>> ENSG00000102466.15 Ok
>>> ENSG00000102854.15 Ok
>>> ENSG00000102910.13 Ok
>>> ENSG00000102962.4 Ok
>>> ENSG00000103460.16 Ok
>>> ENSG00000103888.16 Ok
>>> ENSG00000103942.12 Ok
>>> ENSG00000104154.6 Ok
>>> ENSG00000104218.14 Ok
>>> ENSG00000104221.12 Ok
>>> ENSG00000104368.17 Ok
>>> ENSG00000104524.13 Ok
>>> ENSG00000104691.14 Ok
>>> ENSG00000104760.16 Ok
>>> ENSG00000104892.16 Ok
>>> ENSG00000104907.12 Ok
>>> ENSG00000104980.7 Ok
>>> ENSG00000105364.13 Ok
>>> ENSG00000105388.15 Ok
>>> ENSG00000105464.3 Ok
>>> ENSG00000105664.10 Ok
>>> ENSG00000105825.11 Ok
>>> ENSG00000105855.9 Ok
>>> ENSG00000105877.17 Ok
>>> ENSG00000105997.22 Ok
>>> ENSG00000106066.14 Ok
>>> ENSG00000106565.17 Ok
>>> ENSG00000107201.9 Ok
>>> ENSG00000107562.16 Ok
>>> ENSG00000107833.10 Ok
>>> ENSG00000108474.16 Ok
>>> ENSG00000108551.4 Ok
>>> ENSG00000108602.17 Ok
>>> ENSG00000109321.10 Ok
>>> ENSG00000109674.3 Ok
>>> ENSG00000109805.9 Ok
>>> ENSG00000109861.15 Ok
>>> ENSG00000109906.13 Ok
>>> ENSG00000110195.12 Ok
>>> ENSG00000110811.19 Ok
>>> ENSG00000110900.14 Ok
>>> ENSG00000111110.11 Ok
>>> ENSG00000111186.12 Ok
>>> ENSG00000111247.14 Ok
>>> ENSG00000111275.12 Ok
>>> ENSG00000111452.12 Ok
>>> ENSG00000111615.13 Ok
>>> ENSG00000111799.20 Ok
>>> ENSG00000111817.16 Ok
>>> ENSG00000111875.7 Ok
>>> ENSG00000112237.12 Ok
>>> ENSG00000112742.9 Ok
>>> ENSG00000112769.18 Ok
>>> ENSG00000112936.18 Ok
>>> ENSG00000113319.12 Ok
>>> ENSG00000113494.16 Ok
>>> ENSG00000113749.7 Ok
>>> ENSG00000113851.14 Ok
>>> ENSG00000113924.11 Ok
>>> ENSG00000114270.17 Ok
>>> ENSG00000114790.12 Ok
>>> ENSG00000115009.11 Ok
>>> ENSG00000115107.19 Ok
>>> ENSG00000115221.10 Ok
>>> ENSG00000115255.10 Ok
>>> ENSG00000115380.19 Ok
>>> ENSG00000115414.18 Ok
>>> ENSG00000115419.12 Ok
>>> ENSG00000115457.9 Ok
>>> ENSG00000115641.18 Ok
>>> ENSG00000115841.19 Ok
>>> ENSG00000115919.14 Ok
>>> ENSG00000116106.11 Ok
>>> ENSG00000116132.11 Ok
>>> ENSG00000116299.16 Ok
>>> ENSG00000116661.9 Ok
>>> ENSG00000116711.9 Ok
>>> ENSG00000116761.11 Ok
>>> ENSG00000116774.11 Ok
>>> ENSG00000116991.10 Ok
>>> ENSG00000117091.9 Ok
>>> ENSG00000117228.9 Ok
>>> ENSG00000117472.9 Ok
>>> ENSG00000117525.13 Ok
>>> ENSG00000117983.17 Ok
>>> ENSG00000118308.15 Ok
>>> ENSG00000118407.14 Ok
>>> ENSG00000118513.18 Ok
>>> ENSG00000118849.9 Ok
>>> ENSG00000119655.10 Ok
>>> ENSG00000119917.13 Ok
>>> ENSG00000119922.9 Ok
>>> ENSG00000119927.13 Ok
>>> ENSG00000119938.8 Ok
>>> ENSG00000120217.13 Ok
>>> ENSG00000120675.5 Ok
>>> ENSG00000120885.21 Ok
>>> ENSG00000120992.17 Ok
>>> ENSG00000121039.9 Ok
>>> ENSG00000121281.12 Ok
>>> ENSG00000121350.15 Ok
>>> ENSG00000121361.3 Ok
>>> ENSG00000122852.14 Ok
>>> ENSG00000122862.4 Ok
>>> ENSG00000123094.15 Ok
>>> ENSG00000123552.17 Ok
>>> ENSG00000123689.5 Ok
>>> ENSG00000123838.10 Ok
>>> ENSG00000124120.10 Ok
>>> ENSG00000124191.17 Ok
>>> ENSG00000124243.17 Ok
>>> ENSG00000124429.17 Ok
>>> ENSG00000124615.17 Ok
>>> ENSG00000125378.15 Ok
>>> ENSG00000125629.14 Ok
>>> ENSG00000125656.8 Ok
>>> ENSG00000125731.12 Ok
>>> ENSG00000125775.14 Ok
>>> ENSG00000125827.8 Ok
>>> ENSG00000125872.7 Ok
>>> ENSG00000125966.9 Ok
>>> ENSG00000125999.10 Ok
>>> ENSG00000126215.13 Ok
>>> ENSG00000126878.12 Ok
>>> ENSG00000127324.8 Ok
>>> ENSG00000128422.15 Ok
>>> ENSG00000128578.9 Ok
>>> ENSG00000128591.15 Ok
>>> ENSG00000128944.13 Ok
>>> ENSG00000129354.11 Ok
>>> ENSG00000129355.6 Ok
>>> ENSG00000129680.15 Ok
>>> ENSG00000129682.15 Ok
>>> ENSG00000129810.14 Ok
>>> ENSG00000130270.16 Ok
>>> ENSG00000130303.12 Ok
>>> ENSG00000130332.14 Ok
>>> ENSG00000130812.10 Ok
>>> ENSG00000130816.14 Ok
>>> ENSG00000130830.14 Ok
>>> ENSG00000130962.17 Ok
>>> ENSG00000131203.12 Ok
>>> ENSG00000131400.7 Ok
>>> ENSG00000131401.11 Ok
>>> ENSG00000131408.13 Ok
>>> ENSG00000131470.14 Ok
>>> ENSG00000131746.12 Ok
>>> ENSG00000131771.13 Ok
>>> ENSG00000131781.12 Ok
>>> ENSG00000132004.12 Ok
>>> ENSG00000132017.10 Ok
>>> ENSG00000132182.11 Ok
>>> ENSG00000132274.15 Ok
>>> ENSG00000132688.10 Ok
>>> ENSG00000132840.9 Ok
>>> ENSG00000133048.12 Ok
>>> ENSG00000133106.14 Ok
>>> ENSG00000133134.11 Ok
>>> ENSG00000133135.13 Ok
>>> ENSG00000133641.17 Ok
>>> ENSG00000133661.15 Ok
>>> ENSG00000133703.11 Ok
>>> ENSG00000133740.10 Ok
>>> ENSG00000133794.17 Ok
>>> ENSG00000133812.15 Ok
>>> ENSG00000133818.13 Ok
>>> ENSG00000134020.7 Ok
>>> ENSG00000134077.15 Ok
>>> ENSG00000134121.9 Ok
>>> ENSG00000134152.10 Ok
>>> ENSG00000134222.16 Ok
>>> ENSG00000134258.16 Ok
>>> ENSG00000134321.11 Ok
>>> ENSG00000134326.11 Ok
>>> ENSG00000134490.13 Ok
>>> ENSG00000134504.12 Ok
>>> ENSG00000134668.12 Ok
>>> ENSG00000134775.15 Ok
>>> ENSG00000134986.13 Ok
>>> ENSG00000135114.12 Ok
>>> ENSG00000135119.14 Ok
>>> ENSG00000135299.16 Ok
>>> ENSG00000135318.11 Ok
>>> ENSG00000135362.13 Ok
>>> ENSG00000135423.12 Ok
>>> ENSG00000135451.12 Ok
>>> ENSG00000135549.14 Ok
>>> ENSG00000135678.11 Ok
>>> ENSG00000135778.11 Ok
>>> ENSG00000135919.12 Ok
>>> ENSG00000136155.16 Ok
>>> ENSG00000136982.5 Ok
>>> ENSG00000137124.7 Ok
>>> ENSG00000137135.17 Ok
>>> ENSG00000137203.10 Ok
>>> ENSG00000137310.11 Ok
>>> ENSG00000137331.11 Ok
>>> ENSG00000137440.4 Ok
>>> ENSG00000137547.8 Ok
>>> ENSG00000137628.16 Ok
>>> ENSG00000137673.8 Ok
>>> ENSG00000137699.16 Ok
>>> ENSG00000137709.9 Ok
>>> ENSG00000137745.11 Ok
>>> ENSG00000137825.10 Ok
>>> ENSG00000137868.18 Ok
>>> ENSG00000137959.15 Ok
>>> ENSG00000137962.12 Ok
>>> ENSG00000137965.10 Ok
>>> ENSG00000137968.16 Ok
>>> ENSG00000137970.7 Ok
>>> ENSG00000138135.6 Ok
>>> ENSG00000138162.18 Ok
>>> ENSG00000138271.5 Ok
>>> ENSG00000138615.5 Ok
>>> ENSG00000138640.14 Ok
>>> ENSG00000138646.8 Ok
>>> ENSG00000138678.10 Ok
>>> ENSG00000138755.5 Ok
>>> ENSG00000138764.14 Ok
>>> ENSG00000138772.12 Ok
>>> ENSG00000138785.14 Ok
>>> ENSG00000139146.13 Ok
>>> ENSG00000139239.7 Ok
>>> ENSG00000139278.9 Ok
>>> ENSG00000139318.7 Ok
>>> ENSG00000139351.14 Ok
>>> ENSG00000139508.14 Ok
>>> ENSG00000139626.15 Ok
>>> ENSG00000139629.15 Ok
>>> ENSG00000140105.17 Ok
>>> ENSG00000140254.12 Ok
>>> ENSG00000140297.12 Ok
>>> ENSG00000140534.13 Ok
>>> ENSG00000140564.11 Ok
>>> ENSG00000140945.16 Ok
>>> ENSG00000141576.14 Ok
>>> ENSG00000141994.15 Ok
>>> ENSG00000142459.8 Ok
>>> ENSG00000142512.14 Ok
>>> ENSG00000143153.12 Ok
>>> ENSG00000143156.13 Ok
>>> ENSG00000143228.12 Ok
>>> ENSG00000143257.11 Ok
>>> ENSG00000143320.8 Ok
>>> ENSG00000143412.9 Ok
>>> ENSG00000143416.20 Ok
>>> ENSG00000143502.14 Ok
>>> ENSG00000143507.17 Ok
>>> ENSG00000143512.12 Ok
>>> ENSG00000143546.9 Ok
>>> ENSG00000143653.9 Ok
>>> ENSG00000143819.12 Ok
>>> ENSG00000143891.16 Ok
>>> ENSG00000144118.13 Ok
>>> ENSG00000144120.12 Ok
>>> ENSG00000144476.5 Ok
>>> ENSG00000144868.13 Ok
>>> ENSG00000145113.21 Ok
>>> ENSG00000145287.10 Ok
>>> ENSG00000145358.6 Ok
>>> ENSG00000145386.9 Ok
>>> ENSG00000145824.12 Ok
>>> ENSG00000146122.16 Ok
>>> ENSG00000146166.16 Ok
>>> ENSG00000146197.8 Ok
>>> ENSG00000146477.5 Ok
>>> ENSG00000146648.17 Ok
>>> ENSG00000147364.16 Ok
>>> ENSG00000147536.11 Ok
>>> ENSG00000147548.16 Ok
>>> ENSG00000147642.16 Ok
>>> ENSG00000147687.18 Ok
>>> ENSG00000147872.9 Ok
>>> ENSG00000148346.11 Ok
>>> ENSG00000148671.13 Ok
>>> ENSG00000148702.14 Ok
>>> ENSG00000149021.6 Ok
>>> ENSG00000149260.15 Ok
>>> ENSG00000149557.12 Ok
>>> ENSG00000150636.17 Ok
>>> ENSG00000150782.11 Ok
>>> ENSG00000151012.13 Ok
>>> ENSG00000151090.17 Ok
>>> ENSG00000151332.18 Ok
>>> ENSG00000151474.21 Ok
>>> ENSG00000151575.14 Ok
>>> ENSG00000151632.17 Ok
>>> ENSG00000151651.15 Ok
>>> ENSG00000152049.6 Ok
>>> ENSG00000152128.13 Ok
>>> ENSG00000152137.6 Ok
>>> ENSG00000152229.18 Ok
>>> ENSG00000152284.4 Ok
>>> ENSG00000152455.15 Ok
>>> ENSG00000152784.15 Ok
>>> ENSG00000152785.6 Ok
>>> ENSG00000153292.15 Ok
>>> ENSG00000153363.12 Ok
>>> ENSG00000153446.15 Ok
>>> ENSG00000154025.15 Ok
>>> ENSG00000154040.20 Ok
>>> ENSG00000154065.16 Ok
>>> ENSG00000154146.12 Ok
>>> ENSG00000154277.12 Ok
>>> ENSG00000154319.14 Ok
>>> ENSG00000154451.14 Ok
>>> ENSG00000154556.17 Ok
>>> ENSG00000154839.9 Ok
>>> ENSG00000155096.13 Ok
>>> ENSG00000155307.17 Ok
>>> ENSG00000155380.11 Ok
>>> ENSG00000155438.11 Ok
>>> ENSG00000155657.26 Ok
>>> ENSG00000155659.14 Ok
>>> ENSG00000155760.2 Ok
>>> ENSG00000155957.17 Ok
>>> ENSG00000155962.12 Ok
>>> ENSG00000156050.8 Ok
>>> ENSG00000156234.7 Ok
>>> ENSG00000156298.12 Ok
>>> ENSG00000156299.13 Ok
>>> ENSG00000156463.17 Ok
>>> ENSG00000156510.12 Ok
>>> ENSG00000156535.13 Ok
>>> ENSG00000156738.17 Ok
>>> ENSG00000157064.10 Ok
>>> ENSG00000157399.14 Ok
>>> ENSG00000157404.15 Ok
>>> ENSG00000157456.7 Ok
>>> ENSG00000157601.13 Ok
>>> ENSG00000158125.9 Ok
>>> ENSG00000158467.16 Ok
>>> ENSG00000158825.5 Ok
>>> ENSG00000159164.9 Ok
>>> ENSG00000159167.11 Ok
>>> ENSG00000159189.11 Ok
>>> ENSG00000159212.12 Ok
>>> ENSG00000159228.12 Ok
>>> ENSG00000159231.5 Ok
>>> ENSG00000159348.12 Ok
>>> ENSG00000160111.12 Ok
>>> ENSG00000160180.15 Ok
>>> ENSG00000160469.16 Ok
>>> ENSG00000160862.12 Ok
>>> ENSG00000160932.10 Ok
>>> ENSG00000160957.12 Ok
>>> ENSG00000160973.7 Ok
>>> ENSG00000161055.3 Ok
>>> ENSG00000161888.11 Ok
>>> ENSG00000162545.5 Ok
>>> ENSG00000162645.12 Ok
>>> ENSG00000162654.8 Ok
>>> ENSG00000162738.5 Ok
>>> ENSG00000162757.4 Ok
>>> ENSG00000162896.5 Ok
>>> ENSG00000162949.16 Ok
>>> ENSG00000163072.15 Ok
>>> ENSG00000163075.12 Ok
>>> ENSG00000163110.14 Ok
>>> ENSG00000163141.18 Ok
>>> ENSG00000163220.10 Ok
>>> ENSG00000163235.15 Ok
>>> ENSG00000163297.16 Ok
>>> ENSG00000163568.14 Ok
>>> ENSG00000163577.7 Ok
>>> ENSG00000163584.17 Ok
>>> ENSG00000163636.10 Ok
>>> ENSG00000163659.12 Ok
>>> ENSG00000163735.6 Ok
>>> ENSG00000163762.6 Ok
>>> ENSG00000163879.10 Ok
>>> ENSG00000163975.11 Ok
>>> ENSG00000163993.6 Ok
>>> ENSG00000164070.11 Ok
>>> ENSG00000164087.7 Ok
>>> ENSG00000164099.3 Ok
>>> ENSG00000164109.13 Ok
>>> ENSG00000164120.13 Ok
>>> ENSG00000164176.12 Ok
>>> ENSG00000164265.8 Ok
>>> ENSG00000164266.10 Ok
>>> ENSG00000164292.12 Ok
>>> ENSG00000164414.17 Ok
>>> ENSG00000164430.15 Ok
>>> ENSG00000164465.18 Ok
>>> ENSG00000164694.16 Ok
>>> ENSG00000164758.7 Ok
>>> ENSG00000164867.10 Ok
>>> ENSG00000164930.11 Ok
>>> ENSG00000164949.7 Ok
>>> ENSG00000165046.12 Ok
>>> ENSG00000165272.14 Ok
>>> ENSG00000165304.7 Ok
>>> ENSG00000165516.10 Ok
>>> ENSG00000165525.17 Ok
>>> ENSG00000165819.11 Ok
>>> ENSG00000165949.12 Ok
>>> ENSG00000166016.5 Ok
>>> ENSG00000166123.13 Ok
>>> ENSG00000166143.9 Ok
>>> ENSG00000166206.14 Ok
>>> ENSG00000166250.11 Ok
>>> ENSG00000166347.18 Ok
>>> ENSG00000166532.15 Ok
>>> ENSG00000166582.9 Ok
>>> ENSG00000166669.13 Ok
>>> ENSG00000166676.14 Ok
>>> ENSG00000166741.7 Ok
>>> ENSG00000166816.13 Ok
>>> ENSG00000166825.13 Ok
>>> ENSG00000166851.14 Ok
>>> ENSG00000166920.12 Ok
>>> ENSG00000167191.11 Ok
>>> ENSG00000167286.9 Ok
>>> ENSG00000167476.10 Ok
>>> ENSG00000167601.11 Ok
>>> ENSG00000167702.11 Ok
>>> ENSG00000167711.13 Ok
>>> ENSG00000167775.10 Ok
>>> ENSG00000167779.7 Ok
>>> ENSG00000167815.11 Ok
>>> ENSG00000168032.8 Ok
>>> ENSG00000168306.12 Ok
>>> ENSG00000168484.12 Ok
>>> ENSG00000168517.10 Ok
>>> ENSG00000168675.18 Ok
>>> ENSG00000168679.17 Ok
>>> ENSG00000168874.12 Ok
>>> ENSG00000168878.16 Ok
>>> ENSG00000168899.4 Ok
>>> ENSG00000169083.16 Ok
>>> ENSG00000169093.15 Ok
>>> ENSG00000169129.14 Ok
>>> ENSG00000169184.5 Ok
>>> ENSG00000169213.6 Ok
>>> ENSG00000169245.5 Ok
>>> ENSG00000169435.13 Ok
>>> ENSG00000169550.12 Ok
>>> ENSG00000169583.12 Ok
>>> ENSG00000169814.12 Ok
>>> ENSG00000169894.17 Ok
>>> ENSG00000169908.11 Ok
>>> ENSG00000170425.3 Ok
>>> ENSG00000170456.15 Ok
>>> ENSG00000170522.9 Ok
>>> ENSG00000170561.12 Ok
>>> ENSG00000171004.18 Ok
>>> ENSG00000171017.10 Ok
>>> ENSG00000171174.13 Ok
>>> ENSG00000171241.8 Ok
>>> ENSG00000171346.15 Ok
>>> ENSG00000171476.21 Ok
>>> ENSG00000171497.4 Ok
>>> ENSG00000171557.16 Ok
>>> ENSG00000171560.14 Ok
>>> ENSG00000171564.11 Ok
>>> ENSG00000171766.15 Ok
>>> ENSG00000171791.12 Ok
>>> ENSG00000171903.16 Ok
>>> ENSG00000172009.14 Ok
>>> ENSG00000172167.7 Ok
>>> ENSG00000172175.12 Ok
>>> ENSG00000172201.11 Ok
>>> ENSG00000172250.14 Ok
>>> ENSG00000172270.18 Ok
>>> ENSG00000172296.12 Ok
>>> ENSG00000172724.11 Ok
>>> ENSG00000172927.7 Ok
>>> ENSG00000173068.17 Ok
>>> ENSG00000173110.7 Ok
>>> ENSG00000173267.13 Ok
>>> ENSG00000173369.15 Ok
>>> ENSG00000173376.13 Ok
>>> ENSG00000173467.8 Ok
>>> ENSG00000173702.7 Ok
>>> ENSG00000173848.18 Ok
>>> ENSG00000173890.16 Ok
>>> ENSG00000173947.13 Ok
>>> ENSG00000174028.6 Ok
>>> ENSG00000174502.18 Ok
>>> ENSG00000174514.12 Ok
>>> ENSG00000174564.12 Ok
>>> ENSG00000174749.5 Ok
>>> ENSG00000174791.10 Ok
>>> ENSG00000174808.11 Ok
>>> ENSG00000174837.14 Ok
>>> ENSG00000174917.8 Ok
>>> ENSG00000174939.10 Ok
>>> ENSG00000175084.11 Ok
>>> ENSG00000175264.7 Ok
>>> ENSG00000175265.17 Ok
>>> ENSG00000175287.18 Ok
>>> ENSG00000175305.17 Ok
>>> ENSG00000175318.11 Ok
>>> ENSG00000175592.8 Ok
>>> ENSG00000176124.11 Ok
>>> ENSG00000176153.11 Ok
>>> ENSG00000176208.8 Ok
>>> ENSG00000176619.12 Ok
>>> ENSG00000176623.11 Ok
>>> ENSG00000176834.13 Ok
>>> ENSG00000176907.4 Ok
>>> ENSG00000177337.7 Ok
>>> ENSG00000177508.11 Ok
>>> ENSG00000177575.12 Ok
>>> ENSG00000177694.15 Ok
>>> ENSG00000178031.16 Ok
>>> ENSG00000178460.17 Ok
>>> ENSG00000178605.13 Ok
>>> ENSG00000178826.10 Ok
>>> ENSG00000178999.12 Ok
>>> ENSG00000179023.8 Ok
>>> ENSG00000179115.10 Ok
>>> ENSG00000179152.19 Ok
>>> ENSG00000179178.10 Ok
>>> ENSG00000179564.3 Ok
>>> ENSG00000179593.15 Ok
>>> ENSG00000179715.12 Ok
>>> ENSG00000179750.15 Ok
>>> ENSG00000180340.6 Ok
>>> ENSG00000180772.6 Ok
>>> ENSG00000180801.13 Ok
>>> ENSG00000181019.12 Ok
>>> ENSG00000181315.10 Ok
>>> ENSG00000181458.10 Ok
>>> ENSG00000181634.7 Ok
>>> ENSG00000181649.5 Ok
>>> ENSG00000181652.19 Ok
>>> ENSG00000182272.11 Ok
>>> ENSG00000182378.13 Ok
>>> ENSG00000182667.14 Ok
>>> ENSG00000182752.9 Ok
>>> ENSG00000182795.12 Ok
>>> ENSG00000182809.10 Ok
>>> ENSG00000182963.9 Ok
>>> ENSG00000182985.17 Ok
>>> ENSG00000183020.13 Ok
>>> ENSG00000183098.10 Ok
>>> ENSG00000183196.8 Ok
>>> ENSG00000183287.13 Ok
>>> ENSG00000183580.9 Ok
>>> ENSG00000183617.4 Ok
>>> ENSG00000183779.6 Ok
>>> ENSG00000183844.16 Ok
>>> ENSG00000183856.10 Ok
>>> ENSG00000184254.16 Ok
>>> ENSG00000184454.6 Ok
>>> ENSG00000184828.9 Ok
>>> ENSG00000184979.9 Ok
>>> ENSG00000185088.13 Ok
>>> ENSG00000185189.17 Ok
>>> ENSG00000185565.11 Ok
>>> ENSG00000185633.10 Ok
>>> ENSG00000185689.15 Ok
>>> ENSG00000185697.16 Ok
>>> ENSG00000185745.9 Ok
>>> ENSG00000185885.15 Ok
>>> ENSG00000186205.12 Ok
>>> ENSG00000186377.7 Ok
>>> ENSG00000186567.12 Ok
>>> ENSG00000186638.16 Ok
>>> ENSG00000186818.12 Ok
>>> ENSG00000186832.8 Ok
>>> ENSG00000186891.13 Ok
>>> ENSG00000186907.7 Ok
>>> ENSG00000187091.13 Ok
>>> ENSG00000187134.13 Ok
>>> ENSG00000187608.8 Ok
>>> ENSG00000187840.4 Ok
>>> ENSG00000188153.12 Ok
>>> ENSG00000188343.12 Ok
>>> ENSG00000188536.12 Ok
>>> ENSG00000188549.12 Ok
>>> ENSG00000188641.12 Ok
>>> ENSG00000188672.17 Ok
>>> ENSG00000188687.17 Ok
>>> ENSG00000188910.7 Ok
>>> ENSG00000188921.13 Ok
>>> ENSG00000188959.9 Ok
>>> ENSG00000189058.8 Ok
>>> ENSG00000189120.4 Ok
>>> ENSG00000189221.9 Ok
>>> ENSG00000189223.14 Ok
>>> ENSG00000189334.8 Ok
>>> ENSG00000189377.8 Ok
>>> ENSG00000196126.11 Ok
>>> ENSG00000196139.13 Ok
>>> ENSG00000196151.10 Ok
>>> ENSG00000196154.11 Ok
>>> ENSG00000196155.12 Ok
>>> ENSG00000196167.9 Ok
>>> ENSG00000196177.12 Ok
>>> ENSG00000196188.10 Ok
>>> ENSG00000196205.8 Ok
>>> ENSG00000196260.4 Ok
>>> ENSG00000196470.11 Ok
>>> ENSG00000196611.4 Ok
>>> ENSG00000196616.13 Ok
>>> ENSG00000196735.11 Ok
>>> ENSG00000196754.10 Ok
>>> ENSG00000196937.10 Ok
>>> ENSG00000197249.13 Ok
>>> ENSG00000197635.9 Ok
>>> ENSG00000197696.9 Ok
>>> ENSG00000197959.13 Ok
>>> ENSG00000198223.16 Ok
>>> ENSG00000198356.11 Ok
>>> ENSG00000198502.5 Ok
>>> ENSG00000198734.10 Ok
>>> ENSG00000198736.11 Ok
>>> ENSG00000198743.6 Ok
>>> ENSG00000198848.12 Ok
>>> ENSG00000198879.11 Ok
>>> ENSG00000203697.11 Ok
>>> ENSG00000203760.8 Ok
>>> ENSG00000204228.3 Ok
>>> ENSG00000204257.14 Ok
>>> ENSG00000204287.13 Ok
>>> ENSG00000204305.13 Ok
>>> ENSG00000204381.11 Ok
>>> ENSG00000204396.10 Ok
>>> ENSG00000204514.9 Ok
>>> ENSG00000204623.9 Ok
>>> ENSG00000204642.13 Ok
>>> ENSG00000204681.10 Ok
>>> ENSG00000204839.8 Ok
>>> ENSG00000204977.9 Ok
>>> ENSG00000205542.10 Ok
>>> ENSG00000205707.10 Ok
>>> ENSG00000205790.1 Ok
>>> ENSG00000206075.13 Ok
>>> ENSG00000211445.11 Ok
>>> ENSG00000211460.11 Ok
>>> ENSG00000211598.2 Ok
>>> ENSG00000211637.2 Ok
>>> ENSG00000211638.2 Ok
>>> ENSG00000211640.4 Ok
>>> ENSG00000211648.2 Ok
>>> ENSG00000211649.3 Ok
>>> ENSG00000211651.3 Ok
>>> ENSG00000211653.2 Ok
>>> ENSG00000211659.2 Ok
>>> ENSG00000211660.3 Ok
>>> ENSG00000211662.2 Ok
>>> ENSG00000211663.2 Ok

In [ ]:
print(len(df_gtex))
df_gtex.head()

### GTEx download - per tissue

In [ ]:
def download_file(url, filename_out):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(filename_out, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)

In [ ]:
url_tpm = "https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_gene_counts.gct.gz"
url_meta = "https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt"
fname_out = "gtex_counts.gct.gz"
fname_meta = "gtex_meta.tsv"

filename_out = gdc.root_gtex / fname_out
filename_meta = gdc.root_gtex / fname_meta


# TPM matrix
download_file(url_tpm, filename_out)  

# metadata
download_file(url_meta, filename_meta)

### Reading GTEx count super-file

In [ ]:
# load matrix'1
df = pdreadcsv(fname_out, gdc.root_gtex, skiprows=2)

# load metadata
dfmeta = pdreadcsv(fname_meta, gdc.root_gtex)

# select lung samples
lung_samples = dfmeta.loc[dfmeta["SMTSD"] == "Lung", "SAMPID"].values

# subset expression
df_lung = df[["Name"] + list(lung_samples)].copy()
df_lung = df_lung.set_index("Name")