In [1]:
from platform import python_version
print(python_version())

3.11.14

In [2]:
import os, sys, yaml
from pathlib import Path
from dotenv import load_dotenv

import numpy as npmtd
import pandas as pd
pd.set_option('display.width', 100)
pd.set_option('max_colwidth', 80)
pd.set_option("display.precision", 3)

import seaborn as sns
sns.set_context("notebook", font_scale=1.4)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
%matplotlib inline

sys.path.insert(1, '../src/')

ROOT0 = Path("/home/flavio/uv/perturb_agent/")
ROOT_SRC = ROOT0 / "src"

if str(ROOT_SRC) not in sys.path:
    sys.path.append(str(ROOT_SRC))

print("ROOT0:", ROOT0)
print("ROOT_SRC added:", ROOT_SRC)

from libs.Basic import *
from libs.MTD_lib import MTD
from libs.GDC_lib import GDC
from libs.calc_degs_lib import CALC_DEGS
# from libs.dashcyto_lib import DASH_CYTO
from libs.config_lib import Config

from IPython.display import display, HTML
# display(HTML("<style>.container { width:100% !important; }</style>"))
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

with open('../params.yml', 'r') as file:
    dic_yml = yaml.safe_load(file)

# print(dic_yml)

ROOT0: /home/flavio/uv/perturb_agent
ROOT_SRC added: /home/flavio/uv/perturb_agent/src

In [3]:
email = os.getenv('email')

i_project=0

project_list = dic_yml['project_list']
n = len(project_list)
project = project_list[i_project]

s_project_list = dic_yml['s_project_list']
s_project = s_project_list[i_project]
assert n==len(project_list), f"Error project_list: there are {n} projects"

PROG_ID = 'TCGA'
PSI_ID = 'TCGA-BRCA'
PSI_ID = 'TCGA-ACC'
PSI_ID = 'TCGA-CESC'
PSI_ID = 'TCGA-PAAD'

ROOT0_DATA = ROOT0 / "data"
root_colab = ROOT0_DATA / 'colab'
root_project = ROOT0_DATA / PROG_ID

disease = PSI_ID

root_project = create_dir(ROOT0_DATA, s_project)
root_disease = create_dir(root_project, PSI_ID)

CONTEXT_DISESE = 'xxxx'
context_disease = CONTEXT_DISESE

gene_protein = dic_yml['gene_protein']
s_omics = dic_yml['s_omics']

has_age = dic_yml['has_age']
has_gender = dic_yml['has_gender']

exp_normalization = dic_yml['exp_normalization']
normalization = 'quantile_norm' if exp_normalization == True else 'not_normalized'

LFC_cut_inf = dic_yml['LFC_cut_inf']
s_pathw_enrichm_method = dic_yml['s_pathw_enrichm_method']
ptw_min_num_of_degs_cut = dic_yml['ptw_min_num_of_degs_cut']

tolerance_pPMI = dic_yml['tolerance_pPMI']
type_sat_ptw_index = dic_yml['type_sat_ptw_index']
saturation_lfc_param = dic_yml['saturation_lfc_param']

pval_pathway_cutoff = dic_yml['pval_pathway_cutoff']
fdr_pathway_cutoff = dic_yml['fdr_pathway_cutoff']
num_of_genes_cutoff = dic_yml['num_of_genes_cutoff']
enr_db_list = dic_yml['enr_db_list']


case_list = dic_yml['case_list']
dic_case_list = dic_yml['dic_case_list']

std_filename      = dic_yml['std_filename']
std_filename_list = dic_yml['std_filename_list']

min_lfc_modulation = dic_yml['min_lfc_modulation']
num_of_genes_list  = dic_yml['num_of_genes_list']
pPMI_normalized  = dic_yml['pPMI_normalized']

#--- max len for formatting purposes
s_len_case  = dic_yml['s_len_case']

n_sentences = dic_yml['n_sentences']
run_list = dic_yml['run_list']
chosen_model_list = dic_yml['chosen_model_list']
i_dfp_list = dic_yml['i_dfp_list']
chosen_model_sampling = dic_yml['chosen_model_sampling']

fdr_ptw_cutoff_list = np.arange(0.05, 0.80, 0.05)
lfc_list = np.round(np.arange(1.0, -0.01, -.025), 3)
fdr_list = np.arange(0.05, 0.76, .01)

cfg = Config(root0=ROOT0, root_disease=root_disease, disease=disease, case_list=case_list)
case = case_list[0]

n_genes_annot_ptw, n_degs, n_degs_in_ptw, n_degs_not_in_ptw, degs_in_all_ratio = -1,-1,-1,-1,-1

LFC_cut, lfc_FDR_cut, n_degs, n_degs_up, n_degs_dw = cfg.get_best_lfc_cutoff(case, 'not_normalized')

print(f"project '{project}', s_project '{s_project}'")
print(f"G/P LFC cutoffs: lfc={LFC_cut:.3f}; fdr={lfc_FDR_cut:.3f} - LFC_cut_inf={LFC_cut_inf:.3f}")
print(f"Pathway cutoffs: pval={pval_pathway_cutoff:.3f}; fdr={fdr_pathway_cutoff:.3f}; num of genes={num_of_genes_cutoff}")

Best parameter file for LFC does not exist /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD/config/all_lfc_cutoffs_TCGA-PAAD.tsv
project 'TCGA', s_project 'TCGA'
G/P LFC cutoffs: lfc=1.000; fdr=0.050 - LFC_cut_inf=0.400
Pathway cutoffs: pval=0.050; fdr=0.050; num of genes=3

In [4]:
mtd = MTD(disease=disease, gene_protein=gene_protein, s_omics=s_omics, project=project, s_project=s_project, 
          root0=ROOT0, root0_data=ROOT0_DATA, prog_id=PROG_ID, psi_id=PSI_ID,
          case_list=case_list, dic_case_list=dic_case_list, has_age=has_age, has_gender=has_gender, exp_normalization=exp_normalization,
          std_filename=std_filename, std_filename_list=std_filename_list,
          geneset_num=0, ptw_min_num_of_degs_cut=ptw_min_num_of_degs_cut,
          tolerance_pPMI=tolerance_pPMI, s_pathw_enrichm_method=s_pathw_enrichm_method,
          LFC_cut_inf=LFC_cut_inf, fdr_ptw_cutoff_list=fdr_ptw_cutoff_list,
          num_of_genes_list=num_of_genes_list, lfc_list=lfc_list, fdr_list=fdr_list, 
          min_lfc_modulation=min_lfc_modulation, type_sat_ptw_index=type_sat_ptw_index,
          saturation_lfc_param=saturation_lfc_param, enr_db_list=enr_db_list, pPMI_normalized=pPMI_normalized)

print(">>> Roots", mtd.root0, mtd.root_disease)
case = case_list[0]
print(">>>", case)

mtd.cfg.set_default_best_lfc_cutoff(mtd.normalization, LFC_cut=1, lfc_FDR_cut=0.05)
ret, degs, degs_ensembl, dfdegs = mtd.open_case(case, prompt_verbose=False, verbose=False)
# print("\nEcho Parameters:")
# print(mtd.echo_parameters())

>>> Roots /home/flavio/uv/perturb_agent /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD
>>> Tumor

### Get all programs

In [5]:
gdc = GDC(root0=ROOT0, root0_data=ROOT0_DATA, memory_restriction=False)

#--------- chose a disease --------------------
DISEASE_ID = 'ACC'
DISEASE_ID = 'PAAD'

In [6]:
verbose=False
force=False

method='deseq2'
imax_tumor=250
imax_normal=50

gdc = GDC(root0=ROOT0, root0_data=ROOT0_DATA, memory_restriction=False)

exclude_prog_list=['CCLE']

dfn_tumor, dfn_normal, df_gtex, df_summ = gdc.get_all_data_from_disease(disease_id=DISEASE_ID, 
                                                           imax_tumor=imax_tumor, imax_normal=imax_normal,
                                                           exclude_prog_list=exclude_prog_list,
                                                           force=force, verbose=verbose)
print("\n")
print(">> dfn_tumor", dfn_tumor.shape)
print(">> dfn_normal", dfn_normal.shape)

df_summ

>> dfn_tumor (60616, 460)
>> dfn_normal (60616, 103)

  prog_id          psi_id disease_id primary_site  n_tumors  n_normals
0   CPTAC      CPTAC-PAAD       PAAD     Pancreas       213         50
1   CPTAC  CPTAC-PAAD_GDC       PAAD     Pancreas       213         50
2    TCGA       TCGA-PAAD       PAAD     Pancreas        31          1

### Batch effect correction

In [8]:
force=False
verbose=True

perc_min_samples=0.25; top_n=10_000

df_combat = gdc.calc_cpm_merge_turmor_and_normal_batch_correction(dfn_tumor=dfn_tumor, dfn_normal=dfn_normal,
                                                                  perc_min_samples=perc_min_samples, top_n=top_n,
                                                                  force=force, verbose=verbose)
print(df_combat.shape)
df_combat.head(3)

Table opened ((10000, 458)) at '/home/flavio/uv/perturb_agent/data/multi_progs/PAAD/lfc/Tumor_expression_sel_log_CPM_top_10000_genes_all_samples.tsv'
Table opened ((20024, 458)) at '/home/flavio/uv/perturb_agent/data/multi_progs/PAAD/lfc/Tumor_expression_log_CPM_all_samples.tsv'
Table opened ((10000, 3)) at '/home/flavio/uv/perturb_agent/data/multi_progs/PAAD/lfc/Tumor_expression_gene_annot_top_10000_genes_all_samples.tsv'
Table opened ((10000, 560)) at '/home/flavio/uv/perturb_agent/data/multi_progs/PAAD/lfc/combat_log_exp_tumor_and_normal.tsv'
(10000, 560)

,geneid,symbol,biotype,1,2,3,4,5,6,7,...,548,549,550,551,552,553,554,555,556,557
0,ENSG00000270641,TSIX,lncRNA,13.955,13.211,13.898,13.478,13.710,11.679,13.350,...,2.868,3.028,5.113,2.322,3.620,4.659,13.198,4.548,3.652,14.046
1,ENSG00000262619,LINC00621,lncRNA,10.371,10.430,12.476,12.408,14.294,9.301,12.063,...,1.102,1.409,2.019,0.461,0.589,2.182,2.404,4.046,3.690,2.335
2,ENSG00000281383,FP671120.7,lncRNA,3.266,-0.078,10.497,-0.078,11.041,5.579,2.968,...,-0.146,-0.146,-0.146,-0.146,-0.146,-0.146,1.137,-0.146,0.574,-0.146

### Metadata

In [9]:
print(pd.crosstab(gdc.df_metadata["dataset"], gdc.df_metadata["condition"]))

condition       normal  tumor
dataset
CPTAC-PAAD          50    213
CPTAC-PAAD_GDC      50    213
TCGA-PAAD            0     31

### Clusterization

In [ ]:
disease_id=DISEASE_ID
imax_tumor=250
imax_normal=50
exclude_prog_list=['CCLE']
n_components = 10
n_umap_neighbors=5; min_umap_dist=0.2; umap_metric="euclidean"
method_hca="ward"; hca_criterion="maxclust"
LFC_cutoff=1; FDR_cutoff=0.05

group = 'Tumor'
for n_clusters in range(3, 10+1):
    min_clusters = 2; max_clusters = (n_clusters+2)

    verbose=False
    force=False

    print(f"Clusters: {n_clusters}")
    print("--------------------")

    df_cluster, df_pca, df_umap = gdc.cluster_PCA_HCA_UMAP(df_combat, group=group, n_clusters=n_clusters, 
                                                    n_components=n_components, min_clusters=min_clusters, max_clusters=max_clusters,
                                                    n_umap_neighbors=n_umap_neighbors, min_umap_dist=min_umap_dist, umap_metric=umap_metric,
                                                    method_hca=method_hca, hca_criterion=hca_criterion,
                                                    LFC_cutoff=LFC_cutoff, FDR_cutoff=FDR_cutoff,
                                                    force=force, verbose=verbose)
    print("--------------------")
    print(gdc.df_eval)
    print("--------------------\n")

Clusters: 3
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4565 signature genes
Cluster 2: 2962 signature genes
Cluster 3: 677 signature genes

-------------- end ------------------

--------------------
   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
--------------------

Clusters: 4
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 4362 signature genes
Cluster 3: 2962 signature genes
Cluster 4: 677 signature genes

-------------- end ------------------

--------------------
   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
4  6       0.434
--------------------

Clusters: 5
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 4362 signature genes
Cluster 3: 2962 signature genes
Cluster 4: 694 signature genes
Cluster 5: 394 signature genes

-------------- end ------------------

--------------------
   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
4  6       0.434
5  7       0.438
--------------------

Clusters: 6
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 3215 signature genes
Cluster 3: 4413 signature genes
Cluster 4: 2962 signature genes
Cluster 5: 694 signature genes
Cluster 6: 394 signature genes

-------------- end ------------------

--------------------
   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
4  6       0.434
5  7       0.438
6  8       0.454
--------------------

Clusters: 7
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 3215 signature genes
Cluster 3: 4413 signature genes
Cluster 4: 2962 signature genes
Cluster 5: 694 signature genes
Cluster 6: 5 signature genes
Cluster 7: 559 signature genes

-------------- end ------------------

--------------------
   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
4  6       0.434
5  7       0.438
6  8       0.454
7  9       0.454
--------------------

Clusters: 8
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 3215 signature genes
Cluster 3: 4413 signature genes
Cluster 4: 2962 signature genes
Cluster 5: 512 signature genes
Cluster 6: 388 signature genes
Cluster 7: 5 signature genes
Cluster 8: 559 signature genes

-------------- end ------------------

--------------------
    k  silhouette
0   2       0.578
1   3       0.532
2   4       0.493
3   5       0.493
4   6       0.434
5   7       0.438
6   8       0.454
7   9       0.454
8  10       0.461
--------------------

Clusters: 9
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 3215 signature genes
Cluster 3: 4600 signature genes
Cluster 4: 4268 signature genes
Cluster 5: 2962 signature genes
Cluster 6: 512 signature genes
Cluster 7: 388 signature genes
Cluster 8: 5 signature genes
Cluster 9: 559 signature genes

-------------- end ------------------

--------------------
    k  silhouette
0   2       0.578
1   3       0.532
2   4       0.493
3   5       0.493
4   6       0.434
5   7       0.438
6   8       0.454
7   9       0.454
8  10       0.461
9  11       0.438
--------------------

Clusters: 10
--------------------
Calc PCA ...
Calc best cluster ...
Calc PCA-UMAP ...
Find clusters' signature genes ...
Unique signature genes ...
Cluster 1: 4444 signature genes
Cluster 2: 2700 signature genes
Cluster 3: 3676 signature genes
Cluster 4: 4600 signature genes
Cluster 5: 4268 signature genes
Cluster 6: 2962 signature genes
Cluster 7: 512 signature genes
Cluster 8: 388 signature genes
Cluster 9: 5 signature genes
Cluster 10: 559 signature genes

-------------- end ------------------

--------------------
     k  silhouette
0    2       0.578
1    3       0.532
2    4       0.493
3    5       0.493
4    6       0.434
5    7       0.438
6    8       0.454
7    9       0.454
8   10       0.461
9   11       0.438
10  12       0.428
--------------------

### Clusters

In [12]:
n_clusters=5

min_clusters = 2; max_clusters = (n_clusters+2)

verbose=False
force=False

print(f"Clusters: {n_clusters}")
print("--------------------")

df_cluster, df_pca, df_umap = gdc.cluster_PCA_HCA_UMAP(df_combat, group=group, n_clusters=n_clusters, 
                                                n_components=n_components, min_clusters=min_clusters, max_clusters=max_clusters,
                                                n_umap_neighbors=n_umap_neighbors, min_umap_dist=min_umap_dist, umap_metric=umap_metric,
                                                method_hca=method_hca, hca_criterion=hca_criterion,
                                                LFC_cutoff=LFC_cutoff, FDR_cutoff=FDR_cutoff,
                                                force=force, verbose=verbose)
gdc.df_eval

Clusters: 5
--------------------

   k  silhouette
0  2       0.578
1  3       0.532
2  4       0.493
3  5       0.493
4  6       0.434
5  7       0.438

In [13]:
df_hca = gdc.df_hca
df_hca

     sample  cluster
0         1        1
1         2        5
2         3        1
3         4        5
4         5        1
..      ...      ...
552     553        4
553     554        4
554     555        4
555     556        3
556     557        3

[557 rows x 2 columns]

In [14]:
df_hca.cluster.min(), df_hca.cluster.max()

(1, 5)

### Are normal samples normal?

In [15]:
lista = gdc.df_metadata[gdc.df_metadata.condition == 'normal'].index.to_list()
mini = np.min(lista)
maxi = np.max(lista)

mini, maxi

(458, 557)

In [16]:
normal_culsters = np.unique(df_hca[df_hca['sample'] >= mini].cluster)
normal_culsters

array([3, 4])

In [17]:
for the_cluster in normal_culsters:
    lista = gdc.df_hca[gdc.df_hca.cluster == the_cluster]['sample'].to_list()
    n = len(lista)
    print(f"Cluster {the_cluster}: {n} samples", end='')
    not_normal = [str(x) for x in lista if x < mini]
    if not_normal:
        s_lista = ";".join(not_normal)
        print(f", having {len(not_normal)} not normal samples:", s_lista)
    else:
        print(f": all normal samples")

Cluster 3: 80 samples: all normal samples
Cluster 4: 208 samples, having 188 not normal samples: 10;103;105;106;107;108;109;110;113;114;115;116;117;118;119;121;122;123;124;125;126;128;129;130;132;133;134;135;136;137;138;139;140;141;143;145;147;148;149;150;152;153;154;156;157;158;159;162;164;165;166;167;169;170;171;172;173;174;176;177;178;179;180;181;182;183;184;185;186;187;188;189;190;191;192;193;194;195;196;197;198;199;201;202;203;204;205;207;208;209;210;211;212;213;224;316;318;319;320;321;322;323;326;327;328;329;330;331;332;334;335;336;337;338;339;341;342;343;345;346;347;348;349;350;351;352;353;354;356;358;360;361;362;363;365;366;367;369;370;371;372;375;377;378;379;380;382;383;384;385;386;387;389;390;391;392;393;394;395;396;397;398;399;400;401;402;403;404;405;406;407;408;409;410;411;413;414;415;416;417;419;420;421;422;423;424;425;426

In [29]:
force=False
verbose=True

nclu=1

cols = df_hca[df_hca.cluster == nclu]['sample']
gene_cols = ["geneid", "symbol", "biotype"]
all_cols = gene_cols + list(cols)

dfn_combat_tum = df_combat[all_cols].copy()
dfn_combat_tum

,geneid,symbol,biotype,1,3,5,14,16,17,20,...,292,295,299,303,306,308,309,312,325,373
0,ENSG00000270641,TSIX,lncRNA,13.955,13.898,13.710,13.709,13.517,13.716,13.655,...,13.800,13.748,14.288,12.180,14.237,13.885,13.904,14.315,12.685,11.616
1,ENSG00000262619,LINC00621,lncRNA,10.371,12.476,14.294,10.253,8.013,12.856,9.814,...,11.641,12.799,10.127,13.344,10.181,9.938,13.521,12.297,10.204,1.598
2,ENSG00000281383,FP671120.7,lncRNA,3.266,10.497,11.041,11.796,10.530,8.831,10.768,...,10.104,10.189,10.801,10.106,10.897,3.235,9.594,8.841,11.232,10.155
3,ENSG00000189223,PAX8-AS1,lncRNA,13.304,13.272,12.738,12.123,12.681,13.531,11.430,...,11.190,12.278,12.888,12.110,12.734,13.094,14.089,12.858,13.996,3.084
4,ENSG00000256462,AL732437.1,lncRNA,-0.073,1.575,0.465,-0.073,4.597,-0.073,6.480,...,-0.108,-0.108,1.749,-0.108,2.319,-0.108,-0.108,4.047,-0.108,1.980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ENSG00000153132,CLGN,protein_coding,3.464,2.736,2.405,2.660,3.124,4.032,3.066,...,3.398,2.906,4.107,0.820,0.877,4.279,0.068,2.558,3.113,0.753
9996,ENSG00000246203,AL353807.3,unprocessed_pseudogene,3.972,4.236,4.073,4.151,3.343,3.803,3.020,...,3.189,3.802,3.485,2.266,3.818,3.324,2.806,4.510,4.282,3.871
9997,ENSG00000271964,AC090948.1,lncRNA,4.139,3.002,3.666,3.556,2.077,5.146,5.022,...,2.292,3.321,3.741,4.627,4.100,4.952,2.915,2.790,3.829,4.339
9998,ENSG00000047410,TPR,protein_coding,4.272,5.000,6.758,6.532,6.117,4.831,6.774,...,5.260,5.211,5.622,5.047,5.444,6.003,5.565,4.571,6.150,4.598
9999,ENSG00000145246,ATP10D,protein_coding,1.831,3.819,1.411,2.345,2.599,1.336,3.871,...,0.877,2.277,4.429,2.512,2.963,2.715,2.899,3.004,2.914,2.707

In [30]:
df_tumor = dfn_combat_tum
df_tumor.head(3)

,geneid,symbol,biotype,1,3,5,14,16,17,20,...,292,295,299,303,306,308,309,312,325,373
0,ENSG00000270641,TSIX,lncRNA,13.955,13.898,13.710,13.709,13.517,13.716,13.655,...,13.800,13.748,14.288,12.180,14.237,13.885,13.904,14.315,12.685,11.616
1,ENSG00000262619,LINC00621,lncRNA,10.371,12.476,14.294,10.253,8.013,12.856,9.814,...,11.641,12.799,10.127,13.344,10.181,9.938,13.521,12.297,10.204,1.598
2,ENSG00000281383,FP671120.7,lncRNA,3.266,10.497,11.041,11.796,10.530,8.831,10.768,...,10.104,10.189,10.801,10.106,10.897,3.235,9.594,8.841,11.232,10.155

In [31]:
df_metadata = gdc.df_metadata

cols_normal = df_metadata[df_metadata.condition == 'normal'].index.to_list()

In [32]:

df_normal = df_combat[["geneid", "symbol", "biotype"] + cols_normal]
df_normal.head(3)

,geneid,symbol,biotype,458,459,460,461,462,463,464,...,548,549,550,551,552,553,554,555,556,557
0,ENSG00000270641,TSIX,lncRNA,14.130,5.194,3.204,2.363,4.244,14.158,2.580,...,2.868,3.028,5.113,2.322,3.620,4.659,13.198,4.548,3.652,14.046
1,ENSG00000262619,LINC00621,lncRNA,2.701,3.626,2.377,1.667,2.043,7.048,0.543,...,1.102,1.409,2.019,0.461,0.589,2.182,2.404,4.046,3.690,2.335
2,ENSG00000281383,FP671120.7,lncRNA,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,...,-0.146,-0.146,-0.146,-0.146,-0.146,-0.146,1.137,-0.146,0.574,-0.146

In [33]:
df_exp, df_annotation = gdc.prepare_expression_matrix(
                df_tumor=df_tumor,
                df_normal=df_normal,
            )

df_exp.head(3)

,1,3,5,14,16,17,20,22,23,25,...,548,549,550,551,552,553,554,555,556,557
geneid,,,,,,,,,,,,,,,,,,,,,
ENSG00000270641,13.955,13.898,13.710,13.709,13.517,13.716,13.655,13.642,14.054,13.462,...,2.868,3.028,5.113,2.322,3.620,4.659,13.198,4.548,3.652,14.046
ENSG00000262619,10.371,12.476,14.294,10.253,8.013,12.856,9.814,11.937,3.751,12.437,...,1.102,1.409,2.019,0.461,0.589,2.182,2.404,4.046,3.690,2.335
ENSG00000281383,3.266,10.497,11.041,11.796,10.530,8.831,10.768,8.681,8.584,10.443,...,-0.146,-0.146,-0.146,-0.146,-0.146,-0.146,1.137,-0.146,0.574,-0.146

In [34]:
df_annotation.head(3)

            geneid      symbol biotype
0  ENSG00000270641        TSIX  lncRNA
1  ENSG00000262619   LINC00621  lncRNA
2  ENSG00000281383  FP671120.7  lncRNA

In [35]:
from inmoose.limma import lmFit, eBayes, topTable, makeContrasts, contrasts_fit

tumor_samples = [
    col for col in df_tumor.columns
    if col not in gdc.ANNOT_COLS
]

normal_samples = [
    col for col in df_normal.columns
    if col not in gdc.ANNOT_COLS
]

metadata = pd.DataFrame(
    {
        "group": (
            ["Tumor"] * len(tumor_samples) + 
            ["Normal"] * len(normal_samples)
        )
    },
    index=tumor_samples + normal_samples,
)

metadata = metadata.loc[df_exp.columns].copy()

# Intercept + binary tumor coefficient
# Normal is the reference condition
design = pd.DataFrame(
    {
        "Intercept": 1.0,
        "Tumor_vs_Normal": (
            metadata["group"].eq("Tumor").astype(float)
        ),
    },
    index=metadata.index,
)

assert df_exp.columns.equals(design.index)

fit = lmFit(df_exp, design)

design

     Intercept  Tumor_vs_Normal
1          1.0              1.0
3          1.0              1.0
5          1.0              1.0
14         1.0              1.0
16         1.0              1.0
..         ...              ...
553        1.0              0.0
554        1.0              0.0
555        1.0              0.0
556        1.0              0.0
557        1.0              0.0

[176 rows x 2 columns]

In [36]:
# InMoose supports trend=True for logCPM-like data and calculates moderated statistics through empirical-Bayes variance shrinkage.
coefficient_names = ["Intercept", "Tumor_vs_Normal"]

fit.coefficients.columns = coefficient_names
fit.stdev_unscaled.columns = coefficient_names


fit_bayes = eBayes(
    fit,
    trend=True,
    robust=False,
)

In [37]:
print(fit.coefficients.columns)
print(fit_bayes.coefficients.columns)

Index(['Intercept', 'Tumor_vs_Normal'], dtype='object')
Index(['Intercept', 'Tumor_vs_Normal'], dtype='object')

In [38]:
print("coefficients:", fit_bayes.coefficients.columns.tolist())
print("stdev_unscaled:", fit_bayes.stdev_unscaled.columns.tolist())
print("t:", fit_bayes.t.columns.tolist())
print("p_value:", fit_bayes.p_value.columns.tolist())
print("lods:", fit_bayes.lods.columns.tolist())

coefficients: ['Intercept', 'Tumor_vs_Normal']
stdev_unscaled: ['Intercept', 'Tumor_vs_Normal']
t: ['Intercept', 'Tumor_vs_Normal']
p_value: ['Intercept', 'Tumor_vs_Normal']
lods: ['Intercept', 'Tumor_vs_Normal']

In [39]:
gene_annotations = df_annotation.copy()

gene_annotations.index = gene_annotations["geneid"].astype(str)
df_exp.index = df_exp.index.astype(str)

gene_annotations = gene_annotations.loc[df_exp.index]
gene_annotations

                          geneid      symbol                 biotype
geneid
ENSG00000270641  ENSG00000270641        TSIX                  lncRNA
ENSG00000262619  ENSG00000262619   LINC00621                  lncRNA
ENSG00000281383  ENSG00000281383  FP671120.7                  lncRNA
ENSG00000189223  ENSG00000189223    PAX8-AS1                  lncRNA
ENSG00000256462  ENSG00000256462  AL732437.1                  lncRNA
...                          ...         ...                     ...
ENSG00000153132  ENSG00000153132        CLGN          protein_coding
ENSG00000246203  ENSG00000246203  AL353807.3  unprocessed_pseudogene
ENSG00000271964  ENSG00000271964  AC090948.1                  lncRNA
ENSG00000047410  ENSG00000047410         TPR          protein_coding
ENSG00000145246  ENSG00000145246      ATP10D          protein_coding

[10000 rows x 3 columns]

In [40]:
print(df_exp.index.equals(fit_bayes.coefficients.index))
print(df_exp.index.equals(fit_bayes.t.index))
print(df_exp.index.equals(gene_annotations.index))

True
True
True

In [41]:
assert len(df_annotation) == len(df_exp)

In [42]:
results = topTable(
    fit_bayes,
    coef="Tumor_vs_Normal",
    number=df_exp.shape[0],
    # genelist=gene_annotations,
    adjust_method="fdr_bh",
    sort_by="P",
)

df_lfc_ori = pd.DataFrame(
    data=results.to_numpy(copy=True),
    index=results.index.copy(),
    columns=results.columns.copy(),
)

df_lfc_ori = df_lfc_ori.merge(
    df_annotation,
    on="geneid",
    how="left",
    validate="one_to_one",
)

cols = ['geneid', 'lfc', 'lfcSE', 'ave_expr', 'stat', 'pvalue', 'fdr', 'B', 'symbol', 'biotype']
df_lfc_ori.columns = cols

cols = ['geneid', 'symbol', 'biotype', 'lfc', 'abs_lfc', 'lfcSE', 'pvalue', 'fdr', 'ave_expr', 'stat', 'B']
df_lfc_ori['abs_lfc'] = df_lfc_ori['lfc'].abs()
df_lfc_ori = df_lfc_ori[cols]

df_lfc_ori

,geneid,symbol,biotype,lfc,abs_lfc,lfcSE,pvalue,fdr,ave_expr,stat,B
0,ENSG00000198695,MT-ND6,protein_coding,6.932e+00,6.932e+00,0.152,4.367e-133,4.367e-129,11.355,7.090e+01,292.972
1,ENSG00000249119,MTND6P4,processed_pseudogene,8.652e+00,8.652e+00,0.152,4.608e-129,2.304e-125,4.419,6.720e+01,283.925
2,ENSG00000117242,PINK1-AS,lncRNA,-3.521e+00,3.521e+00,0.152,1.368e-124,4.559e-121,8.770,-6.330e+01,273.839
3,ENSG00000233144,AL512656.1,lncRNA,-3.271e+00,3.271e+00,0.152,1.578e-120,3.945e-117,7.778,-5.993e+01,264.654
4,ENSG00000215375,MYL5,protein_coding,-3.448e+00,3.448e+00,0.152,3.781e-118,7.562e-115,8.353,-5.804e+01,259.264
...,...,...,...,...,...,...,...,...,...,...,...
9995,ENSG00000164107,HAND2,protein_coding,1.781e-03,1.781e-03,0.152,9.947e-01,9.951e-01,2.175,6.654e-03,-8.016
9996,ENSG00000087088,BAX,protein_coding,-2.942e-04,2.942e-04,0.152,9.981e-01,9.983e-01,2.912,-2.387e-03,-8.016
9997,ENSG00000259528,AC068397.1,lncRNA,2.853e-04,2.853e-04,0.152,9.981e-01,9.983e-01,4.256,2.329e-03,-8.016
9998,ENSG00000178952,TUFM,protein_coding,1.705e-04,1.705e-04,0.152,9.989e-01,9.990e-01,3.518,1.430e-03,-8.016
9999,ENSG00000239508,PLCH1-AS1,lncRNA,-1.129e-04,1.129e-04,0.152,9.996e-01,9.996e-01,4.288,-4.784e-04,-8.016

In [45]:
df_degs = df_lfc_ori[ (df_lfc_ori.abs_lfc >= 1.0) & (df_lfc_ori.fdr < 0.05) ]
print(len(df_degs))

df_degs.tail(3)

6350

,geneid,symbol,biotype,lfc,abs_lfc,lfcSE,pvalue,fdr,ave_expr,stat,B
8520,ENSG00000256462,AL732437.1,lncRNA,-1.490,1.490,0.152,0.005,0.006,1.859,-2.812,-4.130
8634,ENSG00000247199,AC011346.1,lncRNA,-1.088,1.088,0.152,0.012,0.013,4.484,-2.551,-4.806
8674,ENSG00000236915,CLCA4-AS1,lncRNA,-1.137,1.137,0.152,0.013,0.015,1.646,-2.498,-4.936

In [48]:
np.unique(df_degs.biotype)

array(['IG_C_gene', 'IG_C_pseudogene', 'IG_V_pseudogene', 'Mt_rRNA',
       'Mt_tRNA', 'TEC', 'TR_V_gene', 'lncRNA', 'miRNA', 'misc_RNA',
       'polymorphic_pseudogene', 'processed_pseudogene', 'protein_coding',
       'rRNA_pseudogene', 'scaRNA', 'snRNA', 'snoRNA',
       'transcribed_processed_pseudogene',
       'transcribed_unitary_pseudogene',
       'transcribed_unprocessed_pseudogene', 'unitary_pseudogene',
       'unprocessed_pseudogene'], dtype=object)

In [50]:
remove_list = ['Mt_rRNA', 'Mt_tRNA', 'TEC', 'TR_V_gene', 'lncRNA', 'misc_RNA',
       'rRNA_pseudogene', 'scaRNA', 'snRNA', 'snoRNA',]

df_degs_biotype = df_lfc_ori[ (df_lfc_ori.abs_lfc >= 1.0) & (df_lfc_ori.fdr < 0.05)  & (~df_lfc_ori.biotype.isin(remove_list)) ]
print(len(df_degs_biotype))

df_degs_biotype.tail(3)

4082

,geneid,symbol,biotype,lfc,abs_lfc,lfcSE,pvalue,fdr,ave_expr,stat,B
8121,ENSG00000237016,AC013410.1,processed_pseudogene,1.164,1.164,0.152,4.295e-04,5.289e-04,2.200,3.588,-1.771
8134,ENSG00000129151,BBOX1,protein_coding,1.200,1.200,0.152,4.508e-04,5.541e-04,2.847,3.575,-1.817
8220,ENSG00000135249,RINT1,protein_coding,1.117,1.117,0.152,8.531e-04,1.038e-03,4.528,3.392,-2.414

In [ ]:
from libs.Basic import write_txt

write_txt("\n".join(df_degs_biotype.symbol[:2000]), f"degs_cluster_{nclu}_biotypes.txt", gdc.root_mprog_lfc)

True

In [ ]:
df_lfc_ori.columns

In [ ]:
method='deseq2'
force=True
verbose=True

df_lfc, df_lfc_ori, degs_txt, msg = gdc.calc_degs(
                                        prog_id = PROG_ID, 
                                        psi_id = PSI_ID,
                                        ncluster = nclu,
                                        df_tumor = dfn_combat_tum,
                                        df_normal = dfn_combat_norm, 
                                        df_gtex_ctrl = pd.DataFrame(),
                                        root_lfc= gdc.root_mprog_lfc,
                                        root_src = gdc.root_src,
                                        run_conda = True,
                                        lfc_cutoff = 1.0,
                                        fdr_cutoff = 0.05,
                                        method = method,
                                        force = force,
                                        verbose = verbose,
                                        )

In [ ]:
df_lfc