In [1]:
from platform import python_version
print(python_version())

3.11.14

In [2]:
import os, sys, yaml
from pathlib import Path
from dotenv import load_dotenv

import numpy as npmtd
import pandas as pd
pd.set_option('display.width', 100)
pd.set_option('max_colwidth', 80)
pd.set_option("display.precision", 3)

import seaborn as sns
sns.set_context("notebook", font_scale=1.4)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
%matplotlib inline

import json
import requests
import pandas as pd

sys.path.insert(1, '../src/')

ROOT0 = Path("/home/flavio/uv/perturb_agent/")
ROOT_SRC = ROOT0 / "src"

if str(ROOT_SRC) not in sys.path:
    sys.path.append(str(ROOT_SRC))

print("ROOT0:", ROOT0)
print("ROOT_SRC added:", ROOT_SRC)

from libs.Basic import *
from libs.MTD_lib import MTD
from libs.GDC_lib import GDC
from libs.calc_degs_lib import CALC_DEGS
# from libs.dashcyto_lib import DASH_CYTO
from libs.config_lib import Config

from IPython.display import display, HTML
# display(HTML("<style>.container { width:100% !important; }</style>"))
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

with open('../params.yml', 'r') as file:
    dic_yml = yaml.safe_load(file)

# print(dic_yml)

ROOT0: /home/flavio/uv/perturb_agent
ROOT_SRC added: /home/flavio/uv/perturb_agent/src

/home/flavio/uv/perturb_agent/.venv/lib/python3.11/site-packages/Bio/__init__.py:138: BiopythonWarning: You may be importing Biopython from inside the source tree. This is bad practice and might lead to downstream issues. In particular, you might encounter ImportErrors due to missing compiled C extensions. We recommend that you try running your code from outside the source tree. If you are outside the source tree then you have a pyproject.toml file in an unexpected directory: /home/flavio/uv/perturb_agent/.venv/lib/python3.11/site-packages
  warnings.warn(
/home/flavio/uv/perturb_agent/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
email = os.getenv('email')

i_project=0

project_list = dic_yml['project_list']
n = len(project_list)
project = project_list[i_project]

s_project_list = dic_yml['s_project_list']
s_project = s_project_list[i_project]
assert n==len(project_list), f"Error project_list: there are {n} projects"

PROG_ID = 'TCGA'
PSI_ID = 'TCGA-BRCA'
PSI_ID = 'TCGA-ACC'
PSI_ID = 'TCGA-CESC'
PSI_ID = 'TCGA-PAAD'

ROOT0_DATA = ROOT0 / "data"
root_colab = ROOT0_DATA / 'colab'
root_project = ROOT0_DATA / PROG_ID

disease = PSI_ID

root_project = create_dir(ROOT0_DATA, s_project)
root_disease = create_dir(root_project, PSI_ID)

CONTEXT_DISESE = 'xxxx'
context_disease = CONTEXT_DISESE

gene_protein = dic_yml['gene_protein']
s_omics = dic_yml['s_omics']

has_age = dic_yml['has_age']
has_gender = dic_yml['has_gender']

exp_normalization = dic_yml['exp_normalization']
normalization = 'quantile_norm' if exp_normalization == True else 'not_normalized'

LFC_cut_inf = dic_yml['LFC_cut_inf']
s_pathw_enrichm_method = dic_yml['s_pathw_enrichm_method']
ptw_min_num_of_degs_cut = dic_yml['ptw_min_num_of_degs_cut']

tolerance_pPMI = dic_yml['tolerance_pPMI']
type_sat_ptw_index = dic_yml['type_sat_ptw_index']
saturation_lfc_param = dic_yml['saturation_lfc_param']

pval_pathway_cutoff = dic_yml['pval_pathway_cutoff']
fdr_pathway_cutoff = dic_yml['fdr_pathway_cutoff']
num_of_genes_cutoff = dic_yml['num_of_genes_cutoff']
enr_db_list = dic_yml['enr_db_list']


case_list = dic_yml['case_list']
dic_case_list = dic_yml['dic_case_list']

std_filename      = dic_yml['std_filename']
std_filename_list = dic_yml['std_filename_list']

min_lfc_modulation = dic_yml['min_lfc_modulation']
num_of_genes_list  = dic_yml['num_of_genes_list']
pPMI_normalized  = dic_yml['pPMI_normalized']

#--- max len for formatting purposes
s_len_case  = dic_yml['s_len_case']

n_sentences = dic_yml['n_sentences']
run_list = dic_yml['run_list']
chosen_model_list = dic_yml['chosen_model_list']
i_dfp_list = dic_yml['i_dfp_list']
chosen_model_sampling = dic_yml['chosen_model_sampling']

fdr_ptw_cutoff_list = np.arange(0.05, 0.80, 0.05)
lfc_list = np.round(np.arange(1.0, -0.01, -.025), 3)
fdr_list = np.arange(0.05, 0.76, .01)

cfg = Config(root0=ROOT0, root_disease=root_disease, disease=disease, case_list=case_list)
case = case_list[0]

n_genes_annot_ptw, n_degs, n_degs_in_ptw, n_degs_not_in_ptw, degs_in_all_ratio = -1,-1,-1,-1,-1

LFC_cut, lfc_FDR_cut, n_degs, n_degs_up, n_degs_dw = cfg.get_best_lfc_cutoff(case, 'not_normalized')

print(f"project '{project}', s_project '{s_project}'")
print(f"G/P LFC cutoffs: lfc={LFC_cut:.3f}; fdr={lfc_FDR_cut:.3f} - LFC_cut_inf={LFC_cut_inf:.3f}")
print(f"Pathway cutoffs: pval={pval_pathway_cutoff:.3f}; fdr={fdr_pathway_cutoff:.3f}; num of genes={num_of_genes_cutoff}")

Best parameter file for LFC does not exist /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD/config/all_lfc_cutoffs_TCGA-PAAD.tsv
project 'TCGA', s_project 'TCGA'
G/P LFC cutoffs: lfc=1.000; fdr=0.050 - LFC_cut_inf=0.400
Pathway cutoffs: pval=0.050; fdr=0.050; num of genes=3

In [4]:
mtd = MTD(disease=disease, gene_protein=gene_protein, s_omics=s_omics, project=project, s_project=s_project, 
          root0=ROOT0, root0_data=ROOT0_DATA, prog_id=PROG_ID, psi_id=PSI_ID,
          case_list=case_list, dic_case_list=dic_case_list, has_age=has_age, has_gender=has_gender, exp_normalization=exp_normalization,
          std_filename=std_filename, std_filename_list=std_filename_list,
          geneset_num=0, ptw_min_num_of_degs_cut=ptw_min_num_of_degs_cut,
          tolerance_pPMI=tolerance_pPMI, s_pathw_enrichm_method=s_pathw_enrichm_method,
          LFC_cut_inf=LFC_cut_inf, fdr_ptw_cutoff_list=fdr_ptw_cutoff_list,
          num_of_genes_list=num_of_genes_list, lfc_list=lfc_list, fdr_list=fdr_list, 
          min_lfc_modulation=min_lfc_modulation, type_sat_ptw_index=type_sat_ptw_index,
          saturation_lfc_param=saturation_lfc_param, enr_db_list=enr_db_list, pPMI_normalized=pPMI_normalized)

print(">>> Roots", mtd.root0, mtd.root_disease)
case = case_list[0]
print(">>>", case)

mtd.cfg.set_default_best_lfc_cutoff(mtd.normalization, LFC_cut=1, lfc_FDR_cut=0.05)
ret, degs, degs_ensembl, dfdegs = mtd.open_case(case, prompt_verbose=False, verbose=False)
# print("\nEcho Parameters:")
# print(mtd.echo_parameters())

>>> Roots /home/flavio/uv/perturb_agent /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD
>>> Tumor

### GDC - no memory restriction to get all data available

In [5]:
gdc = GDC(root0=ROOT0, root0_data=ROOT0_DATA, memory_restriction=False)

### Get all programs

In [6]:
force=False
verbose=False

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)
prog_list.sort()

"; ".join(prog_list)

'ALCHEMIST; APOLLO; BEATAML1.0; CCDI; CCG; CDDP_EAGLE; CGCI; CMI; CPTAC; CTSP; EXCEPTIONAL_RESPONDERS; FM; HCMI; MATCH; MMRF; MP2PRT; NCICCR; OHSU; ORGANOID; RC; REBC; TARGET; TCGA; TRIO; VAREPOP; WCDT'

In [7]:
PROG_ID = 'TCGA'

df_psi = gdc.get_primary_sites(prog_id=PROG_ID, verbose=verbose)
print(len(df_psi))
df_psi.head(3)

33

,prog_id,gdc_project_id,disease_id,psi_id,primary_site,disease_context,cbioportal_study_id,mapping_status,recommended_mutation_source,notes,alternative_cbioportal_study_ids,review_notes
0,TCGA,TCGA-ACC,ACC,TCGA-ACC,Adrenal gland,Adrenocortical carcinoma,acc_tcga_pan_can_atlas_2018,formulaic_tcga_pan_can_atlas,GDC MAF first; cBioPortal only if mapping is validated,Validate with cBioPortal /api/studies before production.,NaN,NaN
1,TCGA,TCGA-BLCA,BLCA,TCGA-BLCA,Bladder,Bladder urothelial carcinoma,blca_tcga_pan_can_atlas_2018,formulaic_tcga_pan_can_atlas,GDC MAF first; cBioPortal only if mapping is validated,Validate with cBioPortal /api/studies before production.,NaN,NaN
2,TCGA,TCGA-BRCA,BRCA,TCGA-BRCA,Breast,Breast invasive carcinoma,brca_tcga_pan_can_atlas_2018,formulaic_tcga_pan_can_atlas,GDC MAF first; cBioPortal only if mapping is validated,Validate with cBioPortal /api/studies before production.,NaN,NaN

### Open primary cites from cbio

In [8]:
df_psi = gdc.open_primary_sites_cbio(verbose=True)

df_psi.columns

Table opened ((89, 12)) at '/home/flavio/uv/perturb_agent/data/gdc_to_cbioportal_study_mapping.tsv'

Index(['prog_id', 'gdc_project_id', 'disease_id', 'psi_id', 'primary_site', 'disease_context',
       'cbioportal_study_id', 'mapping_status', 'recommended_mutation_source', 'notes',
       'alternative_cbioportal_study_ids', 'review_notes'],
      dtype='object')

In [9]:
df_psi.head(3).T

,0,1,2
prog_id,TCGA,TCGA,TCGA
gdc_project_id,TCGA-ACC,TCGA-BLCA,TCGA-BRCA
disease_id,ACC,BLCA,BRCA
psi_id,TCGA-ACC,TCGA-BLCA,TCGA-BRCA
primary_site,Adrenal gland,Bladder,Breast
disease_context,Adrenocortical carcinoma,Bladder urothelial carcinoma,Breast invasive carcinoma
cbioportal_study_id,acc_tcga_pan_can_atlas_2018,blca_tcga_pan_can_atlas_2018,brca_tcga_pan_can_atlas_2018
mapping_status,formulaic_tcga_pan_can_atlas,formulaic_tcga_pan_can_atlas,formulaic_tcga_pan_can_atlas
recommended_mutation_source,GDC MAF first; cBioPortal only if mapping is validated,GDC MAF first; cBioPortal only if mapping is validated,GDC MAF first; cBioPortal only if mapping is validated
notes,Validate with cBioPortal /api/studies before production.,Validate with cBioPortal /api/studies before production.,Validate with cBioPortal /api/studies before production.
alternative_cbioportal_study_ids,NaN,NaN,NaN
review_notes,NaN,NaN,NaN

In [10]:
DISEASE_ID = 'ACC'
DISEASE_ID = 'PAAD'

df_psi = df_psi[ (df_psi.disease_id == DISEASE_ID) & (~pd.isnull(df_psi.primary_site)) & (~pd.isnull(df_psi.cbioportal_study_id)) ].copy()
dfa = df_psi.groupby(['prog_id', 'psi_id', 'disease_id', 'primary_site', 'gdc_project_id', 'cbioportal_study_id']).size().reset_index()

dfa[ ['prog_id', 'psi_id', 'disease_id', 'primary_site', 'gdc_project_id', 'cbioportal_study_id'] ]

  prog_id          psi_id disease_id primary_site gdc_project_id           cbioportal_study_id
0    CCLE       CCLE-PAAD       PAAD     Pancreas      CCLE-PAAD               ccle_broad_2019
1   CPTAC      CPTAC-PAAD       PAAD     Pancreas        CPTAC-3               paad_cptac_2021
2   CPTAC  CPTAC-PAAD_GDC       PAAD     Pancreas        CPTAC-3            pancreas_cptac_gdc
3    TCGA       TCGA-PAAD       PAAD     Pancreas      TCGA-PAAD  paad_tcga_pan_can_atlas_2018

In [28]:
prog_id = 'CCLE'  # DepMap 
psi_id = 'CCLE-BRCA'

prog_id = 'CPTAC'
psi_id = 'CPTAC-BRCA'

prog_id = 'TCGA'
psi_id = 'TCGA-ACC'
psi_id = 'TCGA-BRCA'
psi_id = 'TCGA-BLCA'


df_psi = gdc.get_primary_sites(prog_id=prog_id, verbose=verbose)
df_psi.head(2)

Table opened ((89, 12)) at '/home/flavio/uv/perturb_agent/data/gdc_to_cbioportal_study_mapping.tsv'

,prog_id,gdc_project_id,disease_id,psi_id,primary_site,disease_context,cbioportal_study_id,mapping_status,recommended_mutation_source,notes,alternative_cbioportal_study_ids,review_notes
0,TCGA,TCGA-ACC,ACC,TCGA-ACC,Adrenal gland,Adrenocortical carcinoma,acc_tcga_pan_can_atlas_2018,formulaic_tcga_pan_can_atlas,GDC MAF first; cBioPortal only if mapping is validated,Validate with cBioPortal /api/studies before production.,NaN,NaN
1,TCGA,TCGA-BLCA,BLCA,TCGA-BLCA,Bladder,Bladder urothelial carcinoma,blca_tcga_pan_can_atlas_2018,formulaic_tcga_pan_can_atlas,GDC MAF first; cBioPortal only if mapping is validated,Validate with cBioPortal /api/studies before production.,NaN,NaN

In [29]:

gdc.set_primary_site(psi_id)

True

In [30]:
gdc.gdc_project_id, gdc.primary_site

('TCGA-BLCA', 'Bladder')

In [24]:
force=False
verbose=True

df_cases, df_subt, df_clin_demo = gdc.get_cases_and_subtypes(batch_size=200, do_filter=True, force=force, verbose=verbose)

print(df_cases.shape)
print(df_cases.primary_site.unique())
df_cases.head(3)

.......

👉 Returned 1098 / Total paginated 1098
Table saved ((1098, 26)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/cases_for_TCGA-BRCA.tsv'
Table saved ((21, 6)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/subtype_for_TCGA-BRCA.tsv'
..........................
--------------- end ------------

HTTPError: 414 Client Error: Request-URI Too Long for url: https://api.gdc.cancer.gov/cases?filters=%7B%22op%22%3A+%22in%22%2C+%22content%22%3A+%7B%22field%22%3A+%22case_id%22%2C+%22value%22%3A+%5B%2200807dae-9f4a-4fd1-aac2-82eb11bf2afb%22%2C+%2200b11ca8-8540-4a3d-b602-ec754b00230b%22%2C+%2202bbb632-0f7f-439d-b8f0-c86a06237424%22%2C+%2202bf5203-f9cd-4c5a-97b4-e5584dc22325%22%2C+%2203c143e0-d8a1-4d60-a4a3-df0501fc6b6e%22%2C+%22048549cf-d0a5-4743-a0a1-2004f7cc2b08%22%2C+%2205af737d-89aa-49b6-97b2-28b8ac8bd2cf%22%2C+%22077506ea-8f11-405d-bb8e-3c9924fe54d0%22%2C+%2208306ede-e74b-4be9-b768-7fd98647b6ac%22%2C+%220930e97a-72ea-4bd5-b2f0-50c76af695f3%22%2C+%2209d6e904-7184-4788-8a19-04f8c46cb13f%22%2C+%220adf59c6-581a-475d-a2f4-40aa40060b5b%22%2C+%220b0f9938-ce1e-4814-8821-0132d137eb9e%22%2C+%220bf6e772-1aa1-4f54-9a50-c1414e2f22f3%22%2C+%220cf0d67c-2f7f-42a6-94f3-407d0ec46c88%22%2C+%220d03055c-186b-418a-b614-e2035757bc3b%22%2C+%220d146997-cfdc-4587-888c-e876fc455c80%22%2C+%2210c829ec-fd66-49c4-8afe-ad3ae567372c%22%2C+%22124b693c-77dc-4fa8-b703-54e8b5054a92%22%2C+%22125b0a9a-6cbe-4207-9178-e7ff03487e87%22%2C+%221402082d-25c9-4148-8a1e-f58450b706bb%22%2C+%2214267783-5624-4fe5-ba81-9d67f1017474%22%2C+%2215ff4b02-bb69-4d24-8a07-b82f428e428d%22%2C+%2216fc3677-0393-4ed1-ad3f-c8355f056369%22%2C+%22182c4bdf-2c58-4303-b034-459da86b9d90%22%2C+%2219015644-9c17-4ae7-a656-0fe8623c04ae%22%2C+%221a679332-30a3-4495-a2e5-39d299e14333%22%2C+%221b4cfad1-e353-4411-97b6-2b7b9309e95e%22%2C+%221b703058-e596-45bc-80fe-8b98d545c2e2%22%2C+%221be375fe-5ae5-4e75-a729-69f86a661d9a%22%2C+%221cc30842-4a5b-4f07-b36f-5b84ceaa5662%22%2C+%221d75e89d-4b01-443c-be54-749c7a667bf4%22%2C+%221f601832-eee3-48fb-acf5-80c4a454f26e%22%2C+%221f99e4d4-4e8b-4cc1-a129-227a2a82780e%22%2C+%2222eaba28-be67-4730-9846-860bc1fca29a%22%2C+%2223b7aaea-1119-4b10-aa1a-0ae255d2f2a6%22%2C+%2223f438bd-1dbb-4d46-972f-1e8e74ddbd37%22%2C+%222476dda9-da2a-4242-9642-b92b8b9b1c79%22%2C+%222481a671-760b-428c-968d-42e25fd42ac5%22%2C+%22271e8024-a008-4bf0-9f6e-177f60096b1b%22%2C+%2227b05b15-a44b-45ed-a6e3-e7d1ca488ea9%22%2C+%2227c1c094-690b-4973-8900-a797ad88f98c%22%2C+%2228911b97-42bf-4189-9961-522fc0aeebc6%22%2C+%222ab1b35b-9e56-475c-ac9b-15ed0a422683%22%2C+%222c6adb12-380d-4710-a7e6-93d5a0e53289%22%2C+%222cb8c866-9296-4c70-a3ea-f9a9b707895c%22%2C+%222cbeadff-a8a3-4787-9d4e-f6b74c3ab5d9%22%2C+%222d29a4ac-98e7-4663-9dd6-5681bc32ac2e%22%2C+%222dc1cec9-925a-417f-9e21-3c2143e711b4%22%2C+%222e243f0e-9d7d-4cb0-9678-70607f90430a%22%2C+%2231427699-e27a-4035-8925-6d8d6900d097%22%2C+%2232861b48-83f5-43a3-bb54-45215ad2c5d6%22%2C+%2234126cd5-cc38-4198-8582-c14fb5db7acb%22%2C+%2234d5a193-85e5-4399-8a9b-e92858eafdfe%22%2C+%2235ca5e2a-861a-4dd2-a4ce-d294cf080da3%22%2C+%2237242f5a-25ae-4b1f-9ce6-09ce1dc92539%22%2C+%2238a4e9bd-93e9-432d-a756-3b1055b823bd%22%2C+%2238dc3e09-0b0e-4a29-b318-cc0352013dae%22%2C+%2239cda4c9-e1c8-44c2-bab7-f5849c12f879%22%2C+%223b963d72-ba5c-467b-83c9-fbdb462510a3%22%2C+%223c275152-d04b-440c-9621-2fc05ea977b6%22%2C+%223ca67cd0-81da-4f68-a9fa-f1a8c013c28d%22%2C+%223d676bba-154b-4d22-ab59-d4d4da051b94%22%2C+%223dbc8d60-3a97-47b2-91d0-c18fb46b4365%22%2C+%223efa245d-177d-4ef9-94f7-f554c54e345e%22%2C+%223f56d67f-5a9c-4353-9408-e7f60eb6477b%22%2C+%223f834fa7-6d7b-4b85-98c0-5c55d55b6c95%22%2C+%224229e432-6ac5-49d2-b58a-e8713ddb79bd%22%2C+%224510295e-8aa7-4ef1-b2b7-91cc902f8200%22%2C+%22451e1a67-47e6-4738-99d7-fb7771ef61a3%22%2C+%22452672e8-b6d9-45b5-bb02-e88e03e2dd66%22%2C+%22491d5ebb-e9ab-4b17-acb8-630ff9fef0f2%22%2C+%2249a2fd48-744d-4d88-b9b4-8c778d4f48fd%22%2C+%2249dc3e68-6206-4f16-969f-a758cc7be8ed%22%2C+%224a831893-f4ca-4357-a756-b5e954e35dd7%22%2C+%224b0d295c-e185-4b52-9752-178e5bc1d47d%22%2C+%224cf0f639-7940-48b6-8ea1-2a3494097cdb%22%2C+%224d26dada-5eb7-4d4e-8eb8-f5465c5c3428%22%2C+%224e509f73-99c7-48eb-a3a4-d34e3bface33%22%2C+%224f321d41-3255-46a4-ae0d-1cf39699e624%22%2C+%2259be60a3-e0f6-4d63-b98c-574ef92428c4%22%2C+%2259d60247-e549-4326-a672-50b05c13a291%22%2C+%225a53ec47-e63f-44a2-8078-87659544fb04%22%2C+%225aca16ca-4516-4e27-8249-6914029a7ebf%22%2C+%225c9d8163-a68e-43ce-9cba-effb7405761e%22%2C+%225cd79093-1571-4f71-8136-0d84ccabdcac%22%2C+%225cdae21d-eee5-478f-932a-0f51fcf5f031%22%2C+%225e2cbc56-97f9-4b94-ade2-a3f739bcc7be%22%2C+%225e670fec-8992-44bf-8657-f7f9a272306b%22%2C+%225f4d16aa-9cc4-4edb-b714-394e2661439a%22%2C+%225fd37868-4762-4109-9dcf-6fdbab5b645d%22%2C+%22602083f0-18d9-48b6-a529-31e165c54b37%22%2C+%2261204cdf-3b1c-44a1-bda6-0fef1ac4a333%22%2C+%226397d7bc-9cb1-4a84-81ad-76954e0a8cee%22%2C+%2265cde5d5-1efc-4e30-b1bd-a93598794f2c%22%2C+%226623fc5e-00be-4476-967a-cbd55f676ea6%22%2C+%22670f5022-5066-48f1-8472-5670129a1e0f%22%2C+%2267c73260-a242-4bba-87c5-d2302556dff7%22%2C+%2267c8dc41-edcb-4563-96b3-3f93f9edcbe9%22%2C+%2267eef990-5ff4-45d1-843d-d22d7848f130%22%2C+%226951fe6a-d7d1-4f41-85af-76655b5d1f62%22%2C+%2269a68fbc-e43d-4652-85ee-693211bded47%22%2C+%226a186809-3422-41d0-83d2-867145830936%22%2C+%226af6d256-a753-46d2-b611-e4094ff265aa%22%2C+%226b4e0262-f589-4532-b578-9f2d76c19d90%22%2C+%226ddaee34-46eb-490c-bd13-f0ab963c4322%22%2C+%226e6408d6-6c48-4dfc-9f1c-28b7386e87b4%22%2C+%226e7d5ec6-a469-467c-b748-237353c23416%22%2C+%226f0fd68f-ed6a-4c9e-be02-c97ba4950f76%22%2C+%226f4c8d30-47fb-47df-9eb7-4e5881e3711e%22%2C+%226f6e7356-3521-4674-8eec-ad01340d4b8e%22%2C+%226f89509c-f802-482e-b4da-94553aa76fe9%22%2C+%2270fc011c-0f22-4026-9d72-87351126203a%22%2C+%227241b3d4-31ee-4fd2-a4a5-35a9d5f37d6a%22%2C+%22726c6892-0dce-4869-a7a7-cc44c26fe843%22%2C+%2272cd1b17-d349-4551-83f7-3062ce9db865%22%2C+%22738e1acc-1f0c-4a96-9c8a-222727ef5af8%22%2C+%227451af3c-acc0-4d79-8429-6b8be96911d8%22%2C+%227486a2b3-b09f-4e9c-9864-8b51b58d9fb3%22%2C+%2275f6e476-233a-409c-a3ef-0240be569813%22%2C+%2276099beb-0abe-4b56-8b4e-e4485e0402e6%22%2C+%2276ace6aa-0505-442c-978a-f889cf2d44bb%22%2C+%2276bd9bb9-9a8b-4a90-bb7c-eafe76472ee4%22%2C+%2277e25ae8-82ec-4dea-8e62-1176f27e47ba%22%2C+%2279126e88-9cf8-45ff-bf91-a98da3b304d7%22%2C+%227bcf6d42-eb8f-4aa2-825b-38671d4f9e3a%22%2C+%227e9c8d3c-790c-46ad-8f31-b557b7c26f69%22%2C+%2280419545-4e5d-4baf-8948-f84589b5ef3e%22%2C+%22807b62ed-d3f7-4211-83be-754386ff2c96%22%2C+%2281b70c58-4a12-448c-a594-2ade44f6a0ae%22%2C+%2281e7a3d3-be70-4834-8018-4d2cc077a4e6%22%2C+%2284b7ccf2-8ab3-4b21-96de-800d231bc072%22%2C+%228539e15f-ba40-4219-aaeb-08d0ab101311%22%2C+%228624354c-af25-423c-9c71-48a5dd821097%22%2C+%2286c6f993-327f-4525-9983-29c55625593a%22%2C+%2287b85935-a058-44ad-8fb6-8511130eaffe%22%2C+%2289c128b9-1c6b-4c04-a4af-7066772e783c%22%2C+%228cd1ba0b-ead9-4661-a796-6c9dbf1c42cd%22%2C+%228d5fe6e8-d2cc-481f-a6a1-9cb6e7982cde%22%2C+%228e11c5ec-c15a-48d4-85ac-b7b08a9ed827%22%2C+%228e159b50-8136-42d4-b9c7-d579a74e4931%22%2C+%228e54232d-d8bb-4612-8b0e-4feb076a60f9%22%2C+%228f34cb4c-5798-47a0-89a1-f0ee26a8ae93%22%2C+%2290ff48c3-b14b-4a8b-94a1-98c0bab0d27b%22%2C+%22910655da-2c12-4572-96b7-ded616e69b4b%22%2C+%2291da548b-5c64-49c3-a44a-1ef115f53311%22%2C+%229434687a-197c-4959-b6b8-9c05f1dd7f53%22%2C+%2294b03e1d-50ec-4680-bffd-7086d1536ff2%22%2C+%2295873e61-afdb-496c-9f77-3f9beb008cda%22%2C+%22959ff069-8a49-4c9b-85c2-5291cac0acff%22%2C+%2295cef916-5545-455b-920c-773a54fc7676%22%2C+%229646160a-f1f9-437b-8c7d-efb0b57bfb97%22%2C+%2296e1fc6d-693f-4f4f-b5f7-8d6e1c6c43f8%22%2C+%2296f02be7-f2df-483c-8968-a5bd2d887206%22%2C+%2297862b8e-9f76-4b19-a865-156a9c00fb1e%22%2C+%229857be0c-aeca-4a43-90b1-0535bd08e086%22%2C+%22994ca1f5-ad10-44ec-aa21-71fc2940653b%22%2C+%22995fdab7-7284-4d33-befa-ec22aa7c6479%22%2C+%229964f447-92ad-4d1e-af20-11cf84fab7b0%22%2C+%229c55032f-4db7-4026-ae83-8d060dd8e3fe%22%2C+%229c895825-d6f6-4d14-a662-23212200f6e5%22%2C+%229d8702e1-1a36-4bca-85ab-5f11d58d7953%22%2C+%229da462b0-93c2-4305-89f6-7199a30399a7%22%2C+%229ddc014d-9a8b-407b-845f-452a73f08e5e%22%2C+%229e3de467-fb0d-4021-89f8-b34968a7c7bc%22%2C+%22a076f135-be82-40fa-8516-285ed355c965%22%2C+%22a20fa2c4-a502-47e3-bfaa-2ec4cce3a859%22%2C+%22a2434f47-2168-47d0-9bbb-981071597843%22%2C+%22a2934508-3daf-49e2-b14f-ed9b7693f96f%22%2C+%22a2efe7e1-aca3-440f-825f-ed621edca69f%22%2C+%22a381275f-8858-4793-a8a2-0ca9db7274c8%22%2C+%22a412b374-4d25-491f-b76f-ddaa989acf59%22%2C+%22a45d296e-efc0-479e-b2f6-bad834668cdf%22%2C+%22a482fc4c-ff1d-46a0-a968-7df06422cc4b%22%2C+%22a53dd490-e0ba-419a-90c6-b905e241a8e5%22%2C+%22a5b44d66-c162-46b5-9df2-86305f0385c5%22%2C+%22a6502f17-6bee-4d5a-8520-06364593d39c%22%2C+%22a6e5f869-1182-4f81-b4bb-cf55261c8f3f%22%2C+%22a721dac6-0126-476c-b2d4-2dbf7406454b%22%2C+%22a8b1f6e7-2bcf-460d-b1c6-1792a9801119%22%2C+%22a8f5c479-8685-4e2d-bb60-63f1cc651083%22%2C+%22a947a945-4721-45cc-bc45-13b8ea41c10e%22%2C+%22aa30ac3d-4216-45dd-a314-1ae192fafcb2%22%2C+%22aaea5f9c-b35b-47f8-93cb-bdc7b81844ff%22%2C+%22ad0fa961-c085-4f38-b3db-5fc0cbf6b64f%22%2C+%22ad6d26ab-6568-40db-bfb0-394d40e801cf%22%2C+%22af5453a9-cf1f-40de-aec4-0e0710908fb7%22%2C+%22af577366-0258-49e7-b6af-e70056c081a4%22%2C+%22b0700958-5f90-4546-b35f-635cd506889b%22%2C+%22b09643c2-ded5-4346-b3c5-90a48f88a02e%22%2C+%22b0f8d698-a30e-4d8d-b0a2-a5a01fac8406%22%2C+%22b205c89f-af62-4186-acad-ed23d243fa98%22%2C+%22b304302a-f2b9-4cd7-ab14-c21edf7778ea%22%2C+%22b35fbe19-0e6d-427e-b9be-ee3527b5fca6%22%2C+%22b63391a0-73f8-4544-9e94-f6529245ca2a%22%2C+%22b6b1dc9a-91f4-4b0a-afd5-62c9a90c0d5e%22%2C+%22b804f7ae-da8f-4414-be11-f880f1859160%22%2C+%22b956df1b-bc77-4bdb-a5bd-5dda7b4c8da7%22%2C+%22ba80db4e-d899-4da4-ae49-5263d98e1530%22%2C+%22bac4b268-c781-4408-96d8-43a48fec7418%22%5D%7D%7D&fields=case_id%2Csubmitter_id%2Cdiagnoses.age_at_diagnosis&format=JSON&size=200

In [15]:
gdc.df_clin_demo

,case_id,barcode_case,project_id,primary_site,disease_type,gender,age_at_diagnosis,race,ethnicity,vital_status,...,tumor_stage,ajcc_pathologic_stage,ajcc_pathologic_t,ajcc_pathologic_n,ajcc_pathologic_m,ajcc_clinical_stage,ajcc_clinical_t,ajcc_clinical_n,ajcc_clinical_m,classification_of_tumor
0,0304b12d-7640-4150-a581-2eea2b1f2ad5,TCGA-OR-A5LL,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,75.58,not reported,not reported,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,primary
1,0304b12d-7640-4150-a581-2eea2b1f2ad5,TCGA-OR-A5LL,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,75.58,not reported,not reported,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metastasis
2,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metastasis
3,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metastasis
4,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,recurrence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,fb504e55-1859-48ee-aec7-a3fcb082785e,TCGA-OR-A5LB,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,male,60.71,white,not hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,primary
162,fb54458d-c373-46c2-841e-82663e13efaa,TCGA-OR-A5JM,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,25.62,white,not reported,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,primary
163,fb54458d-c373-46c2-841e-82663e13efaa,TCGA-OR-A5JM,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,25.62,white,not reported,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metastasis
164,fc83ab27-929e-4ad4-ba18-abb0694f1e43,TCGA-OR-A5LJ,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,55.21,white,not hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,metastasis
165,fc83ab27-929e-4ad4-ba18-abb0694f1e43,TCGA-OR-A5LJ,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,55.21,white,not hispanic or latino,Dead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,primary

In [27]:
df_clin_demo = gdc.get_gdc_clin_demo_data(df_cases.case_id, force=True, batch_size=50, verbose=True)
df_clin_demo

.........
--------------- end ------------
Batch 1: 90 requested, 90 returned
Table saved ((166, 29)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/clinical_and_demographics_for_TCGA-BRCA.tsv'

,case_id,barcode_case,project_id,primary_site,disease_type,gender,age_at_diagnosis,race,ethnicity,vital_status,...,tumor_stage,ajcc_pathologic_stage,ajcc_pathologic_t,ajcc_pathologic_n,ajcc_pathologic_m,ajcc_clinical_stage,ajcc_clinical_t,ajcc_clinical_n,ajcc_clinical_m,classification_of_tumor
0,0304b12d-7640-4150-a581-2eea2b1f2ad5,TCGA-OR-A5LL,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,75.58,not reported,not reported,Dead,...,None,None,None,None,None,None,None,None,None,primary
1,0304b12d-7640-4150-a581-2eea2b1f2ad5,TCGA-OR-A5LL,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,75.58,not reported,not reported,Dead,...,None,None,None,None,None,None,None,None,None,metastasis
2,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,metastasis
3,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,metastasis
4,075dbfd0-9cf4-4877-884f-ae858902c79e,TCGA-OR-A5J7,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,31.32,white,hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,recurrence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,fb504e55-1859-48ee-aec7-a3fcb082785e,TCGA-OR-A5LB,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,male,60.71,white,not hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,primary
162,fb54458d-c373-46c2-841e-82663e13efaa,TCGA-OR-A5JM,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,25.62,white,not reported,Dead,...,None,None,None,None,None,None,None,None,None,primary
163,fb54458d-c373-46c2-841e-82663e13efaa,TCGA-OR-A5JM,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,25.62,white,not reported,Dead,...,None,None,None,None,None,None,None,None,None,metastasis
164,fc83ab27-929e-4ad4-ba18-abb0694f1e43,TCGA-OR-A5LJ,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,55.21,white,not hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,metastasis
165,fc83ab27-929e-4ad4-ba18-abb0694f1e43,TCGA-OR-A5LJ,TCGA-ACC,Adrenal gland,Adenomas and Adenocarcinomas,female,55.21,white,not hispanic or latino,Dead,...,None,None,None,None,None,None,None,None,None,primary

In [17]:
df_subt

,psi_id,subtype_global,tumor_class,subtype_tissue,stage,n
0,TCGA-ACC,Adrenal cortical carcinoma,adrenal_cortical_carcinoma,Adrenal cortical carcinoma,NaN,87
1,TCGA-ACC,Adrenal cortical carcinoma,adrenal_cortical_carcinoma,Adrenal cortical carcinoma,unknown,2
2,TCGA-ACC,Adrenal cortical carcinoma,sarcoma,Adrenal cortical carcinoma,NaN,1

In [18]:
for isubt, row in df_subt.iterrows():
    subtype_global = row.subtype_global
    tumor_class = row.tumor_class
    subtype_tissue = row.subtype_tissue

    df_samples = gdc.get_samples_for_subtypes(
        subtype_global=subtype_global,
        tumor_class=tumor_class,
        subtype_tissue=subtype_tissue,
        batch_size=200,
        force=False,
        verbose=verbose,
    )
    print(f"{isubt}) {gdc.s_case}")

    if df_samples.empty:
        print(f"No samples found for PSI_ID: {psi_id} subtype: {subtype_global} tumor_class: {tumor_class} subtype_tissue: {subtype_tissue}")
    else:
        print(f"There are {len(df_samples)} samples for PSI_ID: {psi_id} subtype: {subtype_global} tumor_class: {tumor_class} subtype_tissue: {subtype_tissue}")

Table opened ((92, 26)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/cases_for_TCGA-ACC.tsv'
Table opened ((166, 29)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/clinical_and_demographics_for_TCGA-ACC.tsv'
Table opened ((4481, 14)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/samples/samples_for_TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_adrenal-cortical-carcinoma_tissue_Adrenal_cortical_carcinoma.tsv'
0) TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_adrenal-cortical-carcinoma_tissue_Adrenal_cortical_carcinoma
There are 4481 samples for PSI_ID: TCGA-ACC subtype: Adrenal cortical carcinoma tumor_class: adrenal_cortical_carcinoma subtype_tissue: Adrenal cortical carcinoma
Table opened ((92, 26)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/cases_for_TCGA-ACC.tsv'
Table opened ((166, 29)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/clinical_and_demographics_for_TCGA-ACC.tsv'
Table opened ((4481, 14)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/samples/samples_for_TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_adrenal-cortical-carcinoma_tissue_Adrenal_cortical_carcinoma.tsv'
1) TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_adrenal-cortical-carcinoma_tissue_Adrenal_cortical_carcinoma
There are 4481 samples for PSI_ID: TCGA-ACC subtype: Adrenal cortical carcinoma tumor_class: adrenal_cortical_carcinoma subtype_tissue: Adrenal cortical carcinoma
Table opened ((92, 26)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/cases_for_TCGA-ACC.tsv'
Table opened ((166, 29)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/clinical_and_demographics_for_TCGA-ACC.tsv'
Table opened ((90, 14)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-ACC/samples/samples_for_TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_sarcoma_tissue_Adrenal_cortical_carcinoma.tsv'
2) TCGA-ACC_Adrenal_gland_subtype_Adrenal_cortical_carcinoma_tumor_sarcoma_tissue_Adrenal_cortical_carcinoma
There are 90 samples for PSI_ID: TCGA-ACC subtype: Adrenal cortical carcinoma tumor_class: sarcoma subtype_tissue: Adrenal cortical carcinoma