In [1]:
from platform import python_version
print(python_version())

3.11.14

In [2]:
import os, sys, yaml
from pathlib import Path
from dotenv import load_dotenv

import numpy as npmtd
import pandas as pd
pd.set_option('display.width', 100)
pd.set_option('max_colwidth', 80)
pd.set_option("display.precision", 3)

import seaborn as sns
sns.set_context("notebook", font_scale=1.4)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
%matplotlib inline

sys.path.insert(1, '../src/')

ROOT0 = Path("/home/flavio/uv/perturb_agent/")
ROOT_SRC = ROOT0 / "src"

if str(ROOT_SRC) not in sys.path:
    sys.path.append(str(ROOT_SRC))

print("ROOT0:", ROOT0)
print("ROOT_SRC added:", ROOT_SRC)

from libs.Basic import *
from libs.MTD_lib import MTD
from libs.GDC_lib import GDC
from libs.calc_degs_lib import CALC_DEGS
# from libs.dashcyto_lib import DASH_CYTO
from libs.config_lib import Config

from IPython.display import display, HTML
# display(HTML("<style>.container { width:100% !important; }</style>"))
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

with open('../params.yml', 'r') as file:
    dic_yml = yaml.safe_load(file)

# print(dic_yml)

ROOT0: /home/flavio/uv/perturb_agent
ROOT_SRC added: /home/flavio/uv/perturb_agent/src

In [3]:
email = os.getenv('email')

i_project=0

project_list = dic_yml['project_list']
n = len(project_list)
project = project_list[i_project]

s_project_list = dic_yml['s_project_list']
s_project = s_project_list[i_project]
assert n==len(project_list), f"Error project_list: there are {n} projects"

PROG_ID = 'TCGA'
PSI_ID = 'TCGA-BRCA'
PSI_ID = 'TCGA-ACC'
PSI_ID = 'TCGA-CESC'
PSI_ID = 'TCGA-PAAD'

ROOT0_DATA = ROOT0 / "data"
root_colab = ROOT0_DATA / 'colab'
root_project = ROOT0_DATA / PROG_ID

disease = PSI_ID

root_project = create_dir(ROOT0_DATA, s_project)
root_disease = create_dir(root_project, PSI_ID)

CONTEXT_DISESE = 'xxxx'
context_disease = CONTEXT_DISESE

gene_protein = dic_yml['gene_protein']
s_omics = dic_yml['s_omics']

has_age = dic_yml['has_age']
has_gender = dic_yml['has_gender']

exp_normalization = dic_yml['exp_normalization']
normalization = 'quantile_norm' if exp_normalization == True else 'not_normalized'

LFC_cut_inf = dic_yml['LFC_cut_inf']
s_pathw_enrichm_method = dic_yml['s_pathw_enrichm_method']
ptw_min_num_of_degs_cut = dic_yml['ptw_min_num_of_degs_cut']

tolerance_pPMI = dic_yml['tolerance_pPMI']
type_sat_ptw_index = dic_yml['type_sat_ptw_index']
saturation_lfc_param = dic_yml['saturation_lfc_param']

pval_pathway_cutoff = dic_yml['pval_pathway_cutoff']
fdr_pathway_cutoff = dic_yml['fdr_pathway_cutoff']
num_of_genes_cutoff = dic_yml['num_of_genes_cutoff']
enr_db_list = dic_yml['enr_db_list']


case_list = dic_yml['case_list']
dic_case_list = dic_yml['dic_case_list']

std_filename      = dic_yml['std_filename']
std_filename_list = dic_yml['std_filename_list']

min_lfc_modulation = dic_yml['min_lfc_modulation']
num_of_genes_list  = dic_yml['num_of_genes_list']
pPMI_normalized  = dic_yml['pPMI_normalized']

#--- max len for formatting purposes
s_len_case  = dic_yml['s_len_case']

n_sentences = dic_yml['n_sentences']
run_list = dic_yml['run_list']
chosen_model_list = dic_yml['chosen_model_list']
i_dfp_list = dic_yml['i_dfp_list']
chosen_model_sampling = dic_yml['chosen_model_sampling']

fdr_ptw_cutoff_list = np.arange(0.05, 0.80, 0.05)
lfc_list = np.round(np.arange(1.0, -0.01, -.025), 3)
fdr_list = np.arange(0.05, 0.76, .01)

cfg = Config(root0=ROOT0, root_disease=root_disease, disease=disease, case_list=case_list)
case = case_list[0]

n_genes_annot_ptw, n_degs, n_degs_in_ptw, n_degs_not_in_ptw, degs_in_all_ratio = -1,-1,-1,-1,-1

LFC_cut, lfc_FDR_cut, n_degs, n_degs_up, n_degs_dw = cfg.get_best_lfc_cutoff(case, 'not_normalized')

print(f"project '{project}', s_project '{s_project}'")
print(f"G/P LFC cutoffs: lfc={LFC_cut:.3f}; fdr={lfc_FDR_cut:.3f} - LFC_cut_inf={LFC_cut_inf:.3f}")
print(f"Pathway cutoffs: pval={pval_pathway_cutoff:.3f}; fdr={fdr_pathway_cutoff:.3f}; num of genes={num_of_genes_cutoff}")

Best parameter file for LFC does not exist /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD/config/all_lfc_cutoffs_TCGA-PAAD.tsv
project 'TCGA', s_project 'TCGA'
G/P LFC cutoffs: lfc=1.000; fdr=0.050 - LFC_cut_inf=0.400
Pathway cutoffs: pval=0.050; fdr=0.050; num of genes=3

In [4]:
mtd = MTD(disease=disease, gene_protein=gene_protein, s_omics=s_omics, project=project, s_project=s_project, 
          root0=ROOT0, root0_data=ROOT0_DATA, prog_id=PROG_ID, psi_id=PSI_ID,
          case_list=case_list, dic_case_list=dic_case_list, has_age=has_age, has_gender=has_gender, exp_normalization=exp_normalization,
          std_filename=std_filename, std_filename_list=std_filename_list,
          geneset_num=0, ptw_min_num_of_degs_cut=ptw_min_num_of_degs_cut,
          tolerance_pPMI=tolerance_pPMI, s_pathw_enrichm_method=s_pathw_enrichm_method,
          LFC_cut_inf=LFC_cut_inf, fdr_ptw_cutoff_list=fdr_ptw_cutoff_list,
          num_of_genes_list=num_of_genes_list, lfc_list=lfc_list, fdr_list=fdr_list, 
          min_lfc_modulation=min_lfc_modulation, type_sat_ptw_index=type_sat_ptw_index,
          saturation_lfc_param=saturation_lfc_param, enr_db_list=enr_db_list, pPMI_normalized=pPMI_normalized)

print(">>> Roots", mtd.root0, mtd.root_disease)
case = case_list[0]
print(">>>", case)

mtd.cfg.set_default_best_lfc_cutoff(mtd.normalization, LFC_cut=1, lfc_FDR_cut=0.05)
ret, degs, degs_ensembl, dfdegs = mtd.open_case(case, prompt_verbose=False, verbose=False)
# print("\nEcho Parameters:")
# print(mtd.echo_parameters())

>>> Roots /home/flavio/uv/perturb_agent /home/flavio/uv/perturb_agent/data/TCGA/TCGA-PAAD
>>> Tumor

### Get all programs

In [5]:
gdc = GDC(root0=ROOT0, root0_data=ROOT0_DATA, memory_restriction=False)

#--------- chose a disease --------------------
DISEASE_ID = 'ACC'
DISEASE_ID = 'PAAD'

In [6]:
verbose=False
force=False

method='deseq2'
imax_tumor=250
imax_normal=50

gdc = GDC(root0=ROOT0, root0_data=ROOT0_DATA, memory_restriction=False)

exclude_prog_list=['CCLE']

dfn_tumor, dfn_normal, df_gtex, df_ana = gdc.get_all_data_from_disease(disease_id=DISEASE_ID, 
                                                           imax_tumor=imax_tumor, imax_normal=imax_normal,
                                                           exclude_prog_list=exclude_prog_list,
                                                           force=force, verbose=verbose)
print("\n")
print(">> dfn_tumor", dfn_tumor.shape)
print(">> dfn_normal", dfn_normal.shape)

df_ana

>> dfn_tumor (60616, 460)
>> dfn_normal (60616, 103)

  prog_id     psi_id disease_id primary_site
0   CPTAC       PAAD       PAAD     Pancreas
1   CPTAC   PAAD_GDC       PAAD     Pancreas
2    TCGA  TCGA-PAAD       PAAD     Pancreas

### Clusterization

In [7]:
group = 'Tumor'

verbose=False
force=False

disease_id=DISEASE_ID
imax_tumor=250
imax_normal=50
exclude_prog_list=['CCLE']
n_components = 10
min_clusters = 6; max_clusters = 12
n_umap_neighbors=5; min_umap_dist=0.2; umap_metric="euclidean"
method_hca="ward"; hca_criterion="maxclust"
LFC_cutoff=1; FDR_cutoff=0.05
perc_min_samples=0.25; top_n=10_000

if group == 'Tumor':
    df = dfn_tumor
    n_clusters = 10
else:
    df = dfn_normal
    n_clusters = 3


df_cluster, df_sel, df_cpm, df_pca, df_umap = gdc.cluster_expression_data_group(df, group=group, n_clusters=n_clusters, 
                                                n_components=n_components, min_clusters=min_clusters, max_clusters=max_clusters,
                                                n_umap_neighbors=n_umap_neighbors, min_umap_dist=min_umap_dist, umap_metric=umap_metric,
                                                method_hca=method_hca, hca_criterion=hca_criterion,
                                                LFC_cutoff=LFC_cutoff, FDR_cutoff=FDR_cutoff,
                                                perc_min_samples=perc_min_samples, top_n=top_n,
                                                force=force, verbose=verbose)

In [8]:
dfc_log, dfc_log_nor = gdc.prepare_log_expression(df_cpm=df_cpm, df_sel=df_sel, dfn_normal=dfn_normal, top_n=top_n)


dfc_log.head(3)

10000

,1,2,3,4,5,6,7,8,9,10,...,448,449,450,451,452,453,454,455,456,457
ENSG00000270641,14.479,13.720,14.420,13.992,14.229,12.156,13.862,13.964,13.765,13.668,...,9.388,0.107,9.473,0.350,0.339,9.473,5.700,0.359,8.507,0.339
ENSG00000262619,10.816,10.877,12.968,12.899,14.828,9.721,12.547,10.455,9.238,13.277,...,0.129,0.157,0.833,1.068,1.927,0.055,0.734,0.359,0.522,0.756
ENSG00000281383,3.418,0.000,10.809,0.000,11.366,5.782,3.113,0.000,0.000,0.759,...,0.248,0.206,0.135,0.242,0.885,0.301,0.000,0.249,0.000,0.398

In [9]:
dfc_log_nor.head(3)

,458,459,460,461,462,463,464,465,466,467,...,548,549,550,551,552,553,554,555,556,557
geneid,,,,,,,,,,,,,,,,,,,,,
ENSG00000000971,4.040,2.152,1.815,2.213,2.661,0.765,0.000,1.641,2.880,3.745,...,3.176,0.805,3.168,2.644,0.000,2.488,1.079,2.808,3.059,2.459
ENSG00000001084,1.882,2.542,0.000,1.495,2.069,1.631,0.861,1.641,2.471,2.184,...,1.770,0.000,1.873,0.000,1.393,1.956,3.950,1.585,1.874,0.807
ENSG00000001461,2.124,3.316,2.737,2.548,3.080,1.631,0.861,2.571,4.674,2.184,...,2.327,2.639,1.584,0.728,0.859,1.956,1.846,1.875,3.544,3.999

### Merge tumor + control without combat correction

In [10]:
dfn = pd.merge(dfc_log, dfc_log_nor, left_index=True, right_index=True, how='inner')
print(dfn.shape)

dfn.head(3)

(10000, 557)

,1,2,3,4,5,6,7,8,9,10,...,548,549,550,551,552,553,554,555,556,557
ENSG00000270641,14.479,13.720,14.420,13.992,14.229,12.156,13.862,13.964,13.765,13.668,...,3.042,3.204,5.332,2.484,3.808,4.869,13.583,4.755,3.841,14.448
ENSG00000262619,10.816,10.877,12.968,12.899,14.828,9.721,12.547,10.455,9.238,13.277,...,1.383,1.696,2.320,0.728,0.859,2.488,2.714,4.393,4.029,2.643
ENSG00000281383,3.418,0.000,10.809,0.000,11.366,5.782,3.113,0.000,0.000,0.759,...,0.000,0.000,0.000,0.000,0.000,0.000,1.312,0.000,0.737,0.000

In [11]:
df_metadata = gdc.open_metadata(verbose=True)
df_metadata.tail(3)

Table opened ((557, 3)) at '/home/flavio/uv/perturb_agent/data/multi_progs/lfc/metadata_tumor_and_normal.tsv'

    condition    dataset  condition_numeric
554    normal  CPTAC_GDC                0.0
555    normal  CPTAC_GDC                0.0
556    normal  CPTAC_GDC                0.0

In [12]:
df_metadata.index.dtype

dtype('int64')

In [13]:
df_combat = gdc.open_combat_input_log_cpm(verbose=True)
df_combat.head(3)

Table opened ((10000, 560)) at '/home/flavio/uv/perturb_agent/data/multi_progs/lfc/combat_log_exp_tumor_and_normal.tsv'

,geneid,symbol,biotype,1,2,3,4,5,6,7,...,548,549,550,551,552,553,554,555,556,557
0,ENSG00000000971,CFH,protein_coding,2.246,0.482,2.755,2.204,4.640,0.437,0.524,...,2.887,0.824,2.881,2.424,0.124,2.288,1.062,2.567,2.785,2.263
1,ENSG00000001084,GCLC,protein_coding,2.910,2.282,2.449,2.903,5.244,1.058,3.153,...,1.636,-0.035,1.732,-0.035,1.280,1.811,3.692,1.461,1.734,0.727
2,ENSG00000001461,NIPAL3,protein_coding,4.104,4.274,2.748,0.284,2.603,0.484,2.438,...,2.198,2.476,1.537,0.776,0.892,1.868,1.770,1.796,3.281,3.686

In [14]:
df_combat.columns

Index([ 'geneid',  'symbol', 'biotype',         1,         2,         3,         4,         5,
               6,         7,
       ...
             548,       549,       550,       551,       552,       553,       554,       555,
             556,       557],
      dtype='object', length=560)

### Clusters

In [15]:
df_hca = gdc.df_hca
df_hca

     sample  cluster
0         1        7
1         2        1
2         3        7
3         4        1
4         5        6
..      ...      ...
452     453        5
453     454        5
454     455        5
455     456        5
456     457        5

[457 rows x 2 columns]

In [16]:
df_hca.cluster.max()

10

In [17]:
force=False
verbose=True

nclu=10

cols = df_hca[df_hca.cluster == nclu]['sample']
gene_cols = ["geneid", "symbol", "biotype"]
all_cols = gene_cols + list(cols)

dfn_combat_tum = df_combat[all_cols].copy()
dfn_combat_tum

,geneid,symbol,biotype,48,111,120,131,262,324,333,344
0,ENSG00000000971,CFH,protein_coding,4.308,6.120,-0.203,6.613,3.330,4.627,0.102,4.980
1,ENSG00000001084,GCLC,protein_coding,3.127,4.961,5.789,7.467,2.878,4.522,5.264,6.768
2,ENSG00000001461,NIPAL3,protein_coding,7.896,6.712,6.620,5.741,6.445,5.516,5.444,4.755
3,ENSG00000001617,SEMA3F,protein_coding,7.888,4.245,4.067,4.397,6.512,3.594,3.451,3.716
4,ENSG00000001626,CFTR,protein_coding,6.838,4.306,-0.325,-0.325,6.393,4.311,0.505,0.505
...,...,...,...,...,...,...,...,...,...,...,...
9995,ENSG00000288597,AC234782.2,lncRNA,5.494,4.855,6.865,4.250,5.480,4.860,6.810,4.274
9996,ENSG00000288598,AL354833.1,lncRNA,6.737,2.154,-2.621,2.291,6.742,4.106,1.360,4.185
9997,ENSG00000288611,NPBWR1,protein_coding,-0.155,6.181,6.779,6.075,0.181,6.217,6.787,6.116
9998,ENSG00000288612,AL133351.4,lncRNA,-0.284,-0.284,1.810,-0.284,0.228,0.228,2.132,0.228
9999,ENSG00000288642,CDR1,protein_coding,5.070,2.872,1.337,9.520,5.693,3.865,2.587,9.396

In [18]:
df_tumor = dfn_combat_tum
df_tumor.head(3)

            geneid  symbol         biotype     48    111    120    131    262    324    333    344
0  ENSG00000000971     CFH  protein_coding  4.308  6.120 -0.203  6.613  3.330  4.627  0.102  4.980
1  ENSG00000001084    GCLC  protein_coding  3.127  4.961  5.789  7.467  2.878  4.522  5.264  6.768
2  ENSG00000001461  NIPAL3  protein_coding  7.896  6.712  6.620  5.741  6.445  5.516  5.444  4.755

In [19]:
cols_normal = df_metadata[df_metadata.condition == 'normal'].index.to_list()

In [20]:

df_normal = df_combat[["geneid", "symbol", "biotype"] + cols_normal]
df_normal.head(3)

,geneid,symbol,biotype,457,458,459,460,461,462,463,...,547,548,549,550,551,552,553,554,555,556
0,ENSG00000000971,CFH,protein_coding,2.474,4.674,2.379,1.969,2.453,2.998,0.692,...,2.445,2.887,0.824,2.881,2.424,0.124,2.288,1.062,2.567,2.785
1,ENSG00000001084,GCLC,protein_coding,4.508,1.991,2.685,0.010,1.583,2.187,1.726,...,1.844,1.636,-0.035,1.732,-0.035,1.280,1.811,3.692,1.461,1.734
2,ENSG00000001461,NIPAL3,protein_coding,5.220,2.300,3.651,2.995,2.781,3.384,1.741,...,1.899,2.198,2.476,1.537,0.776,0.892,1.868,1.770,1.796,3.281

In [21]:
df_exp, df_annotation = gdc.prepare_expression_matrix(
                df_tumor=df_tumor,
                df_normal=df_normal,
            )

df_exp.head(3)

,48,111,120,131,262,324,333,344,457,458,...,547,548,549,550,551,552,553,554,555,556
geneid,,,,,,,,,,,,,,,,,,,,,
ENSG00000000971,4.308,6.120,-0.203,6.613,3.330,4.627,0.102,4.980,2.474,4.674,...,2.445,2.887,0.824,2.881,2.424,0.124,2.288,1.062,2.567,2.785
ENSG00000001084,3.127,4.961,5.789,7.467,2.878,4.522,5.264,6.768,4.508,1.991,...,1.844,1.636,-0.035,1.732,-0.035,1.280,1.811,3.692,1.461,1.734
ENSG00000001461,7.896,6.712,6.620,5.741,6.445,5.516,5.444,4.755,5.220,2.300,...,1.899,2.198,2.476,1.537,0.776,0.892,1.868,1.770,1.796,3.281

In [22]:
df_annotation.head(3)

            geneid  symbol         biotype
0  ENSG00000000971     CFH  protein_coding
1  ENSG00000001084    GCLC  protein_coding
2  ENSG00000001461  NIPAL3  protein_coding

In [67]:
from inmoose.limma import lmFit, eBayes, topTable, makeContrasts, contrasts_fit

tumor_samples = [
    col for col in df_tumor.columns
    if col not in gdc.ANNOT_COLS
]

normal_samples = [
    col for col in df_normal.columns
    if col not in gdc.ANNOT_COLS
]

metadata = pd.DataFrame(
    {
        "group": (
            ["Tumor"] * len(tumor_samples) + 
            ["Normal"] * len(normal_samples)
        )
    },
    index=tumor_samples + normal_samples,
)

metadata = metadata.loc[df_exp.columns].copy()

# Intercept + binary tumor coefficient
# Normal is the reference condition
design = pd.DataFrame(
    {
        "Intercept": 1.0,
        "Tumor_vs_Normal": (
            metadata["group"].eq("Tumor").astype(float)
        ),
    },
    index=metadata.index,
)

assert df_exp.columns.equals(design.index)

fit = lmFit(df_exp, design)

design

     Intercept  Tumor_vs_Normal
48         1.0              1.0
111        1.0              1.0
120        1.0              1.0
131        1.0              1.0
262        1.0              1.0
..         ...              ...
552        1.0              0.0
553        1.0              0.0
554        1.0              0.0
555        1.0              0.0
556        1.0              0.0

[108 rows x 2 columns]

In [68]:
# InMoose supports trend=True for logCPM-like data and calculates moderated statistics through empirical-Bayes variance shrinkage.
coefficient_names = ["Intercept", "Tumor_vs_Normal"]

fit.coefficients.columns = coefficient_names
fit.stdev_unscaled.columns = coefficient_names


fit_bayes = eBayes(
    fit,
    trend=True,
    robust=False,
)

In [69]:
print(fit.coefficients.columns)
print(fit_bayes.coefficients.columns)

Index(['Intercept', 'Tumor_vs_Normal'], dtype='object')
Index(['Intercept', 'Tumor_vs_Normal'], dtype='object')

In [70]:
print("coefficients:", fit_bayes.coefficients.columns.tolist())
print("stdev_unscaled:", fit_bayes.stdev_unscaled.columns.tolist())
print("t:", fit_bayes.t.columns.tolist())
print("p_value:", fit_bayes.p_value.columns.tolist())
print("lods:", fit_bayes.lods.columns.tolist())

coefficients: ['Intercept', 'Tumor_vs_Normal']
stdev_unscaled: ['Intercept', 'Tumor_vs_Normal']
t: ['Intercept', 'Tumor_vs_Normal']
p_value: ['Intercept', 'Tumor_vs_Normal']
lods: ['Intercept', 'Tumor_vs_Normal']

In [71]:
gene_annotations = df_annotation.copy()

gene_annotations.index = gene_annotations["geneid"].astype(str)
df_exp.index = df_exp.index.astype(str)

gene_annotations = gene_annotations.loc[df_exp.index]
gene_annotations

                          geneid      symbol         biotype
geneid
ENSG00000000971  ENSG00000000971         CFH  protein_coding
ENSG00000001084  ENSG00000001084        GCLC  protein_coding
ENSG00000001461  ENSG00000001461      NIPAL3  protein_coding
ENSG00000001617  ENSG00000001617      SEMA3F  protein_coding
ENSG00000001626  ENSG00000001626        CFTR  protein_coding
...                          ...         ...             ...
ENSG00000288597  ENSG00000288597  AC234782.2          lncRNA
ENSG00000288598  ENSG00000288598  AL354833.1          lncRNA
ENSG00000288611  ENSG00000288611      NPBWR1  protein_coding
ENSG00000288612  ENSG00000288612  AL133351.4          lncRNA
ENSG00000288642  ENSG00000288642        CDR1  protein_coding

[10000 rows x 3 columns]

In [72]:
print(df_exp.index.equals(fit_bayes.coefficients.index))
print(df_exp.index.equals(fit_bayes.t.index))
print(df_exp.index.equals(gene_annotations.index))

True
True
True

In [73]:
assert len(df_annotation) == len(df_exp)

In [101]:
results = topTable(
    fit_bayes,
    coef="Tumor_vs_Normal",
    number=df_exp.shape[0],
    # genelist=gene_annotations,
    adjust_method="fdr_bh",
    sort_by="P",
)

df_lfc_ori = pd.DataFrame(
    data=results.to_numpy(copy=True),
    index=results.index.copy(),
    columns=results.columns.copy(),
)

df_lfc_ori = df_lfc_ori.merge(
    df_annotation,
    on="geneid",
    how="left",
    validate="one_to_one",
)

cols = ['geneid', 'lfc', 'lfcSE', 'ave_expr', 'stat', 'pvalue', 'fdr', 'B', 'symbol', 'biotype']
df_lfc_ori.columns = cols

cols = ['geneid', 'symbol', 'biotype', 'lfc', 'abs_lfc', 'lfcSE', 'pvalue', 'fdr', 'ave_expr', 'stat', 'B']
df_lfc_ori['abs_lfc'] = df_lfc_ori['lfc'].abs()
df_lfc_ori = df_lfc_ori[cols]

df_lfc_ori

,geneid,symbol,biotype,lfc,abs_lfc,lfcSE,pvalue,fdr,ave_expr,stat,B
0,ENSG00000271207,MTCO1P22,processed_pseudogene,6.799e+00,6.799e+00,0.367,1.169e-87,1.159e-83,0.537,5.904e+01,177.118
1,ENSG00000210112,MT-TM,Mt_tRNA,8.065e+00,8.065e+00,0.367,2.318e-87,1.159e-83,0.712,5.868e+01,176.592
2,ENSG00000240409,MTATP8P1,unprocessed_pseudogene,8.426e+00,8.426e+00,0.367,1.990e-83,6.634e-80,0.693,5.406e+01,169.504
3,ENSG00000285437,POLR2J3,protein_coding,6.585e+00,6.585e+00,0.367,1.126e-75,2.781e-72,0.635,4.594e+01,154.854
4,ENSG00000262902,MTCO1P40,processed_pseudogene,6.833e+00,6.833e+00,0.367,1.390e-75,2.781e-72,0.663,4.585e+01,154.676
...,...,...,...,...,...,...,...,...,...,...,...
9995,ENSG00000165168,CYBB,protein_coding,9.012e-03,9.012e-03,0.367,9.879e-01,9.883e-01,2.442,1.522e-02,-6.900
9996,ENSG00000177301,KCNA2,protein_coding,-1.166e-02,1.166e-02,0.367,9.918e-01,9.921e-01,5.837,-1.031e-02,-6.900
9997,ENSG00000134874,DZIP1,protein_coding,-5.572e-03,5.572e-03,0.367,9.927e-01,9.929e-01,4.194,-9.161e-03,-6.900
9998,ENSG00000160055,TMEM234,protein_coding,-5.034e-03,5.034e-03,0.367,9.944e-01,9.945e-01,4.192,-7.059e-03,-6.900
9999,ENSG00000019991,HGF,protein_coding,-7.966e-05,7.966e-05,0.367,9.999e-01,9.999e-01,2.295,-1.483e-04,-6.900

In [102]:
";".join(df_lfc_ori.symbol)

'MTCO1P22;MT-TM;MTATP8P1;POLR2J3;MTCO1P40;AC005041.5;AC135507.1;CYB561D2;MTND6P22;CFAP73;AC006017.1;AC084125.1;AC105328.1;AC090607.1;UBE2Q1-AS1;MTCO2P2;AP000781.1;NR2C2AP;AP001160.3;AC013489.3;AC007193.3;HCRTR1;AP003307.1;DLX6-AS1;AL021707.5;AC091153.4;STRADB;AC005306.1;RSPH9;MIR1282;AC005943.2;AP003068.1;AC005045.2;ARAP1-AS1;ASH1L-AS1;BRICD5;TMEM18-DT;AP002433.1;AL031587.2;AC002401.1;NUCB1-AS1;AL049569.1;AC073263.1;RNA5SP216;AC010542.5;AL390208.1;LINC00337;AL132639.3;AC020558.1;AL513218.1;C14orf178;AC009065.7;MTCO2P12;AL358937.1;MROH8;AC127024.6;MTND6P4;MCCC1-AS1;U47924.1;AL929472.3;AP001458.1;AL078612.1;AL603839.1;AL110504.1;AC005262.2;AC013472.2;AL354920.1;AL353708.3;AL353689.2;AL355310.2;AC092118.2;AC008915.2;AC009113.2;AC231981.1;SLC6A1;AC020934.2;AF129075.2;AL138724.1;AC009137.1;MT-ATP8;U47924.2;MUC2;MRAP;COA6-AS1;AC006547.3;AC009065.1;MORF4L2-AS1;AC022382.1;AL929472.2;AC023055.1;AC022201.2;AC073389.2;AC025283.2;FBXW7-AS1;ZNF649-AS1;AL513550.1;C1QTNF7-AS1;AC145207.8;GDF9;EGILA;AC087362.2;AC018761.2;AC231533.1;ANAPC10;AL391834.1;OPA1-AS1;AF235103.1;LRRC24;MIR762HG;AC004386.4;AC104187.1;NOMO2;AC005726.3;AL158212.5;CCDC103;AL158141.1;GPAT2;AC107398.4;AC007610.2;AP000812.4;AC007493.2;MTND1P23;KMT2D;AC104117.2;SLC28A3;AC069234.3;AC074044.1;AC007040.1;BX664615.1;AC012085.2;TP63;AC008870.4;MYL5;MRPS9-AS1;AC015853.1;AC007448.4;AL023584.1;C9orf43;SBNO1-AS1;AC137630.2;AC027309.1;P2RY11;AL592166.1;AC025259.1;AC087276.3;IKBKG;AL359644.1;PRPS1P2;AC131238.1;MT-ND5;TMEM53;SCN5A;PROM2;AL022345.4;AL356124.2;AF129075.3;AC132812.1;AC008114.1;MT-TS1;AC004386.2;MUC3A;ABHD11-AS1;AC090907.2;MUC16;AC012309.2;AP001160.1;AC026191.1;AL031778.1;FNDC1;PPIC-AS1;MIR762;AC116428.1;AP001775.2;AC025918.1;AC011498.3;PHBP12;NOTCH3;AC244100.2;NLGN2;AC131953.1;AC073569.2;AP005432.1;AL031775.1;MXRA5;AC010320.2;AL158847.1;WDR83;AC108102.1;AC005021.1;WDR11-AS1;MTND4P35;AL355490.2;AC012435.2;AC092794.2;ERCC8-AS1;AC138028.3;AC073834.1;AL138966.2;REPIN1-AS1;MTND4P12;MIR374C;AC018521.4;AL035658.1;IGFN1;POLR2L;OCIAD1-AS1;POLR2A;AL353807.3;CCDC26;AL603756.1;AC025271.2;MT-ND1;AC107871.2;PLBD2;AC018761.4;COL7A1;B4GALT4-AS1;AC034102.4;MT-ND2;AQP11;PINK1-AS;UXT-AS1;AC017101.1;Z97652.1;GJA1P1;AL355075.2;U2AF1L4;CR936218.1;AP000251.1;AC046143.1;AP001160.2;AC067930.5;CD81-AS1;TET2-AS1;GAPDHP42;AC009133.4;AC091133.1;AC022211.2;MT-ND4;AP001021.3;AC005037.1;TRPM4;AC027514.2;AL133406.1;TMED10P1;OR7E128P;C12orf60;AC008937.3;AC010653.2;TUBB6;OAS3;AC011466.3;AF131215.1;USP28;AL020997.4;ARR3;DCUN1D2-AS;AC011815.3;NDUFB2-AS1;MTND5P11;OBI1-AS1;MED8-AS1;AC012618.2;AC091607.2;AC100763.1;STIM1-AS1;GLTPD2;MIR3661;SLC38A7;IGBP1-AS2;SHLD2;AC000068.2;AL357140.1;AC079880.1;MTX1P1;SLC9A1;GABRE;AC004696.1;AC009141.1;AC113382.1;TAX1BP1-AS1;PROSER1;ZNF133-AS1;AC068389.1;AC008750.3;AC123768.2;AC115621.1;WASHC5-AS1;AC006042.1;MTND2P28;RPL12P11;VLDLR-AS1;AL139120.1;AC104365.1;XACT;AC104819.1;AL670729.1;AC002350.2;SRRM1;BX284668.4;AC084824.4;ZDHHC14;AC121251.1;CYB5RL;PIMREGP4;AL162584.1;AC112907.3;SMIM18;AC022973.5;EGLN3P1;AL158801.2;AP002433.2;AC004217.1;SH3GL1P3;SOX2-OT;AC012254.4;CAPN15;AL391863.1;AC100778.3;AC011092.2;RNA5SP37;LINC00571;SPAG1;SMIM15-AS1;AC009480.1;ATP6V0E1P1;SH3D19;MT-ND6;AL136038.2;SDK2;NT5DC2;KRT18P12;AC022558.3;AC044840.1;ARAP3;MIR631;AC106736.1;TET3;SLC7A1;AC018754.1;AC090192.1;NLRC5;AC015922.2;LINC02863;C6orf201;AC008417.1;AC132219.2;AP001363.1;PDHA1P1;AL117332.1;AC127496.3;AC087749.1;AC020913.2;AC004528.2;AFF2;AC008878.4;MTCL1;AC012379.1;GLIPR1L1;PLN;AL589990.1;ONECUT3;NDUFB4P2;AL033528.2;POU2F2;AC009630.3;AC005154.4;GPATCH8;NOP53-AS1;GLRX5P3;ZBTB20-AS3;RIMKLBP1;AC027601.2;CHP1P1;AP003096.1;SUMO2P8;URAHP;AC007599.1;AC134407.1;AL451070.1;AP001527.2;AC026704.1;AC010285.3;GRPEL2-AS1;KRT17;KSR1;LRP1-AS;AL591721.1;AP003068.3;KDM4B;CHD8;SSC5D;HMGN3-AS1;CROCCP2;AMER1;NLRP1;CHADL;AC106760.1;ZAN;AARSD1P1;RPL17P17;JSRP1;AC100791.3;MIR6080;AC108475.1;AC127496.4;AL161452.1;ZNF497;LINC00867;PCLO;AC083805.2;AC016722.2;AL445187.1;AL035413.1;CEP164P1;MIR924HG;NDUFB4P6;SAP130;FAM86FP;DPP6;AC091046.2;AL132639.2;ACBD3-AS1;AL590369.1;FABP5P3;SERTAD2;AL132765.1;AP001372.3;AC241585.2;ACSF3;PDGFRL2P;AP001001.1;MTCO3P12;AC022413.2;AL591002.1;CTRL;TSPOAP1-AS1;AL049820.1;AL365330.1;MTCO1P12;TFCP2;ARHGEF1;IGF2R;DPY19L2P3;OVOL3;AC090425.3;AL592148.3;RPS2P16;AC060234.1;AC069236.1;AC037459.2;AP001972.1;FBXL6;GRHL1;YLPM1;MCM5;AC131953.2;PRELID1P3;ATP5MGP8;AC022001.2;AP003465.1;AL365258.2;EMC1-AS1;AC093484.3;AC117503.5;AL355297.3;TPMTP2;AC092070.3;AC007036.1;AC010494.1;AL161909.2;SERINC2;AC005154.1;AC009237.8;AL512656.1;MTATP6P1;ATG10;AC055733.1;AC034102.6;AL139396.1;H4C9;AL162591.2;ANKUB1;MT-ATP6;CACNA2D1-AS1;AL513188.1;AC008149.1;MYG1P1;AC021739.3;ABCB9;EP400P1;AL391839.1;AL161430.1;HMGB3;MKI67;AC245140.2;AC104134.1;ATG12P2;EIF2S2P5;ENPP7P12;PKNOX2;NSA2P5;AC022211.4;BCAR3-AS1;AC011825.4;DUTP7;AC100854.1;PABPN1P1;AC010883.1;STAT2;AC105020.6;MT-CYB;AC084125.2;AC022001.3;WDR38;AP005131.3;AC005230.1;AL359258.2;GREM1;AL022341.2;MTMR4;LINC01122;AL391557.1;AC008897.1;BRD4;PROM1;AL049780.1;DLG3-AS1;SNX29;DEFB131B;AC016590.1;RPS15AP13;EDDM3CP;AC010273.2;RNASET2;MRS2P2;RPS5P2;AL158834.1;AC087276.2;RPL17P25;ARHGEF19-AS1;AP006621.1;PRKCE-AS1;AC010285.1;AC004492.1;DLG2-AS2;KIF1C-AS1;AP000757.1;ADD3-AS1;CD74;AC073569.1;AL138963.3;AC036103.1;AC018557.3;AC106739.1;AC037459.4;AL136172.1;RPS6KB2-AS1;AC008080.4;AC022898.1;AC093512.1;AC073167.1;BCORL1;AC020978.2;IDSP1;AL031600.1;H2AZP4;CEP78;MFSD14C;AL359317.1;AC087439.1;AL627308.3;AC013549.3;AL022097.1;AP4B1-AS1;GPS2;COL1A1;PRKAR2A-AS1;MXD3;AC012363.1;AC023818.1;BANF1P3;SMARCAL1-AS1;GGNBP1;UBN2;MMADHC-DT;AC012173.1;SHISA5P2;AC130650.1;NPM1P26;MT-ND3;ZSWIM6;CTD-2350J17.1;AC074276.1;AL450344.2;AC021424.2;KANSL1;KLF5;IL17RA;HIP1;AL357140.4;CENPF;AC130343.3;APOM;C4orf33;RPL21P30;AL049552.2;PTGFRN;GGACT;AC011921.3;ARID1A;AL603832.1;AL118556.1;LBHD1;WIPF2;KLHDC7B;SNORA14B;PPIAP91;AC010834.1;ATXN7L1;AC007780.1;AC020904.3;NFIC;SEC23A-AS1;HECTD2;WASF2;AL161672.1;AC011092.3;GTF2E1;GTF2I;MYO18A;BCAM;COL27A1;DENND6A-AS1;ARSD-AS1;AL133375.1;AP003467.2;SLC51B;CSNK1E;AL731702.1;AL035427.1;PTMAP5;AC091564.2;AL034351.4;AC093535.1;EYA2;SLC26A10;AC078929.1;AC009432.2;MLXIP;NPB;AC138932.4;AC097515.1;AC006027.1;NHLH1;AC079203.2;AC093484.4;ATP9B;AC005703.5;RERE;PPIAP53;AC104758.1;AC021092.1;AP001469.1;PKP1;CYYR1-AS1;USP20;AC020728.1;AL133370.1;CNOT4;RTL10;AC087821.2;AC064874.1;AC008840.1;SNX9-AS1;PHF23;AC091180.3;SOCS7;ITIH4-AS1;AC012073.1;CD276;AL354836.1;AC025449.2;AP002383.2;AC087071.2;VTCN1;AC137630.5;AL133368.1;MT-ND4L;AC007679.1;TENM2;INTS4P2;AL512593.1;CDK5RAP1;AC004943.1;AP001439.1;AC244517.5;VAMP2;SNORA70G;ZNF135;AC025043.1;AC127024.5;ZNF536;RPS26P41;NCBP2-AS1;MCCC2;RANBP10;NUP210;DPYD-AS1;ZBTB8OSP1;SLC2A3P4;MT-CO2;AC117490.2;ASXL2;AC011773.1;AC019077.1;AL512326.3;AC069549.1;AL355385.1;AC106873.1;PRR12;CNTN4-AS1;CCDC6;LTBP4;PRDM2;AGRN;FARP1-AS1;HSD17B6;CFL1P3;AC073130.2;AL441963.1;AC090181.1;AC109322.1;AC136469.2;AC020910.4;AC012557.1;AL021707.3;AL049829.2;AC010185.1;FAM217A;HIVEP3;C6orf132;COLGALT1;TRIM11;HGSNAT;CARS1-AS1;SATB2;CBX3P3;RN7SL330P;DTHD1;AC141586.3;TIMELESS;AL592546.2;AC244517.4;AC027575.1;AL354733.3;AL391056.2;SETD1B;AL137060.5;FAM13A-AS1;MARK1;AC015813.7;TMED2-DT;AC113189.1;AC004882.3;ZNF252P-AS1;PLAAT3;AC009831.1;AL450467.1;LINC01132;CHST12;AC015795.1;AC113143.1;AL136090.1;AL033384.2;ZBTB4;AC087588.2;AL137060.8;AC019130.1;PEX26;TEX41;KAT6B;ABAT;AC002128.2;DMWD;ACVR2B;TNFRSF21;KIF21B;AREL1;CLASRP;AC015982.1;AC073573.1;AC025917.1;SH3PXD2B;SCAT2;AC091132.3;ZNF703;AC016493.1;AC011611.3;AC139792.1;VENTXP6;AC011365.1;SYNE3;RPL36AP41;SLC34A3;AC068385.1;HADHAP1;AC137630.3;AKNA;MOB3C;LINC00484;ZNF350-AS1;AC108693.2;AP002336.3;RRM1-AS1;AL136310.1;IDI2-AS1;SH3BP2;AC090519.1;NBPF1;MBD2;DVL3;RNU6ATAC;PKD2L2;DSG2-AS1;AC106820.5;AP003086.2;LINC01278;AL669841.1;AC025271.3;TFE3;EHMT1;AP000763.3;AP005329.1;SNHG3;SEPTIN7P6;AL031770.1;ZFHX4;TMEM161B-AS1;AC089999.1;ARID1B;ATP13A1;PLEKHS1;IGFBP7-AS1;AC023480.1;AC055764.1;PHACTR4;AF181450.1;AC243571.2;AC073863.1;SP100;SETP5;AC090061.1;AC109446.2;RPL31P20;CHD7;EME2;AC079305.1;SETD1A;AL512306.1;IKBKB;LYG2;MPHOSPH6P1;SRC;AC026347.1;AC007494.1;TM2D3;AL390071.1;SETP10;ZNF217;H1-10-AS1;AC024145.1;MMACHC;CCDC151;PRANCR;TRPS1;AC005104.2;NAV2-AS2;AL449106.1;JTB;CLEC16A;AL358216.1;RNU4-2;STAMBP;BNIP3P39;SMPD4;AC002070.1;C10orf105;AC012409.1;PVT1;OR7C1;AC007342.6;MICAL3;PLCE1-AS1;AL034349.1;AC087292.1;AL390754.1;MKNK1-AS1;ANO1;SMC5-AS1;AC016825.1;WDTC1;CCNJL;AC114730.3;COX7CP1;AC006026.3;AC108063.1;AC011933.4;AC092343.1;AC092567.1;RPL29P11;LAMA3;AL008726.1;AC090971.1;FBXO42;AC005828.1;SNRPGP15;MARCKSL1P1;AL356320.2;AC073651.1;XPO6;ERMARD;AC009120.2;AC037198.2;CHD3;ZZEF1;Z94721.3;AC009084.2;AC017083.3;R3HDM1;MLLT6;TMPO-AS1;AC073333.1;NCMAP-DT;AP002490.1;ME2;AP003550.1;AC009065.6;HIPK2;MIDEAS;RPS27AP10;AC004593.2;AL355388.2;AP001021.2;SERPING1;MXD4;AC139769.2;BRPF3;AKR1C6P;AC073957.2;BUB3;FLRT3;SLC18A2;CDNF;AC020558.6;PHBP9;TTL;AC078925.4;MAN2B1;RPS15AP16;PDE10A;SLC7A8;RNU5A-1;CCDC152;AC012613.2;TRIM26;PRR36;SOGA1;AC024560.2;NECTIN4;TRAF3;SPPL2B;AC022601.1;EPB41L4A-DT;RPL21P23;SNAP47;MTOR-AS1;AC006030.1;AC002550.1;ZFP36L1;KDM5B;ABHD16B;SMARCA4;ARHGAP35;CDK12;AC034102.5;GATAD2B;SLC25A15;HTR5BP;AL159174.1;NCBP3;AP000487.2;AC005154.3;AC007000.1;AC006270.1;TXNP6;AL356608.3;AC109587.1;AL606517.1;PML;ZNF746;EPN1;SLC44A2;AUTS2;AKAP6;AC127496.6;AC011498.6;KDM2A;C9orf147;WARS2-IT1;AC092608.2;AL449212.1;AC009303.2;AC055855.1;SHANK2;TAB2;PPP1R12A-AS1;RREB1;KDELR1;CHMP1A;AC021106.2;AC010768.1;ZMIZ1;AC006213.6;ESRP1;AC015813.5;SRPK3;PCSK5;AL035252.4;MARK4;MFN2;AC138207.1;PPP1R13L;ZNF578;AC005606.2;ROBO1;AP002770.1;GORASP2;VEZF1;AKT2;SYNE1-AS1;MEG3;AC138473.1;VPS13D;EZR-AS1;GK-AS1;FKTN;AC098869.2;TET1;AL445465.1;LIX1L-AS1;WWC1;AC008700.1;KDM6B;AC093752.1;STIM1;PIGG;AC025165.2;AC018816.1;AL161421.1;ZMYM3;AC093110.1;RCCD1-AS1;ARMCX3-AS1;SLC4A1AP;AC079742.1;AL161757.2;PREX1;MIR181A2;ATN1;AC114402.1;AC025754.1;ACP4;MR1;AC007151.1;PRMT5-AS1;POMT2;BNIP3P27;YKT6;PTRH2;ZNF84;MIR3918;AL355612.1;TTC3-AS1;MSI2;AC064852.1;RPGR;SMOC2;KLHL6;WIZ;MMEL1;AC002558.2;AC027018.1;AC021037.1;CREB3L1;AC087362.1;ITGB4;EP300-AS1;AL391416.1;LPP-AS1;NEAT1;AC093462.1;NADSYN1;MEGF8;CERCAM;FLRT2;AC137834.2;RPL10P12;AL139095.4;AC012254.1;THORLNC;ELMO1-AS1;FAM166A;GANAB;AC022167.2;MRPS18AP1;C11orf24;FUS;PKD1L2;PGM5P2;Z95152.1;AC011247.1;AC093866.1;AC010480.1;AC078795.1;AP003392.1;AC079907.1;GTF2IRD1;DTX2;GPATCH2L;KCNN3;MDC1;RNY1P6;NFIA-AS1;AC080162.1;SNX32;AC012640.4;AC073349.1;MMP21;AC090971.2;PCSK1;CDH1;LMO7-AS1;RGS17;PNPLA7;AC005775.1;AC099063.4;CLCN7;TYMSOS;AL133481.1;AC092608.1;ATP5MF-PTCD1;KIRREL1;AL008730.1;RPS9P1;MYH14;AL645933.1;AL445928.2;LMNB2;AC116407.3;AC090236.1;SH3RF3-AS1;RBM33;AL121830.1;AC068620.2;BNIP3P26;SEC23B;AC008914.1;RBMS1P1;AP000879.1;KLRB1;EP400;SPPL3;AC093423.1;AC009237.3;NCOA7-AS1;TULP4;AC005523.2;AP003086.1;AC006449.3;FOXP1-AS1;SEC11A;ANXA2P2;NFYC-AS1;NUMBL;MED22;PCNX3;FBN2;SEC62-AS1;MEF2D;ARHGAP29;AL442071.1;DDX18;POLR3A;ZNF384;AC073534.1;Y_RNA;AC018511.2;ZC3H7A;SCRG1;ACACA;SHANK1;CBLN3;ZC3HAV1;LINC02157;AC009630.2;AC040934.1;GAPDHP60;SOBP;LINC00632;AC020900.1;ZNF580;AP001011.1;B3GALNT1P1;TAB3-AS2;DEFB109F;AC007728.1;LGALS8-AS1;PTK7;BCOR;Z98885.1;APOA1-AS;PPP1R18;LCOR;MYCBP2-AS1;NHSL2;AC025257.1;RPL6P12;Metazoa_SRP;AL139011.1;ZMAT3;CSK;AC018693.1;AC022126.1;AL662797.1;TMEM33;CFAP251;AC104115.2;BCL6;BTBD7;DPP8;AL358333.2;UBE4B;PIGN;GATAD2A;AC090953.1;AL133415.1;CYRIB;AC096733.2;CLASP1;AC103858.1;AC007298.1;AC136424.2;FOXP4;KLHDC4;AC091117.1;AL353586.1;KCTD4;MTA2;MTRNR2L12;AC023510.1;AL118556.2;MIR1260B;CFAP54;MSX1;FGF14-AS2;AC027698.1;BICRAL;AC124069.1;XIAPP2;AC092896.1;CABP7;AL121928.1;PCCA-AS1;AL606517.2;AL391069.1;IRAG1-AS1;AL121787.1;KRT18P57;POLE;AC078889.1;GNRHR2;RNU4-1;MIR181B2;PPARGC1B;VAV3;AC116348.3;AL355075.3;MPRIP-AS1;AC002064.2;CSNK2A1;TMEM214;AC007001.1;NDUFA3P2;PTPRF;AC022395.1;BIRC6-AS1;CAVIN2-AS1;SBK1;ABCA7;AC022150.1;AC102945.1;EFCAB14-AS1;AP000926.2;GALNT2;TTYH3;AC092279.1;MTOR;RPL23AP23;AL713922.2;TCF20;FAM214A;TSTD2;ATG10-AS1;AC007378.1;AC006557.3;AC022137.2;LASP1;PLEKHG2;USP31;TIMM50;NACC1;MDGA1;AC093732.2;AP001453.1;AC008443.1;AC009812.1;AC069029.1;AF001548.1;ERBB4;AC114947.2;SIPA1L3;BDH1;AC063976.2;ZMYM2;AC099501.1;TM6SF1;AL356124.1;GRWD1;CD44-AS1;AL583824.1;AC007000.3;AC021739.2;EMC10;CALM2P2;USP11;EIF3E;C1QL3;EPPK1;HSPB6;RBM19;BICD1;AL355483.1;ITGAL;BCL11A;SNORD3C;AL136231.1;AC072039.2;AL513475.1;ZRANB2-AS1;EXOC4;AC133106.1;PSPC1-AS2;AC096751.2;AL139353.2;AL445183.1;UBXN7-AS1;AL606534.1;ICE2;Z99496.1;HDAC6;AC004898.1;OLFML2A;AC074050.3;WHRN;NUP205;NOLC1;SPG7;AL356652.1;PRRG3;AC104164.2;ABCC5;AC003989.2;ERI2;AC138466.5;AC008277.2;EEF1A1P11;STIM2;SNRPGP4;PLBD1-AS1;RNU1-153P;AC055733.2;NCF4-AS1;JAKMIP2-AS1;AC007496.1;AC010605.1;AC079313.1;RYR1;AC092757.2;AC023024.1;AC104532.2;CFAP99;AC011462.2;LINC01589;AC026470.2;GAPDHP2;ST7-AS2;ZBTB7A;ENPP7P4;MAGI1-AS1;EIF4G1;AL096678.1;AL033397.2;ERCC3;ABCC1;AC006213.2;ZNF326;H2AZ1-DT;AP000943.2;GPR79;YBX1P3;MUC5AC;RNF44;DAB2IP;AC009299.2;NFIX;AC013451.1;TRIM56;AC092140.1;AP005717.1;SEPTIN7P1;AC027682.5;RN7SKP9;AC141424.1;AL035661.2;HSD3BP5;RPL35AP13;FARSA-AS1;AC114730.1;AP003031.1;AC092839.1;B4GALT1;AL121672.2;AC126182.3;SPAG5-AS1;MED15;AC015712.2;AC104126.1;AL121768.1;ADIRF-AS1;AC007620.2;HYOU1;TMPRSS11CP;PLCL2-AS1;NCKAP1;AC022973.2;AKR1C2;PAK1;AC008277.1;AC073130.3;Y_RNA;AC090617.10;TRIM38;MIRLET7BHG;MECR;AL109809.4;FAM81A;SEC31A;TAF15;UBXN7;NECTIN1;AP000925.1;AC018638.1;ADAM19;PHLDB1;AC116424.1;ENPP7P5;BICRA;GSTP1;VHL;PRMT1;CABIN1;AP000769.2;ARL4AP4;AP005210.1;TCF7L2;BTN3A2;SRD5A3-AS1;AF111169.3;ARIH1;AC007551.2;STK10;C19orf71;LMAN2;AC004067.1;AC211433.1;SETD5;UQCRBP1;AC005324.4;AL023807.1;PDE3A;AC114878.1;FP671120.7;ZNF608;GLRX5;DCAF7;AP003032.2;AC011997.2;ZBTB11-AS1;PRDX3P1;AC012645.3;AC108676.2;AC135178.4;MAPRE1P1;CNTN4-AS2;CARNMT1-AS1;TMED11P;MEF2C-AS2;SARNP;LINC00476;SNX27;AL360182.2;TRPM2;PPP2R5E;ARL17A;CHST3;OR7E14P;AC010761.1;CYTH1;EGFR-AS1;AC234917.2;DARS-AS1;AL034405.1;ZNF605;UBR4;AL158151.2;AL138787.2;NSFL1C;AC092652.1;FBRS;AL592148.1;ANKRD18EP;SPON1-AS1;ILF2P1;EPHB4;LANCL1-AS1;PLOD1;MAGED1;HELZ2;AC036108.1;DDX39B;AC005726.2;AC022493.2;TLK1;PTCD1;COP1;CDPF1P1;AL359076.1;SLC35E3;AL157871.1;NNAT;COL5A1;COL11A1;AP000593.3;AC034105.3;SEPTIN6;TBK1;AC108449.1;AL357054.4;OTUD7B;DHX57;AC012157.2;AC022022.1;PLAGL2;AL049552.1;DIRC3-AS1;BEND3P3;RNPS1;AC022784.5;TNRC6B;AUXG01000058.1;PWWP3A;PARP1;SAMD11P1;UBA52P8;SPI1;PSMB2;AC007919.2;AC008738.3;POMK;SETBP1;AC100786.1;PTPA;VANGL2;AHDC1;AC007610.1;RAB3D;TRANK1;TNRC18;NREP;AC009974.2;RNY3P13;WDFY3-AS1;AP001615.1;AC069272.1;PSMD8;DPP9;TRIM9;GOSR2;CDK6-AS1;GAS7;ABL2;NFIB;AP000487.1;AL162408.1;AP000866.3;LINC00665;CSMD2;AL731563.2;UNC93A;AC008833.1;SRI-AS1;AC007292.1;SUB1;AC026202.3;ARHGAP23;KCND3-AS1;CC2D2B;AC011731.1;THRAP3;AC244131.1;CCM2;CDK2AP2;AC097658.1;AC105285.1;AC067930.4;ARAP1;SDK1;SLC25A5-AS1;MFSD11;KANSL3;SPECC1;MT-CO3;AC009899.1;HSPG2;AC092567.2;AC007496.2;AP000753.2;AC021733.4;RBM47;AC008906.2;AXIN1;CIC;RAB5B;CFAP44-AS1;AC009542.1;LAMA5-AS1;AC067751.1;UST-AS1;DLG5;FTH1P24;ZNF460-AS1;FAM71C;ARGFXP2;AC021016.2;AC011477.2;AC003989.1;AC007130.1;AC093797.1;AC103853.1;AL513217.1;AP001972.2;AL353768.2;MGRN1;TMTC2;ZKSCAN1;NUTM2A;STPG3;AC023510.2;AC131182.1;AC025034.2;PRR29;SIRT2;RPS2P15;D2HGDH;AC107886.1;AL136418.1;HPGD;AL356488.3;AC079226.1;IL1R1-AS1;FAM90A1;ASAP1;RASSF1-AS1;PYCARD-AS1;PRICKLE2-AS3;AC021424.3;AL358334.3;AL078459.1;TUFT1;AC007533.1;AC129492.6;SUMO1P3;ADCY4;AC096921.1;AC004765.1;PARVG;AP1B1;AC025576.2;AL356057.1;ULK2;ATP11A;RPL12P24;ERF;TAC4;AQR;TAF4;LAMC1;AL136320.1;BCL2L1-AS1;MX2;COG2;MAML1;AC004837.2;AC011510.1;AC009318.1;FTO;HTT;MT-CO1;AC104078.1;DCAF5;AC007319.1;KCNC4;RFWD3;AC060234.2;PRKACA;SETD7;SIPA1L1;RPS3AP34;SMAD1-AS1;AC004134.1;RN7SL285P;EGR1;JUP;MDC1-AS1;PRRC2C;AP002498.1;RIN2;AC013286.1;TIMM17B;AC100782.1;AP004289.2;AL158198.1;NOVA2;SCML4;PLA2R1;KIAA1549;CAD;ATP8B2;MUTYH;TCF4;AC073655.3;TMEM217;AC026427.1;SNX9;AC021242.3;AC022382.2;PEF1-AS1;AL353759.1;SMAD5;SNRK-AS1;RNY1P13;ZNF320;MAP3K20-AS1;AC025442.1;ABCA2;ARHGAP26;BRD7P3;CLIP1;AC006128.1;AL513190.1;MIDN;AP003392.2;TMEM147-AS1;AL160281.1;AP005059.2;A2M-AS1;AL445123.1;AL136980.1;KIAA0930;NFATC4;AC016549.1;ENSA;MMP11;AC009511.2;AL592146.1;HMGA2;AL118511.1;FASN;PCDH7;NRBP2;AC010261.2;CCSER2;CA3-AS1;AC015912.1;EGFR;COL1A2;KIF13A;NCBP2L;SRMP2;EPHA2;CALCOCO1;KCNV2;BTBD8;AC020914.1;CHAD;PPP2R2C;HNRNPA1P45;AL158801.1;NOTCH2;AP001885.3;LINC00511;TLE3;C4BPAP1;LDHAP2;AC092755.2;RIMKLBP2;AL513008.1;HMCN2;AC025165.1;AC107027.1;KCNJ6;RNMT;NR1I3;PRRC2A;ARHGEF3;SULT6B1;SSXP10;WDR86;AC107081.3;SLC9A9-AS2;KDM6A;LCTL;ETV5;VCAN;CCDC27;SREBF2;KALRN;GNA14-AS1;AC104982.2;C12orf40;AP003110.1;PPM1K-DT;GNB5;ZNF33A;PGAM2;AC136424.1;AC040975.1;KCNK6;SYNPO;R3HDM2;CDHR3;ZFR;HARBI1;MME-AS1;KIF3B;SEC63P1;CCNL2;ARL2BP;SIAH2-AS1;AC025627.1;AC002347.2;YIPF3;SAE1;ZBTB7B;LINC02316;ATXN2L;RFX2;GNAO1;SNX2P1;AC027811.1;NABP2;SLC2A1;RANGAP1;CDYL;ACKR4;MCF2L;AC005281.1;AL390774.2;AC009365.3;SERPINH1;ECT2L;ACOT11;DROSHA;LINC01133;COTL1;MIR4273;AC097534.1;RAB6D;AP000902.1;AC139272.1;GABBR1;ICE1;AC011558.1;PITPNM1;LINC01465;ARID5B;HSPB1;AP002907.1;PRICKLE2-AS1;AC005618.2;RAB7A;EIF3K;ZNF316;HBS1L;ITPRIPL2;WIPF1;SBNO1;NEO1;SDC3;AL109761.1;AC009690.2;AC011451.2;RELCH;MIR205HG;FCGBP;AC023906.4;EBF1;PDSS1P1;WDR13;AL390236.1;NCOR2;AC099850.3;ABCF3;SNED1-AS1;AC078777.1;CEP350;AC096720.1;KLF13;CACNA2D3-AS1;DIP2A;AC105114.2;AL512631.2;VOPP1;AL121748.1;SEPTIN9;AL353804.2;CEMP1;MICALL1;AP000560.1;APC;AP005436.2;AC107050.1;AL136131.3;AL138960.2;KNOP1P2;TLE5;IL10RA;AC119403.1;ATP8A2P2;NOTCH1;DTD1-AS1;SLC6A6;SUPT5H;AC022509.1;DNM1;GLYATL1P1;CST3;ARF3;SSH3;CRTC2;ODF2-AS1;MAPKBP1;FBXO3;AC027237.3;UTP25;NAV2-AS1;AC092910.2;OR2A42;LPP-AS2;AP001610.2;APOL2;AL442663.3;HMGB1P14;AC010132.2;KHSRP;SLC39A6;AL136115.1;AC008945.1;MAP4;AC099850.1;AC025031.2;KCTD10;NABP1;EHD1;RAB11FIP4;AL031280.1;RAB11FIP5;CASC11;CYB5R3;RPS12P3;GNB1;AC091814.1;AC008038.1;AC007494.3;RAB28P5;UBFD1;ARHGEF2;AL121601.2;TMSB10P1;AC012100.2;AP001381.1;TMEM256P2;MGA;AL133444.1;AC104031.1;PRPF8;AL591719.1;AC139495.2;AL160274.1;SPC24;AC011479.4;AC110597.3;LTBP1;DYSF;AC024451.1;CDKN1A;SIDT1-AS1;AC020913.1;NCOA1;SETD4-AS1;MTCYBP18;AP001029.2;AC134669.1;EIF4G3;AL359182.1;ACACB;AC092910.1;BX004807.1;LETM1;AC009269.2;PLEKHG5;FBXW2;AC004551.1;AC005261.2;AC097063.1;Y_RNA;AC007066.1;Z97832.2;AL606534.2;AC107896.1;AC066613.2;GATM;BMPR1AP1;MARK2;SLC25A3P2;AC127459.3;TMEM106B;ACLY;AC105935.2;STOML1;AL163193.1;ADAMTSL4-AS2;C1orf167;POGZ;AC004974.1;RPL3P6;RPL6P2;PSME3;NFATC2;Y_RNA;XYLB;CACHD1;ZNF445;AC080128.2;ACHE;AC011603.2;AC243772.3;AC093225.1;C18orf12;SLC7A5;PTPN3;AL021707.1;ADH6;ACAP2;OR2A1;AC009716.1;YEATS2-AS1;FOXJ2;AC120349.1;AC092574.2;GAS5-AS1;ALG13-AS1;PGAM1P5;INPP5D;AL139807.1;AC006460.1;AC104332.1;AL354977.1;RC3H2;AL158136.1;AL050403.2;AP004289.1;LRP4-AS1;SNX19;AL031717.1;AC107068.2;TMPRSS4;AC025370.1;ENPP7P10;AC084337.1;CCNYL6;AC087286.2;PDZK1P1;AL031123.3;ACSL3-AS1;FBXW7;UTS2B;AC027097.1;AL009178.3;PLEKHA5;QRSL1P3;CATSPER2P1;RAP2B;YIPF4;AC011853.2;AC012645.4;AC006942.1;AC009554.2;AC005013.1;MLYCD;LINC01890;EIF4EP1;PIGHP1;EEF1B2P7;EDC4;AC023796.2;SNRPCP4;AL627308.1;ELN-AS1;FNBP1;AL671277.1;KIFC2;C2orf16;CELF1;MECP2;MANSC1;CELF2-AS2;DNAJC9-AS1;AC079296.2;AC006064.4;TNPO2;HEG1;VRK3;LINC00884;ALDH7A1;AMOT;CEP170B;TRIP12;COL6A3;AC044849.1;HNRNPUL1;IQSEC2;RAG2;Y_RNA;RBM10;L3MBTL4-AS1;GAN;FAHD2CP;LINC01943;RBPJ;AL671883.2;KXD1;AC005841.1;FAM210B;RLIMP2;CEP250-AS1;AL109936.9;RHBDF2;ZBTB20-AS5;AC015921.1;MTR;FCF1P8;MIAT;EEF1A1P6;GRIPAP1;AL592430.1;TOP2A;ULK4;AC109361.2;PRAG1;DRAIC;AC007787.1;PPIAP90;AF131216.4;AC135279.3;AF230666.1;RPS27AP7;SAP30BP;FBLN1;CLMAT3;DDX18P5;SRF;RSL1D1;SOX5-AS1;AC008494.3;BMP2KL;NCL;AC021424.4;SLC25A39P1;GAD1;SRGAP3-AS1;AC013437.1;SATB1;AL356019.1;PRSS51;MED13L;KIF1A;AC012150.2;EEF1B2P1;CEP72;COASY;AL445523.1;TGFBI;OSBPL3;AL450003.1;MED12L;AC068580.3;GCSAM;IVD;MICAL2;MFF-DT;KIF14;AP000311.1;AC019270.1;AC097634.2;BTBD9-AS1;HCG20;FOXP1;HIGD1AP17;PCED1B-AS1;AC073358.1;AL355075.6;AC020661.3;MYO1C;CBX5;AL451085.2;VIM-AS1;ZBTB20-AS2;PCGF5;CPPED1;AC006059.1;DOCK2;UGGT1;ANKS6;AP002961.1;AL136146.1;TENM4;NECTIN2;PIAS2;EFCAB14;RPL10P16;REPIN1;ZNF4

In [87]:
df_lfc_ori.columns

Index(['geneid', 'log2FoldChange', 'lfcSE', 'AveExpr', 'stat', 'pvalue', 'adj_pvalue', 'B',
       'symbol', 'biotype'],
      dtype='object')

In [ ]:
method='deseq2'
force=True
verbose=True

df_lfc, df_lfc_ori, degs_txt, msg = gdc.calc_degs(
                                        prog_id = PROG_ID, 
                                        psi_id = PSI_ID,
                                        ncluster = nclu,
                                        df_tumor = dfn_combat_tum,
                                        df_normal = dfn_combat_norm, 
                                        df_gtex_ctrl = pd.DataFrame(),
                                        root_lfc= gdc.root_mprog_lfc,
                                        root_src = gdc.root_src,
                                        run_conda = True,
                                        lfc_cutoff = 1.0,
                                        fdr_cutoff = 0.05,
                                        method = method,
                                        force = force,
                                        verbose = verbose,
                                        )

In [ ]:
df_lfc