In [1]:
!python --version

Python 3.11.14

## GDC

https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/

sample  
 ├── primary_site       (organ)  
 ├── disease_type       (broad class)  
 ├── subtype_global     (cross-cancer)  
 ├── subtype_tissue     (within-cancer)  
 └── histology          (biological family)

### TCGA / GDC Portal

https://portal.gdc.cancer.gov/

### 🧠 Big picture (this is powerful)

- You’ve essentially built the backbone of:
- cBioPortal-like explorer
- cohort stratification engine
- patient-specific pipeline (your perturbation_agent 🔥)

### 💡 Flow

> project → project_id  
> primary_sites → pid and disease_type  
> subtypes → subtype_id  
> stages →  stage_id  
> case_id → case_ids or UUIDs  
> samples → sample_id [tumor, normal]  
> aliquots → aliquot_id  
> files → file_id

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### 👉 a TCGA cohort builder + data retrieval engine

Which means you can easily extend to:


> pan-cancer analyses  
> patient-specific pipelines (your perturb_agent 🔥)  
> automated workflows (Nextflow-ready)  

#### 🚀 Next steps

> Production pipeline  
  - CLI tool
  - cached queries
  - reproducible outputs

> Expression matrix builder  
  - auto-download
  - merge TSVs
  - DESeq2-ready matrix

> Patient-level analysis
  - per-case DEG
  - pathway perturbation scoring

### Defaults

In [3]:
ROOT = Path().resolve().parent
root_data = os.path.join(ROOT, "data/tcga")

gdc = GDC(root_data=root_data)

os.listdir(root_data)

['subtype_for_TCGA-KIRC.tsv',
 'cases_for_TCGA-LUSC.tsv',
 'subtype_for_TCGA-HNSC.tsv',
 'cases_for_TCGA-PCPG.tsv',
 'cases_for_TCGA-THYM.tsv',
 'cases_for_TCGA-PAAD.tsv',
 'cases_for_TCGA-LAML.tsv',
 'cases_for_TCGA-LIHC.tsv',
 'subtype_for_TCGA-KIRP.tsv',
 'subtype_for_TCGA-CHOL.tsv',
 'cases_for_TCGA-MESO.tsv',
 'cases_for_TCGA-BLCA.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_157ec9e0-ca6e-4da1-9233-f976cf0db433_sample_type_Primary_Tumor_stage_Stage_IV_fileid_a127fb1e-aa3b-4b6d-98b5-c141ffba9ae7.tsv',
 'cases_for_TCGA-KIRP.tsv',
 'cases_for_TCGA-LGG.tsv',
 'cases_for_TCGA-ESCA.tsv',
 'cases_for_TCGA-GBM.tsv',
 'subtype_for_TCGA-ACC.tsv',
 'cases_for_TCGA-TGCT.tsv',
 'subtype_for_TCGA-MESO.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_1783cac1-253a-40af-a9ac-48dfb20e1ab8_sample_type_Primary_Tumor_stage_Stage_IV_fileid_451ecdf8-433f-4d38-8ab6-3cc8d428ed95.tsv',
 'subtype_for_TCGA-OV.tsv',
 'cases_for_TCGA-UCEC.tsv',
 'cases_for_TCGA-HNSC.tsv',
 'subtype_for_TCGA-THYM.tsv',
 'cases_for_TCGA-COAD.tsv',
 'cases_for_TCGA-BRCA.tsv',
 'subtype_for_TCGA-READ.tsv',
 'subtype_for_TCGA-PAAD.tsv',
 'subtype_for_TCGA-CESC.tsv',
 'cases_for_TCGA-READ.tsv',
 'cases_for_TCGA-DLBC.tsv',
 'subtype_for_TCGA-PCPG.tsv',
 'programs.txt',
 'subtype_for_TCGA-SKCM.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_128d198e-9b22-427c-90db-3714455f3a17_sample_type_Primary_Tumor_stage_Stage_IV_fileid_54600389-6de5-44ce-ada1-8a8508b50980.tsv',
 'primary_site_program_HCMI.tsv',
 'samples_for_TCGA-BRCA_other_other_other_Stage_IV.tsv',
 'subtype_for_TCGA-PRAD.tsv',
 'subtype_for_TCGA-LUAD.tsv',
 'subtype_for_TCGA-LAML.tsv',
 'subtype_for_TCGA-THCA.tsv',
 'primary_site_program_TCGA.tsv',
 'cases_for_TCGA-CHOL.tsv',
 'subtype_for_TCGA-TGCT.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_01263518-5f7c-49dc-8d7e-84b0c03a6a63_sample_type_Primary_Tumor_stage_Stage_IV_fileid_aa89d193-05a1-4f7f-9291-b9cf646656de.tsv',
 'subtype_for_TCGA-STAD.tsv',
 'cases_for_TCGA-THCA.tsv',
 'cases_for_TCGA-KICH.tsv',
 'subtype_for_TCGA-DLBC.tsv',
 'cases_for_TCGA-ACC.tsv',
 'subtype_for_TCGA-UVM.tsv',
 'subtype_for_TCGA-LUSC.tsv',
 'cases_for_TCGA-LUAD.tsv',
 'cases_for_TCGA-STAD.tsv',
 'subtype_for_TCGA-BRCA.tsv',
 'subtype_for_TCGA-UCEC.tsv',
 'cases_for_TCGA-SARC.tsv',
 'cases_for_TCGA-UCS.tsv',
 'cases_for_TCGA-KIRC.tsv',
 'cases_for_TCGA-SKCM.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_32bc7cc4-d185-4594-bbee-4b96410be512_sample_type_Primary_Tumor_stage_Stage_IV_fileid_8603da6b-3bb9-4fff-b409-c5af2afd53b3.tsv',
 'subtype_for_TCGA-SARC.tsv',
 'subtype_for_TCGA-LIHC.tsv',
 'Protein_Expression_Quantification_for_TCGA-BRCA_case_32bc7cc4-d185-4594-bbee-4b96410be512_sample_type_Primary_Tumor_stage_Stage_IV_fileid_a2db9935-0427-49f1-97c0-41db6d012889.tsv',
 'subtype_for_TCGA-KICH.tsv',
 'subtype_for_TCGA-UCS.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_1783cac1-253a-40af-a9ac-48dfb20e1ab8_sample_type_Solid_Tissue_Normal_stage_Stage_IV_fileid_9985bb0b-d1cc-455b-80d9-f8007669cd5c.tsv',
 'subtype_for_TCGA-ESCA.tsv',
 'subtype_for_TCGA-GBM.tsv',
 'cases_for_TCGA-CESC.tsv',
 'subtype_for_TCGA-COAD.tsv',
 'subtype_for_TCGA-BLCA.tsv',
 'primary_site_program_FM.tsv',
 'cases_for_TCGA-UVM.tsv',
 'subtype_for_TCGA-LGG.tsv',
 'cases_for_TCGA-OV.tsv',
 'cases_for_TCGA-PRAD.tsv']

### Methods

#### Get GDC programs - get_gdc_progams()

> end_point: url_gdc_project = "https://api.gdc.cancer.gov/projects"  
> "facets": "program.name"  

#### Get valid primary sites - get_primary_sites()

> end_point: url_gdc_project = "https://api.gdc.cancer.gov/projects"  
> "fields": "project_id,name,primary_site,disease_type"  

#### Get valid subtypes - get_subtypes()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> facets = "diagnoses.primary_diagnosis"  

#### For each subtype → get stages  - get_stages()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> "field": "diagnoses.ajcc_pathologic_stage" - AJCC diagnoses   

#### For each (subtype, stage) → get_samples()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> given pid, subtype, stage  
> from cases   
> "samples.sample_id", "samples.submitter_id", "samples.sample_type"  

#### get RNA-seq files - get_expression_files_given_samples()

> given: "field": "cases.case_id", "value": case_ids  
> end_point: url_gdc_files = "https://api.gdc.cancer.gov/files"

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/tcga/programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=True

program = 'TCGA'

dfc = gdc.get_primary_sites(program=program, force=force, verbose=verbose)

print(len(dfc))
dfc.head(12)

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/tcga/primary_site_program_TCGA.tsv'
33

,pid,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma
3,TCGA-LGG,Brain,TCGA-LGG,Gliomas,Brain Lower Grade Glioma
4,TCGA-GBM,Brain,TCGA-GBM,"Not Reported, Gliomas",Glioblastoma Multiforme
5,TCGA-BRCA,Breast,TCGA-BRCA,"Adnexal and Skin Appendage Neoplasms, Adenomas...",Breast Invasive Carcinoma
6,TCGA-LUAD,Bronchus and lung,TCGA-LUAD,"Ductal and Lobular Neoplasms, Cystic, Mucinous...",Lung Adenocarcinoma
7,TCGA-LUSC,Bronchus and lung,TCGA-LUSC,"Squamous Cell Neoplasms, Adenomas and Adenocar...",Lung Squamous Cell Carcinoma
8,TCGA-MESO,"Bronchus and lung, Heart, mediastinum, and pleura",TCGA-MESO,Mesothelial Neoplasms,Mesothelioma
9,TCGA-CESC,"Cervix uteri, Ovary",TCGA-CESC,"Squamous Cell Neoplasms, Cystic, Mucinous and ...",Cervical Squamous Cell Carcinoma and Endocervi...
10,TCGA-COAD,"Colon, Rectosigmoid junction",TCGA-COAD,"Cystic, Mucinous and Serous Neoplasms, Complex...",Colon Adenocarcinoma
11,TCGA-READ,"Colon, Rectosigmoid junction, Rectum, Connecti...",TCGA-READ,"Cystic, Mucinous and Serous Neoplasms, Adenoma...",Rectum Adenocarcinoma

In [8]:
dfc.tail(3)

,pid,primary_site,project_id,disease_type,name
30,TCGA-THCA,Thyroid gland,TCGA-THCA,"Squamous Cell Neoplasms, Epithelial Neoplasms,...",Thyroid Carcinoma
31,TCGA-UCS,"Uterus, NOS, Corpus uteri",TCGA-UCS,"Basal Cell Neoplasms, Complex Mixed and Stroma...",Uterine Carcinosarcoma
32,TCGA-UCEC,"Uterus, NOS, Corpus uteri",TCGA-UCEC,"Not Reported, Cystic, Mucinous and Serous Neop...",Uterine Corpus Endometrial Carcinoma

### Subtypes explanation

👉 GDC does NOT give you clean biological subtypes
👉 You must derive them yourself

This is actually a feature, not a bug — because:

> you control granularity  
> you can harmonize across cancers  
> you avoid noisy labels  


💡 If you want to level this up

I can help you build:

🔬 A cross-TCGA subtype harmonizer
maps all projects → unified subtype ontology
handles synonyms (adenocarcinoma, NOS, etc.)
outputs clean ML-ready labels

👉 That would massively improve your perturbation analysis.

In [9]:
i = 5
pid = dfc.iloc[i].pid
primary_site = dfc.iloc[i].primary_site

print(i, pid, primary_site)

5 TCGA-BRCA Breast

- Brain tumors do NOT use AJCC staging (3 - TCGA-LGG Brain)

In [10]:
force=False
verbose=True

i = 5
pid = dfc.iloc[i].pid
primary_site = dfc.iloc[i].primary_site

print(i, pid, primary_site)

df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

print("df_cases", len(df_cases), "df_subt", len(df_subt))
df_subt

5 TCGA-BRCA Breast
Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-BRCA.tsv'
df_cases 1098 df_subt 12

,pid,subtype_global,tumor_class,subtype_tissue,sstage,n
0,TCGA-BRCA,other,other,other,II,447
1,TCGA-BRCA,lobular,other,breast_lobular,missing,223
2,TCGA-BRCA,other,other,other,III,154
3,TCGA-BRCA,other,other,other,I,141
4,TCGA-BRCA,other,other,other,missing,85
5,TCGA-BRCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,missing,19
6,TCGA-BRCA,other,other,other,IV,16
7,TCGA-BRCA,ductal,adenocarcinoma,breast_ductal,missing,6
8,TCGA-BRCA,ductal,other,breast_ductal,II,2
9,TCGA-BRCA,clear_cell,other,clear_cell,II,2
10,TCGA-BRCA,ductal,other,breast_ductal,missing,2
11,TCGA-BRCA,neuroendocrine,neuroendocrine_tumor,neuroendocrine,missing,1

In [11]:
cols = ["pid", "case_id", "subtype_global", "tumor_class", "subtype_tissue", "stage"]

df_cases[cols].head(12)

,pid,case_id,subtype_global,tumor_class,subtype_tissue,stage
0,TCGA-BRCA,e3935ce4-64d3-4a66-ba11-d308b844b410,other,other,other,unknown
1,TCGA-BRCA,e3b555aa-7f0a-49c6-9b13-182c61a144c1,other,other,other,Stage IIIA
2,TCGA-BRCA,17ca61a2-607a-45ff-88fa-ef72e80bf891,other,other,other,Stage IA
3,TCGA-BRCA,7d681cc6-689d-41c8-9e84-e13733089ec9,other,other,other,Stage IIB
4,TCGA-BRCA,17f275c1-a0d4-487d-8f02-ea279584b4cd,other,other,other,Stage IA
5,TCGA-BRCA,189e1f27-7738-413a-a4d4-97d41d592a13,other,other,other,Stage IIA
6,TCGA-BRCA,95c53ecf-d8f1-4bcb-9b1a-c9a0542939f0,other,other,other,Stage IA
7,TCGA-BRCA,c0f88fc5-56b0-4255-bbd1-9a21ced8b37b,other,other,other,Stage IIIA
8,TCGA-BRCA,0f64edec-0f1f-4025-8a53-75f9534f7828,other,other,other,Stage IIA
9,TCGA-BRCA,c25898b4-eb33-42f4-bf3f-bf532a929e7d,lobular,other,breast_lobular,unknown
10,TCGA-BRCA,195b6731-6ae6-416e-a345-0eb8874a0ca2,other,other,other,Stage IIIA
11,TCGA-BRCA,7f97971b-2818-4e4b-9c9e-7c0246f9484c,other,other,other,Stage IIB

### Get all cases and their classifications

In [12]:

force=False
verbose=True

run_all = False

if run_all:

    for i in range(len(dfc)):
        print(i, end=' ')
        pid = dfc.iloc[i].pid
        primary_site = dfc.iloc[i].primary_site

        print(pid, primary_site)

        df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

### Search for samples and files for each case given

- input: pid, subtype_global, tumor_class, subtype_tissue, and stage

In [13]:
force=False
verbose=True

i = 5
pid = dfc.iloc[i].pid
primary_site = dfc.iloc[i].primary_site

print(i, pid, primary_site)

df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)
df_subt

5 TCGA-BRCA Breast
Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-BRCA.tsv'

,pid,subtype_global,tumor_class,subtype_tissue,sstage,n
0,TCGA-BRCA,other,other,other,II,447
1,TCGA-BRCA,lobular,other,breast_lobular,missing,223
2,TCGA-BRCA,other,other,other,III,154
3,TCGA-BRCA,other,other,other,I,141
4,TCGA-BRCA,other,other,other,missing,85
5,TCGA-BRCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,missing,19
6,TCGA-BRCA,other,other,other,IV,16
7,TCGA-BRCA,ductal,adenocarcinoma,breast_ductal,missing,6
8,TCGA-BRCA,ductal,other,breast_ductal,II,2
9,TCGA-BRCA,clear_cell,other,clear_cell,II,2
10,TCGA-BRCA,ductal,other,breast_ductal,missing,2
11,TCGA-BRCA,neuroendocrine,neuroendocrine_tumor,neuroendocrine,missing,1

In [14]:
i = 6
df_subt.iloc[i]

pid               TCGA-BRCA
subtype_global        other
tumor_class           other
subtype_tissue        other
sstage                   IV
n                        16
Name: 6, dtype: object

In [15]:
force=False
verbose=True

i = 6
row = df_subt.iloc[i]

pid = row.pid
subtype_global = row.subtype_global
tumor_class = row.tumor_class
subtype_tissue = row.subtype_tissue
sstage = row.sstage

s_case = f"{pid} subtype '{subtype_global}' tumor '{tumor_class}' subtype_tissue '{subtype_tissue}' stage '{sstage}'"
print(s_case)

df_sample = gdc.get_samples_for_pid_subtypes(pid=pid, subtype_global=subtype_global,
                                             tumor_class=tumor_class, subtype_tissue=subtype_tissue,
                                             sstage=sstage, batch_size=200,
                                             force=force, verbose=verbose)

print(len(df_sample))

df_sample.head(3)

TCGA-BRCA subtype 'other' tumor 'other' subtype_tissue 'other' stage 'IV'
Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-BRCA.tsv'
Table opened ((445, 11)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_other_other_other_Stage_IV.tsv'
445

,case_id,sample_id,sample_type,file_id,file_name,data_type,pid,subtype_global,tumor_class,subtype_tissue,stage
0,32bc7cc4-d185-4594-bbee-4b96410be512,4ab5f84d-7ba2-49e2-862b-48ff8cff3c34,Primary Tumor,a2db9935-0427-49f1-97c0-41db6d012889,TCGA-A8-A08T-01A-11-A13A-20_RPPA_data.tsv,Protein Expression Quantification,TCGA-BRCA,other,other,other,Stage IV
1,32bc7cc4-d185-4594-bbee-4b96410be512,4ab5f84d-7ba2-49e2-862b-48ff8cff3c34,Primary Tumor,6b2fc2ac-a4b4-4e33-9ecc-8f3f98d4e33e,TCGA-BRCA.dfe66ee6-0535-42b6-b6b1-b961604d8a27...,Allele-specific Copy Number Segment,TCGA-BRCA,other,other,other,Stage IV
2,32bc7cc4-d185-4594-bbee-4b96410be512,4ab5f84d-7ba2-49e2-862b-48ff8cff3c34,Primary Tumor,125aede6-ea2e-4f2d-a8f1-31b9ec3464dd,TCGA_BRCA.ed76da0d-850e-4017-8bd4-f2e9e90d27f1...,Annotated Somatic Mutation,TCGA-BRCA,other,other,other,Stage IV

In [16]:
dfu = gdc.group_file_types(df_sample)
dfu

                              data_type   n
0            Annotated Somatic Mutation  92
1           Raw Simple Somatic Mutation  64
2                         Aligned Reads  42
3              Structural Rearrangement  32
4                     Transcript Fusion  24
5                Gene Level Copy Number  24
6   Allele-specific Copy Number Segment  20
7                           Slide Image  19
8                   Copy Number Segment  18
9                    Masked Intensities  12
10                      Raw Intensities  10
11          Aggregated Somatic Mutation  10
12              Masked Somatic Mutation  10
13            Simple Germline Variation  10
14           Masked Copy Number Segment  10
15        Intermediate Analysis Archive   8
16       Gene Expression Quantification   6
17       Splice Junction Quantification   6
18               Methylation Beta Value   6
19      miRNA Expression Quantification   6
20    Isoform Expression Quantification   6
21    Protein Expression Quantification   5
22                     Pathology Report   5

In [17]:
lista = list(dfu.data_type)
lista.sort()

"; ".join(lista)

'Aggregated Somatic Mutation; Aligned Reads; Allele-specific Copy Number Segment; Annotated Somatic Mutation; Copy Number Segment; Gene Expression Quantification; Gene Level Copy Number; Intermediate Analysis Archive; Isoform Expression Quantification; Masked Copy Number Segment; Masked Intensities; Masked Somatic Mutation; Methylation Beta Value; Pathology Report; Protein Expression Quantification; Raw Intensities; Raw Simple Somatic Mutation; Simple Germline Variation; Slide Image; Splice Junction Quantification; Structural Rearrangement; Transcript Fusion; miRNA Expression Quantification'

### Get Any table (for tumor and control)

In [18]:
force=False
verbose=True

i=0
row = df_sample.iloc[i]

pid = row.pid
case_id = row.case_id
file_type = row.data_type
file_id = row.file_id
sample_type = row.sample_type
stage = row.stage


print(f"{pid}, {case_id}, {file_type}, {file_id}")

dft = gdc.get_table_given_fileID(pid=pid, case_id=case_id, 
                                 file_type=file_type, sample_type=sample_type, stage=stage, file_id=file_id, 
                                 force=force, verbose=verbose)
print(len(dft))
dft.head(6)

TCGA-BRCA, 32bc7cc4-d185-4594-bbee-4b96410be512, Protein Expression Quantification, a2db9935-0427-49f1-97c0-41db6d012889
Table opened ((487, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/Protein_Expression_Quantification_for_TCGA-BRCA_case_32bc7cc4-d185-4594-bbee-4b96410be512_sample_type_Primary_Tumor_stage_Stage_IV_fileid_a2db9935-0427-49f1-97c0-41db6d012889.tsv'
487

        AGID  lab_id catalog_number set_id peptide_target  protein_expression
0  AGID00100     882         sc-628    Old       1433BETA           -0.018320
1  AGID00111     913       sc-23957    Old    1433EPSILON           -0.036071
2  AGID00101     883        sc-1019    Old       1433ZETA            0.387080
3  AGID00001       2           9452    Old          4EBP1            0.016983
4  AGID00002       3           9456    Old     4EBP1_pS65           -0.604880
5  AGID00003       6           9459    Old  4EBP1_pT37T46            0.056122

### Get Expression table (for tumor and control)

#### 🧪 Mental model (important)

| Step	|  Needs strand? | Output | Column |
|---------|---------|---------|---------|
| Read assignment	|  YES |  counts | stranded_first |
| Normalization	| NO | TPM / FPKM | both: unstranded |
| Biological meaning | NO | gene expression| both: unstranded |

In [19]:
file_type = 'Gene Expression Quantification'

force=False
verbose=False

dft = pd.DataFrame()

df2 = df_sample[df_sample.data_type == file_type]

for i, row in df2.iterrows():
    pid = row.pid
    case_id = row.case_id
    file_type = row.data_type
    file_id = row.file_id
    sample_type = row.sample_type
    stage = row.stage

    print(f"{i}) {pid}, {case_id}, {file_type}, {file_id}")

    dft = gdc.get_table_given_fileID(pid=pid, case_id=case_id, 
                                     sample_type=sample_type, stage=stage, 
                                     file_type=file_type, file_id=file_id, 
                                     force=force, verbose=verbose)


dft.head(6)

8) TCGA-BRCA, 32bc7cc4-d185-4594-bbee-4b96410be512, Gene Expression Quantification, 8603da6b-3bb9-4fff-b409-c5af2afd53b3
129) TCGA-BRCA, 1783cac1-253a-40af-a9ac-48dfb20e1ab8, Gene Expression Quantification, 9985bb0b-d1cc-455b-80d9-f8007669cd5c
175) TCGA-BRCA, 1783cac1-253a-40af-a9ac-48dfb20e1ab8, Gene Expression Quantification, 451ecdf8-433f-4d38-8ab6-3cc8d428ed95
186) TCGA-BRCA, 157ec9e0-ca6e-4da1-9233-f976cf0db433, Gene Expression Quantification, a127fb1e-aa3b-4b6d-98b5-c141ffba9ae7
316) TCGA-BRCA, 128d198e-9b22-427c-90db-3714455f3a17, Gene Expression Quantification, 54600389-6de5-44ce-ada1-8a8508b50980
357) TCGA-BRCA, 01263518-5f7c-49dc-8d7e-84b0c03a6a63, Gene Expression Quantification, aa89d193-05a1-4f7f-9291-b9cf646656de

,gene_id,symbol,gene_type,unstranded,counts,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,ENSG00000000003,TSPAN6,protein_coding,911,446,465,12.8633,3.2599,3.1661
1,ENSG00000000005,TNMD,protein_coding,22,12,10,0.9547,0.2419,0.2350
2,ENSG00000000419,DPM1,protein_coding,4349,2189,2160,230.7761,58.4850,56.8023
3,ENSG00000000457,SCYL3,protein_coding,1420,1109,1155,13.2135,3.3487,3.2523
4,ENSG00000000460,C1orf112,protein_coding,1197,1075,1036,12.8419,3.2545,3.1608
5,ENSG00000000938,FGR,protein_coding,679,366,313,12.8589,3.2588,3.1650

In [20]:
np.unique(df_sample.data_type)

array(['Aggregated Somatic Mutation', 'Aligned Reads',
       'Allele-specific Copy Number Segment',
       'Annotated Somatic Mutation', 'Copy Number Segment',
       'Gene Expression Quantification', 'Gene Level Copy Number',
       'Intermediate Analysis Archive',
       'Isoform Expression Quantification', 'Masked Copy Number Segment',
       'Masked Intensities', 'Masked Somatic Mutation',
       'Methylation Beta Value', 'Pathology Report',
       'Protein Expression Quantification', 'Raw Intensities',
       'Raw Simple Somatic Mutation', 'Simple Germline Variation',
       'Slide Image', 'Splice Junction Quantification',
       'Structural Rearrangement', 'Transcript Fusion',
       'miRNA Expression Quantification'], dtype=object)

In [21]:
df_sample.columns

Index(['case_id', 'sample_id', 'sample_type', 'file_id', 'file_name',
       'data_type', 'pid', 'subtype_global', 'tumor_class', 'subtype_tissue',
       'stage'],
      dtype='str')

### Get Normal and Tumor datasets given case_id and data_type

In [22]:
case_id = '1783cac1-253a-40af-a9ac-48dfb20e1ab8'
data_type = 'Gene Expression Quantification'

df_normal, df_tumor = gdc.get_tumor_normal_tables(df_sample=df_sample, case_id=case_id, data_type=data_type)

len(df_normal), len(df_tumor)

(1, 5)

In [23]:
df_normal

,file_id,data_type,sample_type
0,9985bb0b-d1cc-455b-80d9-f8007669cd5c,Gene Expression Quantification,Solid Tissue Normal

In [24]:
df_tumor

,file_id,data_type,sample_type
0,8603da6b-3bb9-4fff-b409-c5af2afd53b3,Gene Expression Quantification,Primary Tumor
1,451ecdf8-433f-4d38-8ab6-3cc8d428ed95,Gene Expression Quantification,Primary Tumor
2,a127fb1e-aa3b-4b6d-98b5-c141ffba9ae7,Gene Expression Quantification,Primary Tumor
3,54600389-6de5-44ce-ada1-8a8508b50980,Gene Expression Quantification,Primary Tumor
4,aa89d193-05a1-4f7f-9291-b9cf646656de,Gene Expression Quantification,Primary Tumor

### Merge Expression Tables for DEGs' calculation

In [25]:
dfa_normal, dfa_tumor = gdc.merge_normal_tumor_tables(pid=pid, df_normal=df_normal, df_tumor=df_tumor)

dfa_normal.shape, dfa_tumor.shape

((60660, 4), (61980, 8))

In [26]:
dfa_normal.head(3)

           gene_id  symbol       gene_type  counts_1
0  ENSG00000000003  TSPAN6  protein_coding      1511
1  ENSG00000000005    TNMD  protein_coding       167
2  ENSG00000000419    DPM1  protein_coding       948

In [27]:
dfa_tumor.head(3)

,gene_id,symbol,gene_type,counts_1,counts_2,counts_3,counts_4,counts_5
0,ENSG00000000003,TSPAN6,protein_coding,1714,2222,910,1335,446
1,ENSG00000000005,TNMD,protein_coding,3,32,6,0,12
2,ENSG00000000419,DPM1,protein_coding,847,1045,917,1584,2189

In [28]:
i=100
dfa_tumor.iloc[i:i+30]

,gene_id,symbol,gene_type,counts_1,counts_2,counts_3,counts_4,counts_5
100,ENSG00000004948,CALCR,protein_coding,17,26,27,2,22
101,ENSG00000004961,HCCS,protein_coding,567,651,878,1188,1667
102,ENSG00000004975,DVL2,protein_coding,1354,1126,1897,675,1140
103,ENSG00000005001,PRSS22,protein_coding,199,242,399,1512,249
104,ENSG00000005007,UPF1,protein_coding,4541,4820,4021,2262,5298
105,ENSG00000005020,SKAP2,protein_coding,464,2499,1797,1068,992
106,ENSG00000005022,SLC25A5,protein_coding,5092,5346,9037,4825,9933
107,ENSG00000005059,MCUB,protein_coding,1052,510,343,342,307
108,ENSG00000005073,HOXA11,protein_coding,38,30,15,4,32
109,ENSG00000005075,POLR2J,protein_coding,602,675,2673,1319,1136
110,ENSG00000005100,DHX33,protein_coding,1142,952,902,385,927
111,ENSG00000005102,MEOX1,protein_coding,42,957,96,5,15
112,ENSG00000005108,THSD7A,protein_coding,154,916,75,46,76
113,ENSG00000005156,LIG3,protein_coding,3165,2430,3403,1679,3131
114,ENSG00000005175,RPAP3,protein_coding,1187,1213,870,579,1464
115,ENSG00000005187,ACSM3,protein_coding,753,442,319,433,236
116,ENSG00000005189,REXO5,protein_coding,334,143,682,198,464
117,ENSG00000005194,CIAPIN1,protein_coding,1055,1461,1341,1117,2335
118,ENSG00000005206,SPPL2B,protein_coding,1369,1230,1462,916,1351
119,ENSG00000005238,FAM214B,protein_coding,399,697,612,1682,519
120,ENSG00000005243,COPZ2,protein_coding,359,1202,823,412,455
121,ENSG00000005249,PRKAR2B,protein_coding,2091,1386,2312,130,1603
122,ENSG00000005302,MSL3,protein_coding,715,994,841,1579,753
123,ENSG00000005339,CREBBP,protein_coding,7863,6009,4973,2791,6120
124,ENSG00000005379,TSPOAP1,protein_coding,1213,1422,299,168,303
125,ENSG00000005381,MPO,protein_coding,4,9,0,6,2
126,ENSG00000005421,PON1,protein_coding,5,8,3,3,0
127,ENSG00000005436,GCFC2,protein_coding,1454,1042,884,854,630
128,ENSG00000005448,WDR54,protein_coding,556,310,670,566,809
129,ENSG00000005469,CROT,protein_coding,969,989,1798,262,638

### Calc DEGs

In [29]:
cdegs = CALC_DEGS(root_data=root_data)

cdegs.libs_dir, cdegs.root_data

(PosixPath('/home/flavio/uv/perturb_agent/src/libs'),
 PosixPath('/home/flavio/uv/perturb_agent/data/tcga'))

In [30]:
dfa_normal2 = cdegs.deduplicate_by_max_reads(dfa_normal)
len(dfa_normal2), len(dfa_normal)

(60616, 60660)

In [31]:
dfa_tumor2 = cdegs.deduplicate_by_max_reads(dfa_tumor)
len(dfa_tumor2), len(dfa_tumor)

(60616, 61980)

In [32]:
df_lfc = cdegs.run_deg_rscript(df_tumor=dfa_tumor2, df_normal=dfa_normal2,
                                method="edger",  manual_dispersion=0.1, min_total_count=10, 
                                merge_how="inner", keep_temp=False)
print(len(df_lfc))

25250

In [35]:
df_lfc = df_lfc.rename(columns={"log2FoldChange": "lfc", "padj": "fdr"})
df_lfc.head(3)

,gene_id,symbol,gene_type,lfc,logCPM,statistic,pvalue,fdr,method
0,ENSG00000137440,FGFBP1,protein_coding,-9.185835,2.257341,NaN,9.425175e-67,1.704767e-62,edgeR_exact_manualDisp_0.1
1,ENSG00000244734,HBB,protein_coding,-7.403060,6.420277,NaN,1.350310e-66,1.704767e-62,edgeR_exact_manualDisp_0.1
2,ENSG00000188536,HBA2,protein_coding,-7.298696,3.683474,NaN,1.113013e-60,9.367861e-57,edgeR_exact_manualDisp_0.1

In [36]:
lfc_cutoff = 1.0
fdr_cutoff = .05

df_degs = df_lfc[ (df_lfc.lfc >= lfc_cutoff) & (df_lfc.fdr < fdr_cutoff)].copy()
print(len(df_degs))

df_degs.head(30)

2365

,gene_id,symbol,gene_type,lfc,logCPM,statistic,pvalue,fdr,method
51,ENSG00000141668,CBLN2,protein_coding,12.118940,7.425111,NaN,1.871379e-26,9.086985e-24,edgeR_exact_manualDisp_0.1
85,ENSG00000147381,MAGEA4,protein_coding,14.202259,5.905617,NaN,1.119542e-22,3.287028e-20,edgeR_exact_manualDisp_0.1
96,ENSG00000123500,COL10A1,protein_coding,8.568603,7.461871,NaN,4.308427e-21,1.121523e-18,edgeR_exact_manualDisp_0.1
104,ENSG00000170419,VSTM2A,protein_coding,13.547065,5.254319,NaN,1.024209e-20,2.462980e-18,edgeR_exact_manualDisp_0.1
109,ENSG00000105141,CASP14,protein_coding,9.514498,5.759617,NaN,2.758795e-20,6.332688e-18,edgeR_exact_manualDisp_0.1
114,ENSG00000105388,CEACAM5,protein_coding,9.018059,5.831233,NaN,5.199101e-20,1.141542e-17,edgeR_exact_manualDisp_0.1
116,ENSG00000105048,TNNT1,protein_coding,8.719954,5.935822,NaN,6.613162e-20,1.427199e-17,edgeR_exact_manualDisp_0.1
117,ENSG00000060718,COL11A1,protein_coding,8.084070,7.275420,NaN,7.168558e-20,1.533950e-17,edgeR_exact_manualDisp_0.1
135,ENSG00000170373,CST1,protein_coding,12.908342,4.618917,NaN,8.208498e-19,1.515591e-16,edgeR_exact_manualDisp_0.1
139,ENSG00000117148,ACTL8,protein_coding,12.845358,4.548618,NaN,1.245940e-18,2.247143e-16,edgeR_exact_manualDisp_0.1
140,ENSG00000122584,NXPH1,protein_coding,12.828129,4.540134,NaN,1.424885e-18,2.551655e-16,edgeR_exact_manualDisp_0.1
142,ENSG00000253802,SIRLNT,lncRNA,8.515100,5.328058,NaN,1.642936e-18,2.900989e-16,edgeR_exact_manualDisp_0.1
149,ENSG00000221867,MAGEA3,protein_coding,12.643299,4.350081,NaN,4.979226e-18,8.381697e-16,edgeR_exact_manualDisp_0.1
157,ENSG00000235123,DSCAM-AS1,lncRNA,9.187207,4.499325,NaN,1.100333e-17,1.758443e-15,edgeR_exact_manualDisp_0.1
161,ENSG00000234722,LINC01287,lncRNA,7.716401,5.508440,NaN,1.431080e-17,2.230542e-15,edgeR_exact_manualDisp_0.1
166,ENSG00000174469,CNTNAP2,protein_coding,8.555701,4.805763,NaN,1.990911e-17,3.010210e-15,edgeR_exact_manualDisp_0.1
177,ENSG00000204832,ST8SIA6-AS1,lncRNA,8.898764,4.209101,NaN,7.798662e-17,1.106271e-14,edgeR_exact_manualDisp_0.1
197,ENSG00000069011,PITX1,protein_coding,8.726596,4.037838,NaN,2.523241e-16,3.217770e-14,edgeR_exact_manualDisp_0.1
198,ENSG00000130294,KIF1A,protein_coding,12.061024,3.776228,NaN,2.643807e-16,3.354579e-14,edgeR_exact_manualDisp_0.1
206,ENSG00000143556,S100A7,protein_coding,7.412470,4.627089,NaN,5.076160e-16,6.191934e-14,edgeR_exact_manualDisp_0.1
209,ENSG00000211892,IGHG4,IG_C_gene,6.889194,5.547303,NaN,6.102658e-16,7.337720e-14,edgeR_exact_manualDisp_0.1
214,ENSG00000189001,SBSN,protein_coding,8.016065,4.261382,NaN,7.756070e-16,9.108872e-14,edgeR_exact_manualDisp_0.1
222,ENSG00000223808,AC044784.1,lncRNA,11.796375,3.519203,NaN,1.598289e-15,1.809722e-13,edgeR_exact_manualDisp_0.1
229,ENSG00000185686,PRAME,protein_coding,7.193191,4.414850,NaN,2.272087e-15,2.494356e-13,edgeR_exact_manualDisp_0.1
233,ENSG00000084628,NKAIN1,protein_coding,6.586998,5.484865,NaN,3.468292e-15,3.742494e-13,edgeR_exact_manualDisp_0.1
234,ENSG00000253877,LINC01608,lncRNA,11.676160,3.394818,NaN,3.539968e-15,3.803583e-13,edgeR_exact_manualDisp_0.1
236,ENSG00000137745,MMP13,protein_coding,7.781465,4.037530,NaN,3.874448e-15,4.127841e-13,edgeR_exact_manualDisp_0.1
239,ENSG00000197172,MAGEA6,protein_coding,11.645800,3.359247,NaN,4.304320e-15,4.528504e-13,edgeR_exact_manualDisp_0.1
252,ENSG00000075388,FGF4,protein_coding,11.522755,3.243046,NaN,9.957564e-15,9.937885e-13,edgeR_exact_manualDisp_0.1
253,ENSG00000203972,GLYATL3,protein_coding,11.512755,3.233149,NaN,1.062224e-14,1.055951e-12,edgeR_exact_manualDisp_0.1

In [ ]:
fname = 'degs.txt'

text = "\n".join(df_degs.gene_id)

write_txt(text, fname, root_data)

'ENSG00000141668, ENSG00000147381, ENSG00000123500, ENSG00000170419, ENSG00000105141, ENSG00000105388, ENSG00000105048, ENSG00000060718, ENSG00000170373, ENSG00000117148, ENSG00000122584, ENSG00000253802, ENSG00000221867, ENSG00000235123, ENSG00000234722, ENSG00000174469, ENSG00000204832, ENSG00000069011, ENSG00000130294, ENSG00000143556, ENSG00000211892, ENSG00000189001, ENSG00000223808, ENSG00000185686, ENSG00000084628, ENSG00000253877, ENSG00000137745, ENSG00000197172, ENSG00000075388, ENSG00000203972, ENSG00000158639, ENSG00000198033, ENSG00000159184, ENSG00000156096, ENSG00000230838, ENSG00000107159, ENSG00000019505, ENSG00000104321, ENSG00000162482, ENSG00000105664, ENSG00000263639, ENSG00000204539, ENSG00000211452, ENSG00000046774, ENSG00000078898, ENSG00000166961, ENSG00000176566, ENSG00000249203, ENSG00000118785, ENSG00000196611, ENSG00000009709, ENSG00000070985, ENSG00000166509, ENSG00000123407, ENSG00000260318, ENSG00000135346, ENSG00000178372, ENSG00000256612, ENSG00000124935, ENSG00000137648, ENSG00000152977, ENSG00000179023, ENSG00000173809, ENSG00000164756, ENSG00000213214, ENSG00000286618, ENSG00000126010, ENSG00000114200, ENSG00000278828, ENSG00000249306, ENSG00000229314, ENSG00000099953, ENSG00000161634, ENSG00000203805, ENSG00000144355, ENSG00000123388, ENSG00000155495, ENSG00000130433, ENSG00000126752, ENSG00000101210, ENSG00000011677, ENSG00000250612, ENSG00000237442, ENSG00000274290, ENSG00000123364, ENSG00000184564, ENSG00000175946, ENSG00000230257, ENSG00000096006, ENSG00000187122, ENSG00000143194, ENSG00000228630, ENSG00000165078, ENSG00000184613, ENSG00000147689, ENSG00000282815, ENSG00000213401, ENSG00000176532, ENSG00000204792, ENSG00000273802, ENSG00000165309, ENSG00000163993, ENSG00000125999, ENSG00000197888, ENSG00000275713, ENSG00000185303, ENSG00000204540, ENSG00000171428, ENSG00000105143, ENSG00000162989, ENSG00000132329, ENSG00000226519, ENSG00000197977, ENSG00000101098, ENSG00000251141, ENSG00000154478, ENSG00000116329, ENSG00000029559, ENSG00000160182, ENSG00000228278, ENSG00000179059, ENSG00000104415, ENSG00000181449, ENSG00000174672, ENSG00000106541, ENSG00000198930, ENSG00000168209, ENSG00000174156, ENSG00000169469, ENSG00000104549, ENSG00000015413, ENSG00000244468, ENSG00000187621, ENSG00000286208, ENSG00000162975, ENSG00000146197, ENSG00000287914, ENSG00000165474, ENSG00000162670, ENSG00000269926, ENSG00000109265, ENSG00000183734, ENSG00000131650, ENSG00000244128, ENSG00000188211, ENSG00000223573, ENSG00000161905, ENSG00000277075, ENSG00000144045, ENSG00000117650, ENSG00000153132, ENSG00000286619, ENSG00000266200, ENSG00000106536, ENSG00000234068, ENSG00000110484, ENSG00000204710, ENSG00000180176, ENSG00000270816, ENSG00000281880, ENSG00000125820, ENSG00000173404, ENSG00000273301, ENSG00000224559, ENSG00000086548, ENSG00000125508, ENSG00000279694, ENSG00000158406, ENSG00000187837, ENSG00000285094, ENSG00000091831, ENSG00000164128, ENSG00000135773, ENSG00000197308, ENSG00000134824, ENSG00000197106, ENSG00000285637, ENSG00000100285, ENSG00000132821, ENSG00000178773, ENSG00000153002, ENSG00000138696, ENSG00000116014, ENSG00000166426, ENSG00000144485, ENSG00000260284, ENSG00000133110, ENSG00000054356, ENSG00000238269, ENSG00000244125, ENSG00000160161, ENSG00000124507, ENSG00000265766, ENSG00000283064, ENSG00000121270, ENSG00000148942, ENSG00000185640, ENSG00000277224, ENSG00000187486, ENSG00000251129, ENSG00000166851, ENSG00000117407, ENSG00000119547, ENSG00000105519, ENSG00000211935, ENSG00000207422, ENSG00000138829, ENSG00000101057, ENSG00000174963, ENSG00000204140, ENSG00000230483, ENSG00000267978, ENSG00000203635, ENSG00000233913, ENSG00000165731, ENSG00000259439, ENSG00000131096, ENSG00000105219, ENSG00000196747, ENSG00000173702, ENSG00000158373, ENSG00000254497, ENSG00000057593, ENSG00000230076, ENSG00000138316, ENSG00000262920, ENSG00000282988, ENSG00000116147, ENSG00000204385, ENSG00000178934, ENSG00000205420, ENSG00000125813, ENSG00000241361, ENSG00000115414, ENSG00000103888, ENSG00000100362, ENSG00000230061, ENSG00000211896, ENSG00000162849, ENSG00000216331, ENSG00000287566, ENSG00000148848, ENSG00000108231, ENSG00000287226, ENSG00000103260, ENSG00000104899, ENSG00000175985, ENSG00000175315, ENSG00000152592, ENSG00000127129, ENSG00000174945, ENSG00000148773, ENSG00000183010, ENSG00000099812, ENSG00000124493, ENSG00000184330, ENSG00000223764, ENSG00000258197, ENSG00000261787, ENSG00000128165, ENSG00000183856, ENSG00000088325, ENSG00000149243, ENSG00000228613, ENSG00000229967, ENSG00000168702, ENSG00000139352, ENSG00000235049, ENSG00000233078, ENSG00000255501, ENSG00000156234, ENSG00000067715, ENSG00000166840, ENSG00000184956, ENSG00000102313, ENSG00000180777, ENSG00000100985, ENSG00000182379, ENSG00000079841, ENSG00000169347, ENSG00000232638, ENSG00000180818, ENSG00000125869, ENSG00000185352, ENSG00000136928, ENSG00000260597, ENSG00000159263, ENSG00000118193, ENSG00000286015, ENSG00000118160, ENSG00000204044, ENSG00000188133, ENSG00000256618, ENSG00000152463, ENSG00000169783, ENSG00000244137, ENSG00000117152, ENSG00000171759, ENSG00000251151, ENSG00000261266, ENSG00000205592, ENSG00000249661, ENSG00000157766, ENSG00000170369, ENSG00000178821, ENSG00000139055, ENSG00000189186, ENSG00000221844, ENSG00000090889, ENSG00000131747, ENSG00000127564, ENSG00000124664, ENSG00000170577, ENSG00000198797, ENSG00000248485, ENSG00000179292, ENSG00000244402, ENSG00000151892, ENSG00000233622, ENSG00000285587, ENSG00000278971, ENSG00000248779, ENSG00000237649, ENSG00000234918, ENSG00000254973, ENSG00000287959, ENSG00000261716, ENSG00000167771, ENSG00000238178, ENSG00000141424, ENSG00000263585, ENSG00000220323, ENSG00000132749, ENSG00000283023, ENSG00000175063, ENSG00000087586, ENSG00000173894, ENSG00000006747, ENSG00000086717, ENSG00000110169, ENSG00000152595, ENSG00000156802, ENSG00000259793, ENSG00000188322, ENSG00000286502, ENSG00000166959, ENSG00000085831, ENSG00000058335, ENSG00000253898, ENSG00000198125, ENSG00000167964, ENSG00000186160, ENSG00000129951, ENSG00000177732, ENSG00000174939, ENSG00000225768, ENSG00000234996, ENSG00000101213, ENSG00000066279, ENSG00000089685, ENSG00000263618, ENSG00000180596, ENSG00000171502, ENSG00000230798, ENSG00000155886, ENSG00000275266, ENSG00000143355, ENSG00000260653, ENSG00000277117, ENSG00000188916, ENSG00000135744, ENSG00000250453, ENSG00000247095, ENSG00000226745, ENSG00000128564, ENSG00000268964, ENSG00000135127, ENSG00000236313, ENSG00000162073, ENSG00000168243, ENSG00000176165, ENSG00000214725, ENSG00000182308, ENSG00000233533, ENSG00000189334, ENSG00000140284, ENSG00000160957, ENSG00000103485, ENSG00000226647, ENSG00000129514, ENSG00000164283, ENSG00000196748, ENSG00000178803, ENSG00000255774, ENSG00000184735, ENSG00000231439, ENSG00000184343, ENSG00000185499, ENSG00000102109, ENSG00000227038, ENSG00000162004, ENSG00000270933, ENSG00000164919, ENSG00000197587, ENSG00000165061, ENSG00000253895, ENSG00000198807, ENSG00000117724, ENSG00000132031, ENSG00000186897, ENSG00000183434, ENSG00000130427, ENSG00000204434, ENSG00000172478, ENSG00000232600, ENSG00000076382, ENSG00000173335, ENSG00000126803, ENSG00000173391, ENSG00000180573, ENSG00000181291, ENSG00000165548, ENSG00000143228, ENSG00000255026, ENSG00000064787, ENSG00000135451, ENSG00000167634, ENSG00000270930, ENSG00000183682, ENSG00000181085, ENSG00000160678, ENSG00000147889, ENSG00000167183, ENSG00000026559, ENSG00000134668, ENSG00000188508, ENSG00000261664, ENSG00000236008, ENSG00000258227, ENSG00000187730, ENSG00000276043, ENSG00000165171, ENSG00000121904, ENSG00000204866, ENSG00000170743, ENSG00000174938, ENSG00000163623, ENSG00000183888, ENSG00000008735, ENSG00000269235, ENSG00000196890, ENSG00000243479, ENSG00000129173, ENSG00000162949, ENSG00000164690, ENSG00000186891, ENSG00000124635, ENSG00000203995, ENSG00000164220, ENSG00000227392, ENSG00000101447, ENSG00000253361, ENSG00000249364, ENSG00000198681, ENSG00000138083, ENSG00000178597, ENSG00000184478, ENSG00000203499, ENSG00000127084, ENSG00000147234, ENSG00000135476, ENSG00000130720, ENSG00000101463, ENSG00000126778, ENSG00000167968, ENSG00000267013, ENSG00000260001, ENSG00000142945, ENSG00000186185, ENSG00000258676, ENSG00000101222, ENSG00000101115, ENSG00000203711, ENSG00000127585, ENSG00000233515, ENSG00000230393, ENSG00000226686, ENSG00000269526, ENSG00000127561, ENSG00000165304, ENSG00000197261, ENSG00000260874, ENSG00000149485, ENSG00000234115, ENSG00000188368, ENSG00000156970, ENSG00000287952, ENSG00000152049, ENSG00000094796, ENSG00000114631, ENSG00000172382, ENSG00000110092, ENSG00000254726, ENSG00000148513, ENSG00000231131, ENSG00000170965, ENSG00000225548, ENSG00000123485, ENSG00000237940, ENSG00000186474, ENSG00000184678, ENSG00000224223, ENSG00000229703, ENSG00000169509, ENSG00000147799, ENSG00000106688, ENSG00000166446, ENSG00000107954, ENSG00000105290, ENSG00000176956, ENSG00000249395, ENSG00000124302, ENSG00000170689, ENSG00000169679, ENSG00000107014, ENSG00000230873, ENSG00000134690, ENSG00000183248, ENSG00000156564, ENSG00000169245, ENSG00000115507, ENSG00000251273, ENSG00000029993, ENSG00000186871, ENSG00000188505, ENSG00000100625, ENSG00000099769, ENSG00000008300, ENSG00000160867, ENSG00000158014, ENSG00000211897, ENSG00000101255, ENSG00000006118, ENSG00000234949, ENSG00000268089, ENSG00000213759, ENSG00000203814, ENSG00000167900, ENSG00000264589, ENSG00000068985, ENSG00000170312, ENSG00000181458, ENSG00000117399, ENSG00000075673, ENSG00000259786, ENSG00000185697, ENSG00000115844, ENSG00000196427, ENSG00000227210, ENSG00000233922, ENSG00000265393, ENSG00000177380, ENSG00000130701, ENSG00000284753, ENSG00000124479, ENSG00000197903, ENSG00000276180, ENSG00000163207, ENSG00000235529, ENSG00000280119, ENSG00000217275, ENSG00000249602, ENSG00000143476, ENSG00000279930, ENSG00000284395, ENSG00000135638, ENSG00000135119, ENSG00000075702, ENSG00000267795, ENSG00000186197, ENSG00000169248, ENSG00000142552, ENSG00000065328, ENSG00000183206, ENSG00000160949, ENSG00000204338, ENSG00000003249, ENSG00000286733, ENSG00000182580, ENSG00000262772, ENSG00000121388, ENSG00000248118, ENSG00000138180, ENSG00000198829, ENSG00000079462, ENSG00000049283, ENSG00000184937, ENSG00000141526, ENSG00000102385, ENSG00000270495, ENSG00000007038, ENSG00000258910, ENSG00000188883, ENSG00000188624, ENSG00000162078, ENSG00000103528, ENSG00000113924, ENSG00000236054, ENSG00000178235, ENSG00000233854, ENSG00000269353, ENSG00000255282, ENSG00000145198, ENSG00000188959, ENSG00000160284, ENSG00000196787, ENSG00000162063, ENSG00000168280, ENSG00000104951, ENSG00000175643, ENSG00000215493, ENSG00000077152, ENSG00000169607, ENSG00000167646, ENSG00000166923, ENSG00000133124, ENSG00000107518, ENSG00000204442, ENSG00000254389, ENSG00000151790, ENSG00000181378, ENSG00000255606, ENSG00000076554, ENSG00000092853, ENSG00000170684, ENSG00000143512, ENSG00000232434, ENSG00000267577, ENSG00000186377, ENSG00000204262, ENSG00000213085, ENSG00000155367, ENSG00000105707, ENSG00000260442, ENSG00000106537, ENSG00000261713, ENSG00000176092, ENSG00000258525, ENSG00000168350, ENSG00000267077, ENSG00000107485, ENSG00000205628, ENSG00000256417, ENSG00000090932, ENSG00000172771, ENSG00000115648, ENSG00000222032, ENSG00000261761, ENSG00000120075, ENSG00000261039, ENSG00000084444, ENSG00000088340, ENSG00000006071, ENSG00000254548, ENSG00000130513, ENSG00000237515, ENSG00000168078, ENSG00000149716, ENSG00000286342, ENSG00000169962, ENSG00000274718, ENSG00000139547, ENSG00000160200, ENSG00000248498, ENSG00000141570, ENSG00000099954, ENSG00000179772, ENSG00000145911, ENSG00000196557, ENSG00000147676, ENSG00000272114, ENSG00000140263, ENSG00000215154, ENSG00000178796, ENSG00000187867, ENSG00000254231, ENSG00000167513, ENSG00000138435, ENSG00000248874, ENSG00000266602, ENSG00000221955, ENSG00000122641, ENSG00000197837, ENSG00000133466, ENSG00000188095, ENSG00000198723, ENSG00000186326, ENSG00000214078, ENSG00000141449, ENSG00000145681, ENSG00000235173, ENSG00000286790, ENSG00000123975, ENSG00000061656, ENSG00000276966, ENSG00000109674, ENSG00000115616, ENSG00000104237, ENSG00000121871, ENSG00000130700, ENSG00000280916, ENSG00000182054, ENSG00000009765, ENSG00000234869, ENSG00000135097, ENSG00000011426, ENSG00000120659, ENSG00000227473, ENSG00000233427, ENSG00000178445, ENSG00000165480, ENSG00000274750, ENSG00000130222, ENSG00000132677, ENSG00000180999, ENSG00000143578, ENSG00000197275, ENSG00000225778, ENSG00000244731, ENSG00000243742, ENSG00000169906, ENSG00000244461, ENSG00000148798, ENSG00000056291, ENSG00000285970, ENSG00000188603, ENSG00000272449, ENSG00000280099, ENSG00000268686, ENSG00000162062, ENSG00000139044, ENSG00000151012, ENSG00000252621, ENSG00000272468, ENSG00000186998, ENSG00000160213, ENSG00000174371, ENSG00000073150, ENSG00000233930, ENSG00000240498, ENSG00000186564, ENSG00000172782, ENSG00000233822, ENSG00000125844, ENSG00000233426, ENSG00000230115, ENSG00000269210, ENSG00000167702, ENSG00000255346, ENSG00000182898, ENSG00000075891, ENSG00000169258, ENSG00000260886, ENSG00000149609, ENSG00000165215, ENSG00000101412, ENSG00000173157, ENSG00000238117, ENSG00000240521, ENSG00000250510, ENSG00000196976, ENSG00000225489, ENSG00000260196, ENSG00000112984, ENSG00000175832, ENSG00000283047, ENSG00000250286, ENSG00000004838, ENSG00000159208, ENSG00000083782, ENSG00000287430, ENSG00000007968, ENSG00000131037, ENSG00000287900, ENSG00000196421, ENSG00000154198, ENSG00000106327, ENSG00000121068, ENSG00000268120, ENSG00000233221, ENSG00000233823, ENSG00000154839, ENSG00000279266, ENSG00000173838, ENSG00000080986, ENSG00000169241, ENSG00000145244, ENSG00000243069, ENSG00000128011, ENSG00000163517, ENSG00000223813, ENSG00000160282, ENSG00000105523, ENSG00000137392, ENSG00000287541, ENSG00000171848, ENSG00000180938, ENSG00000177398, ENSG00000167619, ENSG00000105695, ENSG00000253972, ENSG00000246465, ENSG00000253258, ENSG00000137825, ENSG00000258484, ENSG00000135245, ENSG00000184148, ENSG00000011347, ENSG00000232679, ENSG00000267337, ENSG00000173110, ENSG00000235687, ENSG00000166869, ENSG00000169668, ENSG00000180178, ENSG00000249599, ENSG00000127533, ENSG00000266036, ENSG00000254089, ENSG00000104524, ENSG00000203867, ENSG00000272030, ENSG00000166897, ENSG00000122952, ENSG00000203985, ENSG00000152086, ENSG00000187172, ENSG00000172461, ENSG00000178531, ENSG00000196208, ENSG00000182134, ENSG00000143320, ENSG00000224899, ENSG00000133328, ENSG00000129810, ENSG00000178462, ENSG00000165496, ENSG00000183566, ENSG00000278041, ENSG00000051180, ENSG00000183067, ENSG00000286519, ENSG00000160606, ENSG00000248131, ENSG00000260518, ENSG00000268906, ENSG00000279516, ENSG00000253755, ENSG00000248265, ENSG00000223802, ENSG00000181135, ENSG00000161133, ENSG00000196542, ENSG00000260710, ENSG00000186910, ENSG00000163467, ENSG00000177807, ENSG00000225880, ENSG00000260289, ENSG00000271727, ENSG00000282787, ENSG00000285644, ENSG00000164742, ENSG00000160180, ENSG00000139629, ENSG00000187848, ENSG00000171320, ENSG00000115884, ENSG00000180340, ENSG00000124171, ENSG00000168907, ENSG00000102854, ENSG00000254101, ENSG00000111206, ENSG00000198650, ENSG00000100095, ENSG00000287089, ENSG00000240253, ENSG00000249346, ENSG00000213420, ENSG00000130054, ENSG00000214121, ENSG00000282933, ENSG00000064270, ENSG00000259345, ENSG00000236276, ENSG00000180921, ENSG00000144191, ENSG00000141582, ENSG00000170367, ENSG00000227579, ENSG00000249001, ENSG00000185803, ENSG00000173467, ENSG00000164893, ENSG00000168061, ENSG00000105011, ENSG00000082175, ENSG00000121089, ENSG00000104267, ENSG00000116985, ENSG00000175877, ENSG00000196166, ENSG00000186193, ENSG00000256443, ENSG00000248538, ENSG00000204128, ENSG00000261385, ENSG00000185008, ENSG00000225606, ENSG00000233028, ENSG00000237594, ENSG00000163689, ENSG00000184730, ENSG00000101003, ENSG00000186868, ENSG00000136770, ENSG00000079101, ENSG00000164651, ENSG00000229637, ENSG00000130675, ENSG00000164611, ENSG00000196074, ENSG00000175130, ENSG00000149926, ENSG00000268864, ENSG00000176058, ENSG00000211454, ENSG00000198788, ENSG00000233635, ENSG00000169836, ENSG00000238176, ENSG00000183145, ENSG00000124249, ENSG00000103269, ENSG00000171804, ENSG00000213225, ENSG00000189366, ENSG00000128228, ENSG00000113763, ENSG00000013588, ENSG00000161682, ENSG00000123453, ENSG00000144452, ENSG00000137812, ENSG00000171102, ENSG00000117598, ENSG00000265702, ENSG00000285822, ENSG00000247735, ENSG00000104413, ENSG00000052344, ENSG00000236772, ENSG00000099822, ENSG00000161896, ENSG00000279331, ENSG00000255050, ENSG00000224090, ENSG00000287352, ENSG00000204055, ENSG00000205869, ENSG00000211950, ENSG00000076344, ENSG00000172366, ENSG00000175161, ENSG00000224087, ENSG00000257869, ENSG00000284659, ENSG00000076716, ENSG00000242173, ENSG00000157613, ENSG00000214894, ENSG00000007516, ENSG00000187642, ENSG00000253161, ENSG00000204538, ENSG00000213937, ENSG00000182111, ENSG00000198251, ENSG00000256663, ENSG00000126562, ENSG00000229257, ENSG00000243064, ENSG00000066777, ENSG00000285872, ENSG00000103534, ENSG00000168476, ENSG00000146670, ENSG00000185028, ENSG00000224243, ENSG00000224244, ENSG00000285108, ENSG00000124243, ENSG00000167880, ENSG00000253154, ENSG00000196793, ENSG00000242396, ENSG00000196550, ENSG00000149968, ENSG00000227896, ENSG00000083444, ENSG00000161328, ENSG00000134193, ENSG00000163518, ENSG00000263602, ENSG00000287446, ENSG00000164113, ENSG00000262468, ENSG00000144218, ENSG00000074211, ENSG00000197046, ENSG00000108878, ENSG00000130635, ENSG00000232044, ENSG00000163704, ENSG00000102384, ENSG00000079393, ENSG00000147813, ENSG00000259368, ENSG00000117971, ENSG00000226057, ENSG00000156269, ENSG00000178401, ENSG00000056487, ENSG00000179041, ENSG00000075218, ENSG00000103257, ENSG00000157456, ENSG00000197859, ENSG00000112742, ENSG00000261409, ENSG00000272853, ENSG00000233101, ENSG00000084710, ENSG00000286051, ENSG00000158106, ENSG00000235531, ENSG00000161267, ENSG00000176125, ENSG00000286159, ENSG00000024526, ENSG00000136574, ENSG00000249942, ENSG00000282816, ENSG00000182492, ENSG00000269313, ENSG00000138795, ENSG00000131668, ENSG00000234261, ENSG00000231864, ENSG00000140519, ENSG00000183779, ENSG00000101441, ENSG00000211891, ENSG00000277994, ENSG00000121039, ENSG00000243364, ENSG00000178752, ENSG00000278722, ENSG00000171241, ENSG00000130822, ENSG00000165912, ENSG00000175305, ENSG00000188620, ENSG00000250418, ENSG00000256282, ENSG00000122679, ENSG00000258092, ENSG00000099849, ENSG00000254680, ENSG00000223523, ENSG00000231324, ENSG00000266242, ENSG00000279289, ENSG00000112280, ENSG00000103253, ENSG00000132681, ENSG00000272405, ENSG00000132164, ENSG00000139410, ENSG00000122966, ENSG00000283599, ENSG00000176387, ENSG00000169583, ENSG00000100162, ENSG00000006047, ENSG00000143545, ENSG00000119715, ENSG00000169174, ENSG00000171722, ENSG00000182459, ENSG00000225108, ENSG00000279837, ENSG00000111981, ENSG00000273821, ENSG00000104738, ENSG00000260500, ENSG00000184368, ENSG00000254236, ENSG00000178999, ENSG00000226890, ENSG00000164778, ENSG00000267751, ENSG00000214077, ENSG00000267282, ENSG00000232765, ENSG00000234232, ENSG00000261949, ENSG00000259352, ENSG00000109511, ENSG00000259721, ENSG00000154342, ENSG00000251191, ENSG00000277030, ENSG00000187608, ENSG00000112379, ENSG00000214796, ENSG00000105464, ENSG00000138755, ENSG00000187550, ENSG00000231057, ENSG00000287394, ENSG00000250033, ENSG00000254349, ENSG00000111665, ENSG00000214313, ENSG00000147536, ENSG00000239405, ENSG00000196408, ENSG00000185130, ENSG00000224040, ENSG00000176912, ENSG00000260219, ENSG00000204970, ENSG00000146476, ENSG00000250284, ENSG00000251350, ENSG00000284648, ENSG00000099994, ENSG00000104522, ENSG00000273449, ENSG00000227719, ENSG00000105289, ENSG00000261326, ENSG00000068078, ENSG00000206113, ENSG00000100290, ENSG00000162782, ENSG00000124575, ENSG00000227195, ENSG00000204052, ENSG00000099617, ENSG00000286868, ENSG00000099869, ENSG00000162814, ENSG00000136541, ENSG00000134057, ENSG00000224389, ENSG00000075275, ENSG00000287595, ENSG00000181788, ENSG00000145103, ENSG00000143195, ENSG00000272568, ENSG00000178718, ENSG00000154252, ENSG000