In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [3]:
ROOT = Path().resolve().parent
root_data = os.path.join(ROOT, "data/tcga")

gdc = GDC(root_data=root_data)

os.listdir(root_data)[:10]

['subtype_for_TCGA-KIRC.tsv',
 'samples_for_TCGA-STAD_Stomach_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic.tsv',
 'cases_for_TCGA-LUSC.tsv',
 'samples_for_TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_clear_cell_tumor_other_subtype_tissue_clear_cell.tsv',
 'samples_for_TCGA-ACC_Adrenal_gland_subtype_sarcoma_tumor_sarcoma_subtype_tissue_sarcoma.tsv',
 'samples_for_TCGA-BRCA_Breast_subtype_lobular_tumor_other_subtype_tissue_breast_lobular.tsv',
 'samples_for_TCGA-SKCM_Colon_Spinal_cord_cranial_nerves_and_subtype_other_tumor_melanoma_subtype_tissue_other.tsv',
 'samples_for_TCGA-DLBC_Colon_Retroperitoneum_and_peritoneum_H_subtype_other_tumor_lymphoma_tissue_other.tsv',
 'subtype_for_TCGA-HNSC.tsv',
 'samples_for_TCGA-KICH_Kidney_subtype_other_tumor_renal_cell_carcinoma_subtype_tissue_other.tsv']

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/tcga/programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=False

pid = 'TCGA'

df_all_cases, df_all_samples, df_all_mutations = \
    gdc.loop_program_psi_samples(program=pid, force=force, verbose=verbose)

print("\n----------- end ------------\n")
print(len(df_all_samples))

0) Adrenal gland - 0) TCGA-ACC_Adrenal_gland_subtype_adrenal_cortical_carcinoma_tumor_adrenal_cortical_carcinoma_subtype_tissue_adrenal_cortical_carcinoma
Getting mutations
>>> acc_tcga_pan_can_atlas_2018 --> TCGA-ACC_Adrenal_gland_subtype_adrenal_cortical_carcinoma_tumor_adrenal_cortical_carcinoma_subtype_tissue_adrenal_cortical_carcinoma len = 54 - [np.str_('TCGA-OR-A5J2-01'), np.str_('TCGA-OR-A5J4-01'), np.str_('TCGA-OR-A5J5-01'), np.str_('TCGA-OR-A5J7-01'), np.str_('TCGA-OR-A5J8-01')]...
1) TCGA-ACC_Adrenal_gland_subtype_adrenal_cortical_carcinoma_tumor_adrenal_cortical_carcinoma_subtype_tissue_adrenal_cortical_carcinoma
Getting mutations
>>> acc_tcga_pan_can_atlas_2018 --> TCGA-ACC_Adrenal_gland_subtype_adrenal_cortical_carcinoma_tumor_adrenal_cortical_carcinoma_subtype_tissue_adrenal_cortical_carcinoma len = 54 - [np.str_('TCGA-OR-A5J2-01'), np.str_('TCGA-OR-A5J4-01'), np.str_('TCGA-OR-A5J5-01'), np.str_('TCGA-OR-A5J7-01'), np.str_('TCGA-OR-A5J8-01')]...
2) TCGA-ACC_Adrenal_gland_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> acc_tcga_pan_can_atlas_2018 --> TCGA-ACC_Adrenal_gland_subtype_other_tumor_other_subtype_tissue_other len = 2 - [np.str_('TCGA-OR-A5JV-01'), np.str_('TCGA-OR-A5L5-01')]...
3) TCGA-ACC_Adrenal_gland_subtype_sarcoma_tumor_sarcoma_subtype_tissue_sarcoma
Getting mutations
>>> acc_tcga_pan_can_atlas_2018 --> TCGA-ACC_Adrenal_gland_subtype_sarcoma_tumor_sarcoma_subtype_tissue_sarcoma len = 1 - [np.str_('TCGA-P6-A5OG-01')]...
Error: cBioPortal URL: https://www.cbioportal.org/api/molecular-profiles/acc_tcga_pan_can_atlas_2018_mutations/mutations/fetch
No mutations found for molecular profile 'acc_tcga_pan_can_atlas_2018_mutations' barcodes: [np.str_('TCGA-P6-A5OG-01')].
No mutations found for these samples.
Could not find mutations for : TCGA-ACC_Adrenal_gland_subtype_sarcoma_tumor_sarcoma_subtype_tissue_sarcoma
1) Adrenal gland, Retroperitoneum and peritoneum, Other endocrine glands and related structures, Other and ill-defined sites, Connective, subcutaneous and other soft tissues, Spinal cord, cranial nerves, and other parts of central nervous system, Heart, mediastinum, and pleura - 0) TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_other_tumor_other_tissue_other
Getting mutations
>>> pcpg_tcga_pan_can_atlas_2018 --> TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_other_tumor_other_tissue_other len = 53 - [np.str_('TCGA-P7-A5NY-01'), np.str_('TCGA-P7-A5NY-05'), np.str_('TCGA-P8-A5KD-01'), np.str_('TCGA-P8-A5KD-11'), np.str_('TCGA-P8-A6RY-01')]...
1) TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_other_tumor_glioma_tissue_other
Getting mutations
>>> pcpg_tcga_pan_can_atlas_2018 --> TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_other_tumor_glioma_tissue_other len = 28 - [np.str_('TCGA-P8-A6RX-01'), np.str_('TCGA-QR-A6GU-01'), np.str_('TCGA-QR-A6H0-01'), np.str_('TCGA-QR-A6H3-01'), np.str_('TCGA-QR-A6H6-01')]...
2) TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_tissue_adenocarcinoma_generic
Getting mutations
>>> pcpg_tcga_pan_can_atlas_2018 --> TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_tissue_adenocarcinoma_generic len = 1 - [np.str_('TCGA-RW-A68F-01')]...
3) TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_ductal_tumor_other_tissue_ductal
Getting mutations
>>> pcpg_tcga_pan_can_atlas_2018 --> TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_ductal_tumor_other_tissue_ductal len = 1 - [np.str_('TCGA-QR-A70T-01')]...
4) TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_clear_cell_tumor_other_tissue_clear_cell
Getting mutations
>>> pcpg_tcga_pan_can_atlas_2018 --> TCGA-PCPG_Adrenal_gland_Retroperitoneum_and_perit_subtype_clear_cell_tumor_other_tissue_clear_cell len = 1 - [np.str_('TCGA-S7-A7X1-01')]...
2) Bladder - 0) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
1) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
2) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
3) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
4) TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 33 - [np.str_('TCGA-4Z-AA7M-01'), np.str_('TCGA-BT-A3PJ-01'), np.str_('TCGA-CU-A0YN-01'), np.str_('TCGA-CU-A0YN-11'), np.str_('TCGA-CU-A0YR-01')]...
5) TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 33 - [np.str_('TCGA-4Z-AA7M-01'), np.str_('TCGA-BT-A3PJ-01'), np.str_('TCGA-CU-A0YN-01'), np.str_('TCGA-CU-A0YN-11'), np.str_('TCGA-CU-A0YR-01')]...
6) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
7) TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 33 - [np.str_('TCGA-4Z-AA7M-01'), np.str_('TCGA-BT-A3PJ-01'), np.str_('TCGA-CU-A0YN-01'), np.str_('TCGA-CU-A0YN-11'), np.str_('TCGA-CU-A0YR-01')]...
8) TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 33 - [np.str_('TCGA-4Z-AA7M-01'), np.str_('TCGA-BT-A3PJ-01'), np.str_('TCGA-CU-A0YN-01'), np.str_('TCGA-CU-A0YN-11'), np.str_('TCGA-CU-A0YR-01')]...
9) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
10) TCGA-BLCA_Bladder_subtype_squamous_tumor_squamous_cell_carcinoma_subtype_tissue_squamous
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_squamous_tumor_squamous_cell_carcinoma_subtype_tissue_squamous len = 3 - [np.str_('TCGA-BT-A42C-01'), np.str_('TCGA-CF-A1HS-01'), np.str_('TCGA-ZF-A9R4-01')]...
11) TCGA-BLCA_Bladder_subtype_clear_cell_tumor_squamous_cell_carcinoma_subtype_tissue_clear_cell
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_clear_cell_tumor_squamous_cell_carcinoma_subtype_tissue_clear_cell len = 1 - [np.str_('TCGA-ZF-A9R2-01')]...
12) TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_other_tumor_other_subtype_tissue_other len = 52 - [np.str_('TCGA-BL-A3JM-01'), np.str_('TCGA-BL-A3JM-11'), np.str_('TCGA-BT-A0YX-01'), np.str_('TCGA-BT-A20T-01'), np.str_('TCGA-BT-A20T-11')]...
13) TCGA-BLCA_Bladder_subtype_squamous_tumor_squamous_cell_carcinoma_subtype_tissue_squamous
Getting mutations
>>> blca_tcga_pan_can_atlas_2018 --> TCGA-BLCA_Bladder_subtype_squamous_tumor_squamous_cell_carcinoma_subtype_tissue_squamous len = 3 - [np.str_('TCGA-BT-A42C-01'), np.str_('TCGA-CF-A1HS-01'), np.str_('TCGA-ZF-A9R4-01')]...
3) Brain - 0) TCGA-LGG_Brain_subtype_other_tumor_glioma_subtype_tissue_other
Getting mutations
>>> lgg_tcga --> TCGA-LGG_Brain_subtype_other_tumor_glioma_subtype_tissue_other len = 52 - [np.str_('TCGA-DB-5274-01'), np.str_('TCGA-DB-5278-01'), np.str_('TCGA-DB-5281-01'), np.str_('TCGA-DB-A4XE-01'), np.str_('TCGA-DB-A64O-01')]...
1) TCGA-LGG_Brain_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> lgg_tcga --> TCGA-LGG_Brain_subtype_other_tumor_other_subtype_tissue_other len = 51 - [np.str_('TCGA-CS-6188-01'), np.str_('TCGA-DB-5277-01'), np.str_('TCGA-DB-5279-01'), np.str_('TCGA-DH-A7UT-01'), np.str_('TCGA-DU-5854-01')]...
4) Brain - 0) TCGA-GBM_Brain_subtype_other_tumor_glioma_subtype_tissue_other
Getting mutations
>>> gbm_tcga_pan_can_atlas_2018 --> TCGA-GBM_Brain_subtype_other_tumor_glioma_subtype_tissue_other len = 78 - [np.str_('TCGA-02-0004-01'), np.str_('TCGA-02-0011-01'), np.str_('TCGA-02-0024-01'), np.str_('TCGA-02-0047-01'), np.str_('TCGA-02-0068-01')]...
1) TCGA-GBM_Brain_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> gbm_tcga_pan_can_atlas_2018 --> TCGA-GBM_Brain_subtype_other_tumor_other_subtype_tissue_other len = 29 - [np.str_('TCGA-02-0250-01'), np.str_('TCGA-02-0329-01'), np.str_('TCGA-02-0336-01'), np.str_('TCGA-06-0121-01'), np.str_('TCGA-06-0178-01')]...
2) TCGA-GBM_Brain_subtype_other_tumor_glioma_subtype_tissue_other
Getting mutations
>>> gbm_tcga_pan_can_atlas_2018 --> TCGA-GBM_Brain_subtype_other_tumor_glioma_subtype_tissue_other len = 78 - [np.str_('TCGA-02-0004-01'), np.str_('TCGA-02-0011-01'), np.str_('TCGA-02-0024-01'), np.str_('TCGA-02-0047-01'), np.str_('TCGA-02-0068-01')]...
3) TCGA-GBM_Brain_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> gbm_tcga_pan_can_atlas_2018 --> TCGA-GBM_Brain_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 1 - [np.str_('TCGA-06-0209-01')]...
Error: cBioPortal URL: https://www.cbioportal.org/api/molecular-profiles/gbm_tcga_pan_can_atlas_2018_mutations/mutations/fetch
No mutations found for molecular profile 'gbm_tcga_pan_can_atlas_2018_mutations' barcodes: [np.str_('TCGA-06-0209-01')].
No mutations found for these samples.
Could not find mutations for : TCGA-GBM_Brain_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
5) Breast - 0) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
1) TCGA-BRCA_Breast_subtype_lobular_tumor_other_subtype_tissue_breast_lobular
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_lobular_tumor_other_subtype_tissue_breast_lobular len = 54 - [np.str_('TCGA-5L-AAT1-01'), np.str_('TCGA-A2-A0T6-01'), np.str_('TCGA-A2-A0YD-01'), np.str_('TCGA-A2-A3KC-01'), np.str_('TCGA-A2-A4RW-01')]...
2) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
3) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
4) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
5) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
6) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
7) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
8) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
9) TCGA-BRCA_Breast_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 19 - [np.str_('TCGA-5L-AAT0-01'), np.str_('TCGA-A2-A04W-01'), np.str_('TCGA-A2-A3KD-01'), np.str_('TCGA-A2-A4S0-01'), np.str_('TCGA-A7-A3IY-01')]...
10) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
11) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
12) TCGA-BRCA_Breast_subtype_ductal_tumor_adenocarcinoma_subtype_tissue_breast_ductal
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_ductal_tumor_adenocarcinoma_subtype_tissue_breast_ductal len = 6 - [np.str_('TCGA-B6-A0IC-01'), np.str_('TCGA-BH-A0HL-01'), np.str_('TCGA-D8-A1JS-01'), np.str_('TCGA-D8-A1X7-01'), np.str_('TCGA-E9-A5UP-01')]...
13) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
14) TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_other_tumor_other_subtype_tissue_other len = 55 - [np.str_('TCGA-A1-A0SB-01'), np.str_('TCGA-A1-A0SN-01'), np.str_('TCGA-A1-A0SQ-01'), np.str_('TCGA-A2-A0D1-01'), np.str_('TCGA-A2-A0T1-01')]...
15) TCGA-BRCA_Breast_subtype_clear_cell_tumor_other_subtype_tissue_clear_cell
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_clear_cell_tumor_other_subtype_tissue_clear_cell len = 2 - [np.str_('TCGA-AQ-A54O-01'), np.str_('TCGA-BH-A0EA-01')]...
16) TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal len = 4 - [np.str_('TCGA-E2-A2P5-01'), np.str_('TCGA-LL-A440-01'), np.str_('TCGA-LL-A442-01'), np.str_('TCGA-S3-AA17-01')]...
17) TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal len = 4 - [np.str_('TCGA-E2-A2P5-01'), np.str_('TCGA-LL-A440-01'), np.str_('TCGA-LL-A442-01'), np.str_('TCGA-S3-AA17-01')]...
18) TCGA-BRCA_Breast_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic len = 19 - [np.str_('TCGA-5L-AAT0-01'), np.str_('TCGA-A2-A04W-01'), np.str_('TCGA-A2-A3KD-01'), np.str_('TCGA-A2-A4S0-01'), np.str_('TCGA-A7-A3IY-01')]...
19) TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_ductal_tumor_other_subtype_tissue_breast_ductal len = 4 - [np.str_('TCGA-E2-A2P5-01'), np.str_('TCGA-LL-A440-01'), np.str_('TCGA-LL-A442-01'), np.str_('TCGA-S3-AA17-01')]...
20) TCGA-BRCA_Breast_subtype_neuroendocrine_tumor_neuroendocrine_tumor_subtype_tissue_neuroendocrine
Getting mutations
>>> brca_tcga_pan_can_atlas_2018 --> TCGA-BRCA_Breast_subtype_neuroendocrine_tumor_neuroendocrine_tumor_subtype_tissue_neuroendocrine len = 1 - [np.str_('TCGA-A1-A0SK-01')]...
6) Bronchus and lung - 0) TCGA-LUAD_Bronchus_and_lung_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_lung_adenocarcinoma
Getting mutations
>>> luad_tcga_pan_can_atlas_2018 --> TCGA-LUAD_Bronchus_and_lung_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_lung_adenocarcinoma len = 78 - [np.str_('TCGA-38-4625-01'), np.str_('TCGA-38-4625-11'), np.str_('TCGA-38-4629-01'), np.str_('TCGA-38-4629-11'), np.str_('TCGA-38-4631-01')]...
1) TCGA-LUAD_Bronchus_and_lung_subtype_other_tumor_other_subtype_tissue_other
Getting mutations
>>> luad_tcga_pan_can_atlas_2018 --> TCGA-LUAD_Bronchus_and_lung_subtype_other_tumor_other_subtype_tissue_other len = 73 - [np.str_('TCGA-05-4245-01'), np.str_('TCGA-05-4382-01'), np.str_('TCGA-17-Z004-01'), np.str_('TCGA-17-Z004-11'), np.str_('TCGA-17-Z007-01')]...
2) TCGA-LUAD_Bronchus_and_lung_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_lung_adenocarcinoma
Getting mutations
>>> luad_tcga_pan_can_atlas_2018 --> TCGA-LUAD_Bronchus_and_lung_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_lung_adenocarcinoma len = 78 - [np.str_('TCGA-38-4625-01'), np.str_('TCGA-38-4625-11'), np.str_('TCGA-38-4629-01'), np.str_('TCGA-38-4629-11'), np.str_('TCGA-38-4631-01')]...

In [8]:
print(len(df_all_cases))
df_all_cases.tail(3)

11428

,primary_site,disease_type,case_id,diagnoses,pid,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
11425,Corpus uteri,"Cystic, Mucinous and Serous Neoplasms",db67a9cd-65ba-4d6f-a799-031b6b3df599,[{'primary_diagnosis': 'Serous cystadenocarcin...,TCGA-UCEC,serous,unknown,"Serous cystadenocarcinoma, NOS",G3,NaN,...,corpus uteri,cystic mucinous and serous neoplasms,serous cystadenocarcinoma,adenocarcinoma,epithelial,uterine_serous,ok,valid,1,0.001786
11426,Corpus uteri,Adenomas and Adenocarcinomas,976bb47a-d999-4e24-ad08-452fea73c846,"[{'primary_diagnosis': 'Clear cell carcinoma',...",TCGA-UCEC,clear_cell,unknown,Clear cell carcinoma,G1,NaN,...,corpus uteri,adenomas and adenocarcinomas,clear cell carcinoma,other,epithelial,uterine_clear_cell,ok,valid,1,0.001786
11427,Corpus uteri,Adenomas and Adenocarcinomas,e604f5d4-f2c0-4404-9073-b8dbc8396778,[{'primary_diagnosis': 'Endometrioid adenocarc...,TCGA-UCEC,endometrioid,unknown,"Endometrioid adenocarcinoma, NOS",G3,NaN,...,corpus uteri,adenomas and adenocarcinomas,endometrioid adenocarcinoma,adenocarcinoma,epithelial,uterine_endometrioid,ok,valid,1,0.001786

In [9]:
print(len(df_all_samples))
df_all_samples.tail(3)

245657

,case_id,submitter_id,sample_id,sample_type,barcode_id,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
245654,2fe46394-cfc5-44bb-81a9-e438a0126f5b,TCGA-A5-A1OK,65208656-d7e1-493a-8806-90b4e82d701f,Blood Derived Normal,TCGA-A5-A1OK-10A,c1d633f4-e539-4abd-9ba6-8c67d8b3f474,42f61f26-fbd1-4ecf-b446-980cdd7cdb8e.wxs.aliqu...,Aggregated Somatic Mutation,MAF,TCGA-UCEC,squamous,squamous_cell_carcinoma,squamous,unknown
245655,2fe46394-cfc5-44bb-81a9-e438a0126f5b,TCGA-A5-A1OK,65208656-d7e1-493a-8806-90b4e82d701f,Blood Derived Normal,TCGA-A5-A1OK-10A,37650872-d6af-4211-bd15-b7441ba6c378,0dbc85ff-ee09-467c-81ff-a6184401f7cc.wxs.Pinde...,Annotated Somatic Mutation,MAF,TCGA-UCEC,squamous,squamous_cell_carcinoma,squamous,unknown
245656,2fe46394-cfc5-44bb-81a9-e438a0126f5b,TCGA-A5-A1OK,65208656-d7e1-493a-8806-90b4e82d701f,Blood Derived Normal,TCGA-A5-A1OK-10A,cea3e10a-4c23-473a-8302-2e6a91a2b1dc,CABAL_p_TCGA_b112_125_SNP_N_GenomeWideSNP_6_F0...,Masked Copy Number Segment,TXT,TCGA-UCEC,squamous,squamous_cell_carcinoma,squamous,unknown

In [10]:
barcodes = np.unique(df_all_samples.barcode_id)
len(barcodes)

8506

In [11]:
sample_types = np.unique(df_all_samples.sample_type)
sample_types

array(['Additional - New Primary', 'Additional Metastatic',
       'Blood Derived Normal', 'Bone Marrow Normal', 'Buccal Cell Normal',
       'Metastatic', 'Primary Blood Derived Cancer - Peripheral Blood',
       'Primary Tumor', 'Recurrent Tumor', 'Solid Tissue Normal'],
      dtype=object)

In [12]:
df_normal = df_all_samples[df_all_samples.sample_type.str.contains('Normal', case=False, na=False)]
len(df_normal)

98079

In [13]:
symbols = np.unique(df_all_mutations.symbol)
len(symbols)

18957

In [17]:
primary_sites = list(np.unique(df_all_cases.primary_site_norm))
primary_sites.sort()
print(len(primary_sites))

print(", ".join(primary_sites))

57
adrenal gland, anus and anal canal, base of tongue, bladder, bones joints and articular cartilage of limbs, bones joints and articular cartilage of other and unspecified sites, brain, breast, bronchus and lung, cervix uteri, colon, connective subcutaneous and other soft tissues, corpus uteri, esophagus, eye and adnexa, floor of mouth, gum, heart mediastinum and pleura, hematopoietic and reticuloendothelial systems, hypopharynx, kidney, larynx, lip, liver and intrahepatic bile ducts, lymph nodes, meninges, nasal cavity and middle ear, oropharynx, other and ill-defined sites, other and ill-defined sites in lip oral cavity and pharynx, other and unspecified major salivary glands, other and unspecified male genital organs, other and unspecified parts of biliary tract, other and unspecified parts of mouth, other and unspecified parts of tongue, other endocrine glands and related structures, ovary, palate, pancreas, parotid gland, peripheral nerves and autonomic nervous system, prostate gland, rectosigmoid junction, rectum, retroperitoneum and peritoneum, skin, small intestine, spinal cord cranial nerves and other parts of central nervous system, stomach, testis, thymus, thyroid gland, tonsil, unknown, uterus, vagina, vulva

In [18]:
stri = f"Interfacing GDC {pid} data, one gathered:"
print(stri)
stri = f"\t- {len(primary_sites)} primary sites."
print(stri)
stri = f"\t- {len(df_all_cases)} cases."
print(stri)
stri = f"\t- {len(df_all_samples)} samples."
print(stri)
stri = f"\t- {len(df_all_mutations)} annotated mutations."
print(stri)
stri = f"\t- {len(symbols)} different genes."
print(stri)

Interfacing GDC TCGA data, one gathered:
	- 57 primary sites.
	- 11428 cases.
	- 245657 samples.
	- 745228 annotated mutations.
	- 18957 different genes.

In [19]:
primary_sites = np.array(primary_sites)
primary_sites

array(['adrenal gland', 'anus and anal canal', 'base of tongue',
       'bladder', 'bones joints and articular cartilage of limbs',
       'bones joints and articular cartilage of other and unspecified sites',
       'brain', 'breast', 'bronchus and lung', 'cervix uteri', 'colon',
       'connective subcutaneous and other soft tissues', 'corpus uteri',
       'esophagus', 'eye and adnexa', 'floor of mouth', 'gum',
       'heart mediastinum and pleura',
       'hematopoietic and reticuloendothelial systems', 'hypopharynx',
       'kidney', 'larynx', 'lip', 'liver and intrahepatic bile ducts',
       'lymph nodes', 'meninges', 'nasal cavity and middle ear',
       'oropharynx', 'other and ill-defined sites',
       'other and ill-defined sites in lip oral cavity and pharynx',
       'other and unspecified major salivary glands',
       'other and unspecified male genital organs',
       'other and unspecified parts of biliary tract',
       'other and unspecified parts of mouth',
       'other and unspecified parts of tongue',
       'other endocrine glands and related structures', 'ovary', 'palate',
       'pancreas', 'parotid gland',
       'peripheral nerves and autonomic nervous system', 'prostate gland',
       'rectosigmoid junction', 'rectum',
       'retroperitoneum and peritoneum', 'skin', 'small intestine',
       'spinal cord cranial nerves and other parts of central nervous system',
       'stomach', 'testis', 'thymus', 'thyroid gland', 'tonsil',
       'unknown', 'uterus', 'vagina', 'vulva'], dtype='<U68')

In [20]:

term = 'breast'
term = 'esophagus'

primary_sites[[True if term in x.lower() else False for x in primary_sites]]

array(['esophagus'], dtype='<U68')

In [21]:
df_all_cases.head()

,primary_site,disease_type,case_id,diagnoses,pid,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
0,Adrenal gland,Adenomas and Adenocarcinomas,7e61e3b8-c617-4a5f-afdf-689521c9a670,[{'primary_diagnosis': 'Adrenal cortical carci...,TCGA-ACC,adrenal_cortical_carcinoma,NaN,Adrenal cortical carcinoma,NaN,NaN,...,adrenal gland,adenomas and adenocarcinomas,adrenal cortical carcinoma,adrenal_cortical_carcinoma,other,adrenal_cortical_carcinoma,ok,valid,1,0.01087
1,Adrenal gland,Adenomas and Adenocarcinomas,09454ed6-64bc-4a35-af44-7c4344623d45,[{'primary_diagnosis': 'Adrenal cortical carci...,TCGA-ACC,adrenal_cortical_carcinoma,NaN,Adrenal cortical carcinoma,NaN,NaN,...,adrenal gland,adenomas and adenocarcinomas,adrenal cortical carcinoma,adrenal_cortical_carcinoma,other,adrenal_cortical_carcinoma,ok,valid,1,0.01087
2,Adrenal gland,Adenomas and Adenocarcinomas,4f845fea-e823-47d6-89fb-36ee478a43b8,[{'primary_diagnosis': 'Adrenal cortical carci...,TCGA-ACC,adrenal_cortical_carcinoma,NaN,Adrenal cortical carcinoma,NaN,NaN,...,adrenal gland,adenomas and adenocarcinomas,adrenal cortical carcinoma,adrenal_cortical_carcinoma,other,adrenal_cortical_carcinoma,ok,valid,1,0.01087
3,Adrenal gland,Adenomas and Adenocarcinomas,891b7a67-0a01-45f0-8a32-4a1b3e888f6c,[{'primary_diagnosis': 'Adrenal cortical carci...,TCGA-ACC,adrenal_cortical_carcinoma,NaN,Adrenal cortical carcinoma,NaN,NaN,...,adrenal gland,adenomas and adenocarcinomas,adrenal cortical carcinoma,adrenal_cortical_carcinoma,other,adrenal_cortical_carcinoma,ok,valid,1,0.01087
4,Adrenal gland,Adenomas and Adenocarcinomas,a26b6f97-fd7e-4b96-bdf5-9df4f9233726,[{'primary_diagnosis': 'Adrenal cortical carci...,TCGA-ACC,adrenal_cortical_carcinoma,NaN,Adrenal cortical carcinoma,NaN,NaN,...,adrenal gland,adenomas and adenocarcinomas,adrenal cortical carcinoma,adrenal_cortical_carcinoma,other,adrenal_cortical_carcinoma,ok,valid,1,0.01087

In [22]:
disease_type = 'Adenomas and Adenocarcinomas'

df2 = df_all_cases[ (df_all_cases.primary_site_norm.str.contains(term, case=False)) &
                   (df_all_cases.disease_type_norm.str.contains(disease_type, case=False)) ]
df2

,primary_site,disease_type,case_id,diagnoses,pid,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
5558,Esophagus,Adenomas and Adenocarcinomas,29da08f4-c9e2-4e7a-9733-b4ec5b9c5f13,"[{'primary_diagnosis': 'Not Reported'}, {'prim...",TCGA-ESCA,other,unknown,Not Reported,GX,NaN,...,esophagus,adenomas and adenocarcinomas,not reported,other,other,other,ok,invalid,1,0.005405
5560,Esophagus,Adenomas and Adenocarcinomas,6826bcdd-24a4-4dd1-9fab-201cf774e166,"[{'primary_diagnosis': 'Adenocarcinoma, NOS'},...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",GX,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5561,Esophagus,Adenomas and Adenocarcinomas,90940ff1-c270-44f5-9949-f726838aaa57,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",GX,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5562,Esophagus,Adenomas and Adenocarcinomas,c17331fb-c47b-40b5-8d39-9803ee37a42a,"[{'primary_diagnosis': 'Adenocarcinoma, NOS'},...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",G2,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5563,Esophagus,Adenomas and Adenocarcinomas,b2b8c6bc-509b-4c5b-b0fb-d07a5628fa80,"[{'primary_diagnosis': 'Adenocarcinoma, NOS'},...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",G3,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5735,Esophagus,Adenomas and Adenocarcinomas,ee47cd59-c8d8-4b1e-96db-91c679e4106f,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",G2,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5737,Esophagus,Adenomas and Adenocarcinomas,f23794d7-35cc-4550-a03f-8e3cde1a2bcd,"[{'primary_diagnosis': 'Adenocarcinoma, NOS'},...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",G3,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5738,Esophagus,Adenomas and Adenocarcinomas,f28f37a0-8e24-4a36-90f0-83cf5a27be10,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",GX,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5740,Esophagus,Adenomas and Adenocarcinomas,fb777a96-2e24-4b60-9c7e-9d5dc3e7f35a,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",GX,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405
5742,Esophagus,Adenomas and Adenocarcinomas,fdcdf592-66f1-4027-962f-a64d49be474f,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-ESCA,adenocarcinoma_generic,unknown,"Adenocarcinoma, NOS",G3,NaN,...,esophagus,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,adenocarcinoma_generic,ok,valid,1,0.005405

In [23]:
case_id_list = np.unique(df2.case_id)
len(case_id_list)

87

In [24]:
sample_type = 'tumor'
df3 = df_all_samples[ (df_all_samples.case_id.isin(case_id_list)) & (df_all_samples.sample_type.str.contains(sample_type, case=False)) ]
print(len(df3))
df3.head(3)

2339

,case_id,submitter_id,sample_id,sample_type,barcode_id,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
104523,9e02a368-8858-4ec5-8c27-9e0876d387a4,TCGA-L5-A8NJ,7cf7a9fc-92f8-4072-98bd-59829c10d172,Primary Tumor,TCGA-L5-A8NJ-01A,edd1ed69-5095-44ff-a075-2e5593798a8e,TCGA-ESCA.221d3836-d867-4458-a7f3-108a3b374f77...,Gene Level Copy Number,TSV,TCGA-ESCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,unknown
104524,9e02a368-8858-4ec5-8c27-9e0876d387a4,TCGA-L5-A8NJ,7cf7a9fc-92f8-4072-98bd-59829c10d172,Primary Tumor,TCGA-L5-A8NJ-01A,4f848b21-0903-4114-98c7-5a06a640477a,TCGA_ESCA.b056c63a-e29a-4ae0-9c96-3a9853949333...,Annotated Somatic Mutation,VCF,TCGA-ESCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,unknown
104525,9e02a368-8858-4ec5-8c27-9e0876d387a4,TCGA-L5-A8NJ,7cf7a9fc-92f8-4072-98bd-59829c10d172,Primary Tumor,TCGA-L5-A8NJ-01A,e0f0f5ab-7ff7-4640-9cf6-0172e310256d,3ee213e3-a720-420d-9e59-2bebdf8cb379.rna_seq.g...,Aligned Reads,BAM,TCGA-ESCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,unknown

In [25]:
sample_type_list = np.unique(df3.sample_type)
sample_type_list

array(['Primary Tumor'], dtype=object)

In [28]:
barcode_id_list = np.unique(df3.barcode_id)
len(barcode_id_list)

93

In [35]:
barcode_id_list = [gdc.to_cbioportal_barcode_id(x) for x in barcode_id_list]

barcode_id_list[:3]

['TCGA-2H-A9GF-01', 'TCGA-2H-A9GF-01', 'TCGA-2H-A9GG-01']

### Mutations

In [31]:
df_all_mutations.columns

Index(['pid', 'barcode_id_sample', 'barcode_id', 'symbol', 'refseq_mrna_id',
       'entrez_gene_id', 'protein_mut', 'mutation_type', 'variant_type', 'chr',
       'n_mutations'],
      dtype='str')

In [33]:
df_all_mutations.barcode_id_sample.iloc[:4]

0    TCGA-OR-A5J2-01
1    TCGA-OR-A5J2-01
2    TCGA-OR-A5J2-01
3    TCGA-OR-A5J2-01
Name: barcode_id_sample, dtype: str

In [36]:
df4 = df_all_mutations[df_all_mutations.barcode_id_sample.isin(barcode_id_list)]
len(df4), len(df_all_mutations)

(7680, 745228)

In [37]:
df4.head(3)

,pid,barcode_id_sample,barcode_id,symbol,refseq_mrna_id,entrez_gene_id,protein_mut,mutation_type,variant_type,chr,n_mutations
396220,esca_tcga_pan_can_atlas_2018,TCGA-2H-A9GF-01,TCGA-2H-A9GF,AASS,NA,10157,E368V,Missense_Mutation,SNP,7,1
396221,esca_tcga_pan_can_atlas_2018,TCGA-2H-A9GF-01,TCGA-2H-A9GF,ABCA13,NM_152701.3,154664,R2939C,Missense_Mutation,SNP,7,1
396222,esca_tcga_pan_can_atlas_2018,TCGA-2H-A9GF-01,TCGA-2H-A9GF,ABCB6,NM_005689.2,10058,R584H,Missense_Mutation,SNP,2,1