In [1]:
!python --version

Python 3.11.14

## GDC

https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/

sample  
 ├── primary_site       (organ)  
 ├── disease_type       (broad class)  
 ├── subtype_global     (cross-cancer)  
 ├── subtype_tissue     (within-cancer)  
 └── histology          (biological family)

### TCGA / GDC Portal

https://portal.gdc.cancer.gov/

### 🧠 Big picture (this is powerful)

- You’ve essentially built the backbone of:
- cBioPortal-like explorer
- cohort stratification engine
- patient-specific pipeline (your perturbation_agent 🔥)

### 💡 Flow

> project → project_id  
> primary_sites → pid and disease_type  
> subtypes → subtype_id  
> stages →  stage_id  
> case_id → case_ids or UUIDs  
> samples → sample_id [tumor, normal]  
> aliquots → aliquot_id  
> files → file_id

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### 👉 a TCGA cohort builder + data retrieval engine

Which means you can easily extend to:


> pan-cancer analyses  
> patient-specific pipelines (your perturb_agent 🔥)  
> automated workflows (Nextflow-ready)  

#### 🚀 Next steps

> Production pipeline  
  - CLI tool
  - cached queries
  - reproducible outputs

> Expression matrix builder  
  - auto-download
  - merge TSVs
  - DESeq2-ready matrix

> Patient-level analysis
  - per-case DEG
  - pathway perturbation scoring

### Defaults

In [3]:
ROOT = Path().resolve().parent
root_data = os.path.join(ROOT, "data/tcga")

gdc = GDC(root_data=root_data)

os.listdir(root_data)[:10]

['subtype_for_TCGA-KIRC.tsv',
 'degs.txt',
 'cases_for_TCGA-LUSC.tsv',
 'subtype_for_TCGA-HNSC.tsv',
 'cases_for_TCGA-PCPG.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_0045349c-69d9-4306-a403-c9c1fa836644_sample_type_Primary_Tumor_stage_unknown_fileid_0e0df72c-33c0-4e4f-939c-a4d45a6e1ea3.tsv',
 'cases_for_TCGA-THYM.tsv',
 'cases_for_TCGA-PAAD.tsv',
 'cases_for_TCGA-LAML.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_011b9b2d-ebe5-42bf-9662-d922faccc7a1_sample_type_Primary_Tumor_stage_Stage_IA_fileid_89409cf3-e710-47fd-af3c-6f8f0dec7c90.tsv']

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/tcga/programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=True

program = 'TCGA'

df_psi = gdc.get_primary_sites(program=program, force=force, verbose=verbose)

print(len(df_psi))
df_psi.head(12)

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/tcga/primary_site_program_TCGA.tsv'
33

,pid,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma
3,TCGA-LGG,Brain,TCGA-LGG,Gliomas,Brain Lower Grade Glioma
4,TCGA-GBM,Brain,TCGA-GBM,"Not Reported, Gliomas",Glioblastoma Multiforme
5,TCGA-BRCA,Breast,TCGA-BRCA,"Adnexal and Skin Appendage Neoplasms, Adenomas...",Breast Invasive Carcinoma
6,TCGA-LUAD,Bronchus and lung,TCGA-LUAD,"Ductal and Lobular Neoplasms, Cystic, Mucinous...",Lung Adenocarcinoma
7,TCGA-LUSC,Bronchus and lung,TCGA-LUSC,"Squamous Cell Neoplasms, Adenomas and Adenocar...",Lung Squamous Cell Carcinoma
8,TCGA-MESO,"Bronchus and lung, Heart, mediastinum, and pleura",TCGA-MESO,Mesothelial Neoplasms,Mesothelioma
9,TCGA-CESC,"Cervix uteri, Ovary",TCGA-CESC,"Squamous Cell Neoplasms, Cystic, Mucinous and ...",Cervical Squamous Cell Carcinoma and Endocervi...
10,TCGA-COAD,"Colon, Rectosigmoid junction",TCGA-COAD,"Cystic, Mucinous and Serous Neoplasms, Complex...",Colon Adenocarcinoma
11,TCGA-READ,"Colon, Rectosigmoid junction, Rectum, Connecti...",TCGA-READ,"Cystic, Mucinous and Serous Neoplasms, Adenoma...",Rectum Adenocarcinoma

In [8]:
df_psi.tail(3)

,pid,primary_site,project_id,disease_type,name
30,TCGA-THCA,Thyroid gland,TCGA-THCA,"Squamous Cell Neoplasms, Epithelial Neoplasms,...",Thyroid Carcinoma
31,TCGA-UCS,"Uterus, NOS, Corpus uteri",TCGA-UCS,"Basal Cell Neoplasms, Complex Mixed and Stroma...",Uterine Carcinosarcoma
32,TCGA-UCEC,"Uterus, NOS, Corpus uteri",TCGA-UCEC,"Not Reported, Cystic, Mucinous and Serous Neop...",Uterine Corpus Endometrial Carcinoma

### Subtypes explanation

👉 GDC does NOT give you clean biological subtypes
👉 You must derive them yourself

This is actually a feature, not a bug — because:

> you control granularity  
> you can harmonize across cancers  
> you avoid noisy labels  


💡 If you want to level this up

I can help you build:

🔬 A cross-TCGA subtype harmonizer
maps all projects → unified subtype ontology
handles synonyms (adenocarcinoma, NOS, etc.)
outputs clean ML-ready labels

👉 That would massively improve your perturbation analysis.

In [22]:
ipsi = 5
pid = df_psi.iloc[ipsi].pid
primary_site = df_psi.iloc[ipsi].primary_site

print(ipsi, pid, primary_site)

5 TCGA-BRCA Breast

- Brain tumors do NOT use AJCC staging (3 - TCGA-LGG Brain)

In [23]:
force=False
verbose=True

pid = df_psi.iloc[ipsi].pid
primary_site = df_psi.iloc[ipsi].primary_site

print(ipsi, pid, primary_site)

df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

print("df_cases", len(df_cases), "df_subt", len(df_subt))

5 TCGA-BRCA Breast
Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-BRCA.tsv'
df_cases 1098 df_subt 21

### df_subt

In [24]:
print(len(df_subt))
df_subt

21

,pid,subtype_global,tumor_class,subtype_tissue,stage,n
0,TCGA-BRCA,other,other,other,Stage IIA,263
1,TCGA-BRCA,lobular,other,breast_lobular,unknown,223
2,TCGA-BRCA,other,other,other,Stage IIB,180
3,TCGA-BRCA,other,other,other,Stage IIIA,107
4,TCGA-BRCA,other,other,other,unknown,76
5,TCGA-BRCA,other,other,other,Stage IA,69
6,TCGA-BRCA,other,other,other,Stage I,67
7,TCGA-BRCA,other,other,other,Stage IIIC,29
8,TCGA-BRCA,other,other,other,Stage IIIB,18
9,TCGA-BRCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,unknown,18
10,TCGA-BRCA,other,other,other,Stage IV,16
11,TCGA-BRCA,other,other,other,Stage X,9
12,TCGA-BRCA,ductal,adenocarcinoma,breast_ductal,unknown,6
13,TCGA-BRCA,other,other,other,Stage IB,5
14,TCGA-BRCA,other,other,other,Stage II,4
15,TCGA-BRCA,clear_cell,other,clear_cell,Stage IIA,2
16,TCGA-BRCA,ductal,other,breast_ductal,unknown,2
17,TCGA-BRCA,ductal,other,breast_ductal,Stage IIA,1
18,TCGA-BRCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,Stage X,1
19,TCGA-BRCA,ductal,other,breast_ductal,Stage IIB,1
20,TCGA-BRCA,neuroendocrine,neuroendocrine_tumor,neuroendocrine,unknown,1

### df_cases

In [25]:
df_cases.head(3)

,primary_site,disease_type,case_id,diagnoses,pid,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac,sstage
0,Breast,Complex Epithelial Neoplasms,e3935ce4-64d3-4a66-ba11-d308b844b410,"[{'primary_diagnosis': 'Metaplastic carcinoma,...",TCGA-BRCA,other,unknown,"Metaplastic carcinoma, NOS",NaN,NaN,...,complex epithelial neoplasms,metaplastic carcinoma,other,other,other,ok,ambiguous,1,0.000911,missing
1,Breast,Ductal and Lobular Neoplasms,e3b555aa-7f0a-49c6-9b13-182c61a144c1,[{'primary_diagnosis': 'Infiltrating duct carc...,TCGA-BRCA,other,Stage IIIA,"Infiltrating duct carcinoma, NOS",NaN,NaN,...,ductal and lobular neoplasms,infiltrating duct carcinoma,other,other,other,ok,ambiguous,1,0.000911,III
2,Breast,Ductal and Lobular Neoplasms,17ca61a2-607a-45ff-88fa-ef72e80bf891,[{'primary_diagnosis': 'Infiltrating duct carc...,TCGA-BRCA,other,Stage IA,"Infiltrating duct carcinoma, NOS",NaN,NaN,...,ductal and lobular neoplasms,infiltrating duct carcinoma,other,other,other,ok,ambiguous,1,0.000911,I

In [26]:
cols = ["pid", "case_id", "subtype_global", "tumor_class", "subtype_tissue", "stage"]

df_cases[cols].head(12)

,pid,case_id,subtype_global,tumor_class,subtype_tissue,stage
0,TCGA-BRCA,e3935ce4-64d3-4a66-ba11-d308b844b410,other,other,other,unknown
1,TCGA-BRCA,e3b555aa-7f0a-49c6-9b13-182c61a144c1,other,other,other,Stage IIIA
2,TCGA-BRCA,17ca61a2-607a-45ff-88fa-ef72e80bf891,other,other,other,Stage IA
3,TCGA-BRCA,7d681cc6-689d-41c8-9e84-e13733089ec9,other,other,other,Stage IIB
4,TCGA-BRCA,17f275c1-a0d4-487d-8f02-ea279584b4cd,other,other,other,Stage IA
5,TCGA-BRCA,189e1f27-7738-413a-a4d4-97d41d592a13,other,other,other,Stage IIA
6,TCGA-BRCA,95c53ecf-d8f1-4bcb-9b1a-c9a0542939f0,other,other,other,Stage IA
7,TCGA-BRCA,c0f88fc5-56b0-4255-bbd1-9a21ced8b37b,other,other,other,Stage IIIA
8,TCGA-BRCA,0f64edec-0f1f-4025-8a53-75f9534f7828,other,other,other,Stage IIA
9,TCGA-BRCA,c25898b4-eb33-42f4-bf3f-bf532a929e7d,lobular,other,breast_lobular,unknown
10,TCGA-BRCA,195b6731-6ae6-416e-a345-0eb8874a0ca2,other,other,other,Stage IIIA
11,TCGA-BRCA,7f97971b-2818-4e4b-9c9e-7c0246f9484c,other,other,other,Stage IIB

### Samples

In [30]:
force=True
force=False
verbose=True

isubt=0

row = df_subt.iloc[isubt]

pid = row.pid
subtype_global = row.subtype_global
tumor_class = row.tumor_class
subtype_tissue = row.subtype_tissue
stage = None # row.stage

# s_case = f"{pid} subtype '{subtype_global}' tumor '{tumor_class}' subtype_tissue '{subtype_tissue}' stage '{stage}'"
# print(s_case)
df_samples = gdc.get_samples_for_pid_subtypes(pid=pid, subtype_global=subtype_global,
                                             tumor_class=tumor_class, subtype_tissue=subtype_tissue,
                                             batch_size=200, force=force, verbose=verbose)

print(len(df_samples))

Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-BRCA.tsv'
>>> TCGA-BRCA subtype 'other' tumor 'other' subtype_tissue 'other'
>>> 843 cases [001cef41-ff86-4d3f-a140-a647ac4b10a1,0045349c-69d9-4306-a403-c9c1fa836644,00a2d166-78c9-4687-a195-3d6315c27574] .....
Searching: 0-5
>>> 5 ['001cef41-ff86-4d3f-a140-a647ac4b10a1', '0045349c-69d9-4306-a403-c9c1fa836644', '00a2d166-78c9-4687-a195-3d6315c27574', '011b9b2d-ebe5-42bf-9662-d922faccc7a1', '01263518-5f7c-49dc-8d7e-84b0c03a6a63']
....

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
5-10
>>> 5 ['0130d616-885e-4a6c-9d03-2f17dd692a05', '01674b2c-5cf2-478f-84a1-f69c39f47bd4', '016caf42-4e19-4444-ab5d-6cf1e76c4afa', '01b9f68b-4de4-4374-b4f2-8a0685e18153', '01eef340-598c-4205-a990-cec190ac2ca5']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
10-15
>>> 5 ['01f50abf-fc15-446e-9d07-edeecc545a32', '029ce650-5e5a-4100-8596-cd94300e7ef5', '02bed00f-bef7-4fb7-b243-540354990e45', '02e6f999-24f2-4ad2-9b92-df3ee2b082e5', '02f5ae33-a563-4ecb-9e33-dfa500a44931']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
15-20
>>> 5 ['03565036-b6d3-432f-8d9a-7099818e0788', '035cb359-eac3-484a-9e88-3ddc739440a3', '03ab1e9f-4918-404d-b178-3a4fd929c5e8', '03da7a65-fa2f-42cb-a709-5fe8736f21d3', '045c13ef-3db7-4adf-b0a3-23338f0479f3']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
20-25
>>> 5 ['0491063c-14a7-4104-8002-1459126332f3', '04af44fc-c487-4005-b3cb-cb64815824a2', '05135396-df5c-49db-b34e-f4add5b65a2b', '05506f4c-e701-4a9d-ae06-97f066aade43', '058dcb78-bed1-40c3-a6c2-a0cc40065531']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
25-30
>>> 5 ['0685edd2-ce1c-4e0e-8dda-393139af4223', '06ef6e83-5583-45b9-a0bd-edea68943083', '0741b5db-4405-42ba-b63a-c6ee4f341480', '074e8b06-3929-4896-9263-3b80ad6a355b', '0772cdbe-8b0d-452b-8df1-bd70d1306363']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
30-35
>>> 5 ['0807435a-e75e-4e04-8e45-ed0cd49a841a', '084c6aec-94f7-4090-8f3f-59fa9e89721a', '08740d7f-5a5e-4dfa-bd48-7fbf228a7a28', '08da7c4c-3067-4bcf-9d7a-78566df72e69', '08de63a2-7b76-43c3-80dc-df748b1d81bc']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
35-40
>>> 5 ['095c7985-3842-494f-b591-706ad1cd2133', '09765b0a-94f6-47d2-af56-93368084ac3a', '09a5e9fd-d816-4f8c-baa9-0e40ba607b16', '09c2bc35-c21f-4aa4-ac30-0d8db02ad811', '0a017f15-1c6b-45e7-8d55-e0a71df1b2e8']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
40-45
>>> 5 ['0a229f95-0ea1-4d63-953e-74f5ec2f3028', '0a2a3529-f645-4967-9a58-89ee20b8bb62', '0b172e29-6166-4863-803d-a0a010887c11', '0b23b5fe-6c7e-4297-bc55-f93fcb830ac4', '0bc5744c-5fa3-45bb-87d0-70a02068b392']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
45-50
>>> 5 ['0c1023c0-d2ce-4940-8047-7642f1dc3965', '0c23c380-363c-474d-b64c-b47f612a8225', '0dc337fa-da8b-42c4-b9a7-fb76d81c161f', '0dca98b0-f43e-45b6-9a02-00092c78678c', '0dd8dbc1-c48b-4e7c-b401-57101f724967']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
50-55
>>> 5 ['0e1d0d46-7a7b-4538-95dd-b9fc20a15aec', '0ec70e40-07df-461d-8ff9-351240a0d454', '0ed9ad26-7fdc-4d75-93f9-d029eee94993', '0f64edec-0f1f-4025-8a53-75f9534f7828', '0f7ab21b-1fd0-45e0-9a47-17c4691eb84f']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
55-60
>>> 5 ['0fe1419e-a005-407c-8ae7-15c4c1579539', '1026e0bf-5640-4fa5-b65f-4f11e8e76b18', '10c9be1e-2cc0-45e4-8d2c-c013ea63ef05', '1111fb30-46ce-4722-98da-ec9ba2323d90', '1133b8a9-6b11-4511-b70a-f200e3b8b5db']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
60-65
>>> 5 ['115bc72c-116f-40c1-be9b-e3dd7650efae', '1174f6e4-ffbe-4e59-a000-8d861c968369', '1285eb55-415c-494a-aa58-936f0427cdd0', '128d198e-9b22-427c-90db-3714455f3a17', '12d31787-e54d-4729-ace8-9141043c92b8']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
65-70
>>> 5 ['1347c23d-8d6e-4c15-9461-640249838c96', '13b860c3-8048-4dc9-9eb0-7480bc660837', '13ca97a1-75bb-4a49-b8c3-181e5b2c9e86', '14b95463-2108-4921-afc2-e29eef52b18f', '14d1d84e-99e1-41ad-8892-3b4da3d4f948']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
70-75
>>> 5 ['1502c7d7-1535-4e56-9f34-30623acd50d5', '151f3677-6854-4265-9126-d92c646c67ae', '1549dc64-3dab-43fc-96e9-b07d520957e1', '1557183c-aedd-4df6-b98a-3654667f7b69', '157ec9e0-ca6e-4da1-9233-f976cf0db433']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
75-80
>>> 5 ['161917b8-88ad-407b-ade6-d6b98478b359', '16368c32-2118-4fcf-8693-6c89995e49d8', '16a8d916-ad46-4690-b1a5-3b2b323f4336', '174850b4-5ec2-462b-a890-89bd1716b3c2', '1783cac1-253a-40af-a9ac-48dfb20e1ab8']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
80-85
>>> 5 ['178b2c48-c07d-422e-ae17-8bcfd996ad51', '17baef7c-d97d-4b98-ab53-503ef856523d', '17c1d42c-cb84-4655-a4cd-b54bae17ecaf', '17ca61a2-607a-45ff-88fa-ef72e80bf891', '17d9e646-6ab3-40b3-a0bc-2c834d3c3213']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
85-90
>>> 5 ['17f275c1-a0d4-487d-8f02-ea279584b4cd', '189e1f27-7738-413a-a4d4-97d41d592a13', '18d35983-ea6a-4b70-a209-9bef37595956', '18eb4dfc-556f-4bf3-a411-4780209ed1e0', '195b6731-6ae6-416e-a345-0eb8874a0ca2']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
90-95
>>> 5 ['197428f7-bd77-4c5f-8119-87157b5c35b9', '197741de-a098-4f04-bb37-8ea8b3bb39bc', '1a18974d-967c-4727-b42e-12ae7be66589', '1c3610f7-e0aa-48d7-9a27-0dbaf6e244f9', '1c40b84e-a0e3-429f-a48c-21566cf881c0']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
95-100
>>> 5 ['1d27253f-b036-44e7-a04d-8da5bbf57419', '1d38d356-d126-4476-94d0-26616b9375b1', '1dafdd64-527d-4d46-bbdf-7a97774f881b', '1e68e760-a4cf-4100-bf9c-e50fa8d126f6', '1f8f87cb-8a0b-474c-97fb-c71b4fd88d97']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
100-105
>>> 5 ['1fef9454-b3e8-4d9d-a9aa-aa1f1a32b80c', '1ff85ada-3cdd-4afb-b311-2c7befb52702', '2021ed1f-dc75-4701-b8b8-1386466e4802', '20e8106b-1290-4735-abe4-7621e08e3dc8', '214a4507-d974-4b3e-8525-7408fccc6a0f']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
105-110
>>> 5 ['2192c1db-4718-4254-ba42-3ae7f30ad5a8', '2199b7a1-bd47-4bb5-b36a-a3e291e3e259', '21ef1730-e5a7-47ce-b419-d000bb59ae15', '22b35927-1c3f-4f98-ba42-deafc56b677a', '233b02f3-c4f0-4a67-9db5-e68d5cdaccb6']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
110-115
>>> 5 ['2399caeb-ead2-4003-af38-809db4ac2e2b', '23c21dea-3713-408f-ba56-f7c586e9f206', '23c31c2e-336c-4878-a476-cf8d811b4875', '23dabeef-8e3c-44bc-9a12-a9522d17be5c', '23e7a78a-1d56-4ad1-9bb4-72ec0178aff2']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
115-120
>>> 5 ['24046547-d038-4616-b190-52ac93f4965f', '241fffc8-4250-4cfa-b2e7-e68c33ae07dc', '24334ac1-28a3-4b61-b590-3f51e375b247', '24e39609-9645-43e5-960b-db5446eaea65', '2585edbd-3488-4100-a4ab-a161252a31ee']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
120-125
>>> 5 ['26573441-eedb-4364-966c-e7f803deef19', '2680da86-c977-4611-b75f-df015283c023', '271404de-24e8-43f6-806b-fb510c1124c4', '2779fa01-ac93-4e80-a997-3385f72172c3', '27ba717a-5cd8-440a-9345-4ae086f6efca']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
125-130
>>> 5 ['27dfb9d4-3a2c-44bc-9acf-8f638d3f3004', '281f70c5-876f-44b3-84fb-f2302f85e74c', '28e9048a-e540-42de-a1f4-4ef894fccc4c', '295cf595-4a29-46a3-a0c5-e5f08f947031', '298a1710-deb4-4064-a0f2-da32d43aa217']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
130-135
>>> 5 ['298d33da-15af-48cb-b30f-eaf54e7baa43', '29df128d-ace2-40cf-88ee-3f6f2170f159', '29fdc464-f216-4828-b456-829f71436e27', '2a84997d-ccee-4f46-bea2-752534f26416', '2b19a6b4-7a17-4452-b4aa-6fc18adc0c3c']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
135-140
>>> 5 ['2b22db1d-54a1-4b9e-a86e-a174cf51d95c', '2b36853f-34d3-47c5-ba6a-e5a93233d2b1', '2bcacfd1-6a45-4b96-9b80-2ad569b1ab45', '2c04a2f5-321e-4dea-8e00-268325da65cb', '2c86c3ea-d926-4d39-a5ae-39ece4774287']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
140-145
>>> 5 ['2c90d5e3-ac8c-4c86-a06f-42ccc064eb49', '2cf68894-168b-458b-af4f-53cad72989a8', '2d0d7ff4-7866-4ae1-9cf1-a3c7f4cbe48d', '2d4c778c-7f77-4f0a-8261-2086accf15fd', '2e1e3bf0-1708-4b65-936c-48b89eb8966a']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
145-150
>>> 5 ['2e32f31f-9817-4935-b259-96c59936ee33', '2e538802-2a31-4774-89a8-c6e4381a887d', '2e82e576-3095-4aee-9853-65f676647c34', '2e8e70f2-c781-44c2-8f12-1f8c2f536aa3', '2f4cbedf-ed7e-45a2-bf34-f1d1e696bdde']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
150-155
>>> 5 ['2fd36838-5a83-433e-ac80-b1f77448e5aa', '2fdfd287-d13c-4910-9788-73987d45908a', '2fe854b4-bac9-4801-9a1c-ee99388e8082', '30047d32-0833-4aca-98d1-3b9ab7122863', '303a1d77-a37a-4966-a4a4-9981d99ba1b4']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
155-160
>>> 5 ['30ec8b1f-28c4-4f46-8a1b-a8d51e558c7d', '3144f1fb-4342-4079-bfe8-940da4bfd88e', '316625b8-a217-4829-90d1-dfd9cb7e4bc3', '316e021c-5175-4ab3-bdb6-2bf9683f657a', '31c31cce-1b4d-4f12-922f-84f389403170']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
160-165
>>> 5 ['324bcba2-f6a4-45a6-807c-215bdffcca21', '327a2395-85c8-42e1-9638-8e037a1723ed', '328dfcb0-b5ae-43f2-bc87-dad0ab3df9e7', '32bc7cc4-d185-4594-bbee-4b96410be512', '32efa6e8-6b19-480a-9d04-ace02e93318a']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
165-170
>>> 5 ['332148f5-f070-4c20-8eb1-4d8c0673aa52', '332423a7-8866-4ee3-b08f-3c8d7c16af80', '33919e92-4ea9-47e5-a6f4-36e51845d50f', '33b7bf50-53f4-4839-aa83-9665f85671d8', '33cea538-4c3f-470a-972d-257c43241ab4']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
170-175
>>> 5 ['33fe5833-d7a0-43d7-a03d-56985ea448a6', '34a74805-300c-4773-ab59-2085fcc2e6cc', '34ab0cb8-bf19-4cbb-b4eb-3c45ee5aa60b', '3558dec7-eae3-4a41-a217-266c6a4535fb', '359f12f9-5c41-48a4-85bc-fd7e307bf7d8']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
175-180
>>> 5 ['35bd694d-1dd2-466f-ab27-03320614b40e', '360d1d6d-cf3e-4c78-b36f-ef5e3160aa6b', '36220587-1c1c-4f92-b177-3b2155e7e273', '36449392-de76-4ee9-bc09-627a07e18727', '36d77496-99f8-4911-ba7c-89fae32662aa']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
180-185
>>> 5 ['36fe6152-f61e-4948-9ccc-23ac01a9d77d', '376ffe63-efd7-42af-90e1-261255b28bb7', '378778d2-b331-4867-a93b-c64028c8b4c7', '3828b534-908e-4953-a3fb-07d01cf49c7d', '3886b4fb-ba22-4a50-b11a-a6893951f170']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
185-190
>>> 5 ['389e5b18-8f89-41a9-9fa5-efd4172836e2', '38a631a1-6875-4216-a335-ee93c90a86d6', '38a8b734-9acc-42f9-b5b7-e51b0dfc6504', '3927f736-3b5c-48c8-9d9e-83669ec44770', '398fb71b-ca83-44e7-bf0d-b1ca464b0283']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
190-195
>>> 5 ['39cde586-df95-435f-b9a6-73b0c0ee5e92', '39de7761-e762-4811-b95c-8216b79ae06b', '3a0775a0-61ae-43f2-b5f6-629a44355c2f', '3a711140-1b89-4611-9992-3861e3d0e01a', '3aaabc62-f5a4-4025-9b29-5adf82c86c84']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
195-200
>>> 5 ['3af31fcf-ad0c-4fd9-a8e3-10f9176b5e9d', '3afa1e93-1df8-4e4c-aaa4-557463f4bb77', '3b01d064-8c00-4972-9f07-407eac8e7534', '3b1f7e48-216d-47de-ba79-db350f52bff0', '3b7b9c1e-a84c-47ed-983c-9e4b00cbf01a']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
200-205
>>> 5 ['3bf81a9f-abb4-4495-a514-fd3865e13a03', '3c08aabd-d5b5-4bbe-857c-38a7527b2163', '3c612e12-6de8-44fa-a095-805c45474821', '3c8b5af9-c34d-43c2-b8c9-39ea11e44fa6', '3cb06c7a-f2a8-448b-91a8-dd201bbf2ddd']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
205-210
>>> 5 ['3dbe99d1-e3b8-4ee2-b6a8-2e2e12c6fbe9', '3e25056d-d137-49f5-abaa-f68509426600', '3e637872-f5e5-49d3-bb0d-9c16b8713382', '3e775c99-ceda-4246-8d6f-0f58ca5097c8', '3e9f93c0-aa79-4b4c-bd6c-b3325912362a']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
210-215
>>> 5 ['3ea9412b-429e-4dcf-90cd-c53be06885a1', '3ecb0147-276d-486c-9af0-ce437c24ba83', '3fc3755d-a3f8-4e2c-813f-ff124f2a75c1', '408cb583-6dc3-4698-8bd2-e284042bd5ef', '417dea5f-f68e-4dab-940e-43ae8c67e5e6']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
215-220
>>> 5 ['418c11e8-2670-48d5-bbf5-95b46bff1201', '42378dbc-a123-4cf9-8502-165e89fda271', '42621dfa-abfd-4c7d-8bc5-a02a09d1c2b4', '427d0648-3f77-4ffc-b52c-89855426d647', '42e47f3a-dff7-41e4-8f84-146d97e8ab72']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
220-225
>>> 5 ['42f6f503-4cf6-4a8e-b5fe-b44bccf6b38b', '43029932-feb0-4658-97fa-645c1e775009', '433427a1-bacf-4381-91ba-5fec8a0953f9', '43b3bf47-7313-4dfb-952a-ec0b9d48e16c', '43c0bec6-6fac-47b1-83cb-200a15a932be']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
225-230
>>> 5 ['43cc074d-b85a-4b0b-8feb-833094ffc565', '43d5632e-7272-4aad-9496-7f5a99671223', '441919eb-8c9f-478c-bda3-8de4f8295e8a', '444374f8-9282-439c-af00-0f828edcbff3', '44954053-0b93-4577-a436-42777e442300']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
230-235
>>> 5 ['44bec761-b603-49c0-8634-f6bfe0319bb1', '45013972-2dfd-4f82-a076-e3e4af1b43b8', '45c3975c-d333-4237-93f7-e12dc2451c38', '4649dee3-b668-44cd-ab97-3834de3ef8f8', '478eb8aa-50b8-4ce5-98e4-d518ede4b174']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
235-240
>>> 5 ['4842bac3-abaa-4900-871f-f2c3ba6457f5', '48ff0420-0f19-4e9d-a75d-6c54949a461a', '491b6364-1223-474f-816f-e248c8c841e2', '4922cddc-575c-4b8a-8245-ce5f6876760c', '4958c36f-1dc7-4f14-9dec-36e14107dbe3']
.

👉 Returned 436 / Total paginated 436
Table saved ((587, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-BRCA_subtype_'other'_tumor_'other'_subtype_tissue_'other'.tsv'
240-245
>>> 5 ['495f9eda-b9be-4eef-bae1-766a4bfbd68e', '49717f75-0f2d-4e1c-9a12-f1cd7877b80a', '4a032bad-e726-48f2-8f39-e3acc109cc91', '4a16429b-884f-4c95-8683-feeedf0d6a55', '4aa68586-6331-4795-b40c-859386640df6']
.

👉 Returned 436 / Total paginated 436

### Available sample types

In [33]:
df_samples.sample_type.unique()

array(['Primary Tumor', 'Blood Derived Normal', 'Solid Tissue Normal'],
      dtype=object)

In [32]:
df2 = df_samples[df_samples.sample_type == 'Primary Tumor']
print(len(df_samples), len(df2))
df2.head()

587 361

,case_id,submitter_id,sample_id,sample_type,barcode_id,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
0,01263518-5f7c-49dc-8d7e-84b0c03a6a63,TCGA-A8-A07W,5d1a5545-6934-41e5-b41b-8e0ee88e6ec6,Primary Tumor,TCGA-A8-A07W-01A,7ccc5a5b-d3f1-46da-8540-d8fbb7c6c06e,TCGA-A8-A07W-01A-01-TSA.eae41004-b3f5-4528-9e9...,Slide Image,SVS,TCGA-BRCA,other,other,other,Stage IV
1,01263518-5f7c-49dc-8d7e-84b0c03a6a63,TCGA-A8-A07W,5d1a5545-6934-41e5-b41b-8e0ee88e6ec6,Primary Tumor,TCGA-A8-A07W-01A,8f355183-b72c-407e-8f25-f5eec7f115cc,e06580e9-0b4a-48f7-9522-d54229aefb2d.rna_seq.t...,Aligned Reads,BAM,TCGA-BRCA,other,other,other,Stage IV
2,01263518-5f7c-49dc-8d7e-84b0c03a6a63,TCGA-A8-A07W,5d1a5545-6934-41e5-b41b-8e0ee88e6ec6,Primary Tumor,TCGA-A8-A07W-01A,e209288d-df03-4a61-a84f-eec243a2c43f,TCGA-BRCA.3e06faf7-1e08-4c15-9aee-8891de8cad5c...,Gene Level Copy Number,TSV,TCGA-BRCA,other,other,other,Stage IV
3,01263518-5f7c-49dc-8d7e-84b0c03a6a63,TCGA-A8-A07W,5d1a5545-6934-41e5-b41b-8e0ee88e6ec6,Primary Tumor,TCGA-A8-A07W-01A,aa89d193-05a1-4f7f-9291-b9cf646656de,e06580e9-0b4a-48f7-9522-d54229aefb2d.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-BRCA,other,other,other,Stage IV
4,01263518-5f7c-49dc-8d7e-84b0c03a6a63,TCGA-A8-A07W,5d1a5545-6934-41e5-b41b-8e0ee88e6ec6,Primary Tumor,TCGA-A8-A07W-01A,dd634319-6e80-4486-97b9-5d5fa3723a70,TCGA-BRCA.3cce14e4-4d6b-428c-812f-3716af4f855c...,Transcript Fusion,BEDPE,TCGA-BRCA,other,other,other,Stage IV

### GDC barcodes ~ submitter

In [34]:
barcodes = list(np.unique(df2.barcode_id))
len(barcodes)

11

In [35]:
barcodes

['TCGA-A1-A0SB-01A',
 'TCGA-A1-A0SB-01Z',
 'TCGA-A7-A26E-01A',
 'TCGA-A7-A26E-01B',
 'TCGA-A7-A26E-01Z',
 'TCGA-A8-A07W-01A',
 'TCGA-A8-A07W-01Z',
 'TCGA-AN-A0AM-01A',
 'TCGA-AN-A0AM-01Z',
 'TCGA-E2-A1IU-01A',
 'TCGA-E2-A1IU-01Z']

In [36]:
pid

'TCGA-BRCA'

In [37]:
mat = pid.lower().split('-')
study_id = mat[1] + '_' + mat[0]
print(">>>", study_id)

>>> brca_tcga

In [39]:
df_mut = gdc.get_mutations_from_samples(sample_ids=barcodes, study_id=study_id)
len(df_mut)

>>> https://www.cbioportal.org/api/molecular-profiles/brca_tcga_mutations/mutations/fetch

0

In [21]:
df_mut

Empty DataFrame
Columns: []
Index: []

In [40]:
sample_ids = barcodes

In [41]:
study_id

'brca_tcga'

In [ ]:
timeout = 60,
session: Optional[requests.Session] = None
url_cbioportal = "https://www.cbioportal.org/api"

sample_ids = [str(x).strip() for x in sample_ids if str(x).strip()]
if not sample_ids:
    raise ValueError("sample_ids is empty.")

molecular_profile_id = f"{study_id}_mutations"

http = session or requests.Session()

payload = {
    "sampleIds": sample_ids
}

headers = {
    "Accept": "application/json",
    "Content-Type": "application/json",
}

resp = http.post(url_cbioportal, json=payload, headers=headers, timeout=timeout)

# Helpful error message from cBioPortal
if not resp.ok:
    msg = ""
    try:
        msg = resp.json()
    except Exception:
        msg = resp.text

    raise RuntimeError(
        f"cBioPortal request failed: HTTP {resp.status_code} | "
        f"profile={molecular_profile_id} | details={msg}"
    )

data = resp.json()

df = pd.DataFrame(data)

# Optional: reorder a few common columns if present
cols = ["sampleId", "patientId", "studyId", "molecularProfileId","gene",
        "entrezGeneId", "proteinChange", "mutationType", "mutationStatus",
        "variantType", "chr", "startPosition", "endPosition",
        "referenceAllele", "tumorSeqAllele2",
]
# the selected cols + others not listed
cols = [c for c in cols if c in df.columns] + [c for c in df.columns if c not in cols]

NameError: name 'timeout' is not defined

In [ ]:
df[cols]