### TCGA / GDC Portal

https://portal.gdc.cancer.gov/

## GDC

https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/

### 🧠 Big picture (this is powerful)

- You’ve essentially built the backbone of:
- cBioPortal-like explorer
- cohort stratification engine
- patient-specific pipeline (your perturbation_agent 🔥)

### 💡 Flow

> project → subtypes  
> subtype → stages  
> stage → case_ids  
> case_id → file_ids

In [1]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [2]:
root_data = "/media/flavio/36873e3e-7941-48d7-aecb-45900ef92659/colaboracoes/tcga"

gdc = GDC(root_data=root_data)

### All programs

In [3]:
force=False
verbose=True

prog_list = gdc.list_gdc_progams(force=force, verbose=verbose)

# prog_list

File read at '/media/flavio/36873e3e-7941-48d7-aecb-45900ef92659/colaboracoes/tcga/programs'

### Get valid subtypes

facets = "diagnoses.primary_diagnosis"

### For each subtype → get stages

facets = "diagnoses.tumor_stage"

### For each (subtype, stage) → get samples

fields = "case_id,submitter_id,diagnoses.tumor_stage"

### Then → fetch RNA-seq files

endpoint = "/files"
field = "cases.case_id"

In [4]:
force=False
verbose=True

program = 'TCGA'

dfc = gdc.get_primary_sites(program=program, force=force, verbose=verbose)

dfc.head(3)

Table opened ((33, 3)) at '/media/flavio/36873e3e-7941-48d7-aecb-45900ef92659/colaboracoes/tcga/primary_site_program_TCGA.tsv'

,project_id,primary_site,disease_type
0,TCGA-ACC,['Adrenal gland'],['Adenomas and Adenocarcinomas']
1,TCGA-BLCA,['Bladder'],"['Epithelial Neoplasms, NOS', 'Squamous Cell N..."
2,TCGA-BRCA,['Breast'],"['Adnexal and Skin Appendage Neoplasms', 'Aden..."

### Subtypes

In [5]:
force=True
verbose=True

i=1
pid = dfc.iloc[i].project_id
primary_site = dfc.iloc[i].primary_site

print(pid, primary_site)

df_subt = gdc.build_subtypes(pid=pid, do_filter=True, force=force, verbose=verbose)

print(len(df_subt))
df_subt

TCGA-BLCA ['Bladder']
Table saved ((22, 5)) at '/media/flavio/36873e3e-7941-48d7-aecb-45900ef92659/colaboracoes/tcga/subtype_for_PS_TCGA-BLCA.tsv'
9

,project_id,subtype,n,is_valid,frac
0,TCGA-BLCA,transitional cell carcinoma,348,True,0.480000
1,TCGA-BLCA,papillary transitional cell carcinoma,76,True,0.104828
2,TCGA-BLCA,"papillary transitional cell carcinoma, non-inv...",66,True,0.091034
3,TCGA-BLCA,acinar adenocarcinoma,1,True,0.001379
4,TCGA-BLCA,basaloid squamous cell carcinoma,1,True,0.001379
5,TCGA-BLCA,merkel cell carcinoma,1,True,0.001379
6,TCGA-BLCA,papillary renal cell carcinoma,1,True,0.001379
7,TCGA-BLCA,"squamous cell carcinoma, clear cell type",1,True,0.001379
8,TCGA-BLCA,transitional cell carcinoma in situ,1,True,0.001379

### Stages

In [ ]:
force=True
verbose=True

i=1
subtype = df_subt.iloc[i].subtype_raw


print(pid, subtype)

df_stage = gdc.build_stages(pid=pid, subtype=subtype, force=force, verbose=verbose)

print(len(df_stage))
df_stage

TCGA-BLCA papillary transitional cell carcinoma
No stages found for TCGA-BLCA / papillary transitional cell carcinoma
0

Empty DataFrame
Columns: []
Index: []