In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv/perturb_agent
SRC added: /home/flavio/uv/perturb_agent/src

### Defaults

In [3]:
ROOT = Path().resolve().parent
root0 = ROOT / "data"

gdc = GDC(root0=root0)

os.listdir(root0)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'gdc_programs.txt']

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/gdc_programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.self.cancer.gov/projects'

In [7]:
prog_id = 'TCGA'
df_psi = gdc.get_primary_sites(prog_id=prog_id, force=force, verbose=verbose)

primary_sites = np.unique(df_psi.primary_site)
primary_sites[:10]

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/TCGA/primary_site_program_TCGA.tsv'

array(['Adrenal gland',
       'Adrenal gland, Retroperitoneum and peritoneum, Other endocrine glands and related structures, Other and ill-defined sites, Connective, subcutaneous and other soft tissues, Spinal cord, cranial nerves, and other parts of central nervous system, Heart, mediastinum, and pleura',
       'Bladder', 'Brain', 'Breast', 'Bronchus and lung',
       'Bronchus and lung, Heart, mediastinum, and pleura',
       'Cervix uteri, Ovary', 'Colon, Rectosigmoid junction',
       'Colon, Rectosigmoid junction, Rectum, Connective, subcutaneous and other soft tissues, Unknown'],
      dtype=object)

In [8]:
primary_site = 'Breast'
gdc.set_primary_site(primary_site = primary_site)

primary_site = gdc.primary_site
psi_id = gdc.psi_id

psi_id, primary_site

('TCGA-BRCA', 'Breast')

In [9]:
verbose=False

df_cases, df_all_samples, df_all_mut, all_barcode_list = gdc.get_filtered_tables(primary_site=primary_site, verbose=verbose)

In [10]:
df_cases.head(2)

,primary_site,disease_type,case_id,diagnoses,psi_id,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
0,Breast,Ductal and Lobular Neoplasms,c25898b4-eb33-42f4-bf3f-bf532a929e7d,"[{'primary_diagnosis': 'Lobular carcinoma, NOS...",TCGA-BRCA,lobular,unknown,"Lobular carcinoma, NOS",NaN,NaN,...,breast,ductal and lobular neoplasms,lobular carcinoma,other,epithelial,breast_lobular,ok,valid,1,0.000911
1,Breast,Ductal and Lobular Neoplasms,bb8d42d3-ad65-4d88-ae1d-f9aadfc7962d,"[{'primary_diagnosis': 'Lobular carcinoma, NOS...",TCGA-BRCA,lobular,unknown,"Lobular carcinoma, NOS",NaN,NaN,...,breast,ductal and lobular neoplasms,lobular carcinoma,other,epithelial,breast_lobular,ok,valid,1,0.000911

In [11]:
case_id_list = np.unique(df_cases.case_id)
print(len(case_id_list))

case_id_list[:3]

255

array(['00807dae-9f4a-4fd1-aac2-82eb11bf2afb',
       '00b11ca8-8540-4a3d-b602-ec754b00230b',
       '02bbb632-0f7f-439d-b8f0-c86a06237424'], dtype=object)

In [12]:
row = df_cases.iloc[0]

subtype_global = row.subtype_global
tumor_class = row.tumor_class
subtype_tissue = row.subtype_tissue

subtype_global, tumor_class, subtype_global

('lobular', 'other', 'lobular')

In [13]:
df_cases.head(3)

,primary_site,disease_type,case_id,diagnoses,psi_id,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
0,Breast,Ductal and Lobular Neoplasms,c25898b4-eb33-42f4-bf3f-bf532a929e7d,"[{'primary_diagnosis': 'Lobular carcinoma, NOS...",TCGA-BRCA,lobular,unknown,"Lobular carcinoma, NOS",NaN,NaN,...,breast,ductal and lobular neoplasms,lobular carcinoma,other,epithelial,breast_lobular,ok,valid,1,0.000911
1,Breast,Ductal and Lobular Neoplasms,bb8d42d3-ad65-4d88-ae1d-f9aadfc7962d,"[{'primary_diagnosis': 'Lobular carcinoma, NOS...",TCGA-BRCA,lobular,unknown,"Lobular carcinoma, NOS",NaN,NaN,...,breast,ductal and lobular neoplasms,lobular carcinoma,other,epithelial,breast_lobular,ok,valid,1,0.000911
2,Breast,Ductal and Lobular Neoplasms,2476dda9-da2a-4242-9642-b92b8b9b1c79,"[{'primary_diagnosis': 'Lobular carcinoma, NOS...",TCGA-BRCA,lobular,unknown,"Lobular carcinoma, NOS",NaN,NaN,...,breast,ductal and lobular neoplasms,lobular carcinoma,other,epithelial,breast_lobular,ok,valid,1,0.000911

### Preparing to get VCF files from TCGA programa

In [14]:
case_id_list = np.unique(df_cases.case_id)
print(len(case_id_list))

row = df_cases.iloc[0]

subtype_global = row.subtype_global
tumor_class = row.tumor_class
subtype_tissue = row.subtype_tissue

print(subtype_global, tumor_class, subtype_global)

255
lobular other lobular

In [ ]:
verbose=True
force=False

df_vcf = gdc.get_VCF_files(subtype_global=subtype_global, tumor_class=tumor_class, subtype_tissue=subtype_tissue, 
                       batch_cases=20, batch_size=20, timeout=120, force=force, verbose=verbose)

print(len(df_vcf))

Table opened ((1098, 23)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/cases_for_TCGA-BRCA.tsv'
>>> 1098 cases
Table opened ((354, 14)) at '/home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/vcf_files_for_TCGA-BRCA_Breast_subtype_lobular_tumor_other_subtype_tissue_breast_lobular.tsv'
354

In [16]:
df_vcf.head(3).T

,0,1,2
case_id,0c1023c0-d2ce-4940-8047-7642f1dc3965,0c1023c0-d2ce-4940-8047-7642f1dc3965,0c1023c0-d2ce-4940-8047-7642f1dc3965
submitter_id,TCGA-BH-A0HB,TCGA-BH-A0HB,TCGA-BH-A0HB
sample_id,19193b8f-1e1b-448c-b934-93f25e60d45b,19193b8f-1e1b-448c-b934-93f25e60d45b,19193b8f-1e1b-448c-b934-93f25e60d45b
sample_type,Primary Tumor,Primary Tumor,Primary Tumor
barcode_sample,TCGA-BH-A0HB-01A,TCGA-BH-A0HB-01A,TCGA-BH-A0HB-01A
file_id,a27f1856-e4b3-4e0c-a285-0a21ff68219c,41253061-634e-4b6c-933c-87f27f88fb35,c51a4a1d-3931-4ae5-be01-db9a4c92af9c
file_name,71e0809f-c79f-4f48-935b-14b0b58d60e9.svaba.som...,TCGA-BRCA.f4c82250-7bba-4a41-87a0-93f97573baab...,06857ea5-33b5-45b8-9795-a8f68197af2a.svaba.som...
data_type,Raw Simple Somatic Mutation,Raw Simple Somatic Mutation,Raw Simple Somatic Mutation
data_format,VCF,VCF,VCF
workflow_type,SvABA Indel,GATK4 MuTect2,SvABA Indel
psi_id,TCGA-BRCA,TCGA-BRCA,TCGA-BRCA
subtype_global,lobular,lobular,lobular
tumor_class,other,other,other
subtype_tissue,breast_lobular,breast_lobular,breast_lobular

In [17]:
np.unique(df_vcf.data_type)

array(['Raw Simple Somatic Mutation'], dtype=object)

In [ ]:
verbose=True
force=False

row = df_vcf.iloc[0]

data_type = row.data_type
case_id = row.case_id
file_id = row.file_id

filename = gdc.get_table_given_fileID(file_type=data_type, case_id=case_id, file_id=file_id, force=force, verbose=verbose)
filename

### Development & tests

In [ ]:
def get_VCF_files(subtype_global:str, tumor_class:str, subtype_tissue:str, 
			    batch_cases:int=50, batch_size:int=200, timeout:int=100,
			    force:bool=False, verbose:bool=False) -> pd.DataFrame:

    df_vcf = pd.DataFrame()
    gdc.df_vcf = df_vcf

    gdc.set_s_case(subtype_global, tumor_class, subtype_tissue)

    df_cases, _, _ = gdc.get_cases_and_subtypes(batch_size=batch_size, do_filter=False, 
                                                force=False, verbose=verbose)

    gdc.df_cases = df_cases

    if df_cases is None or df_cases.empty:
        print(f"No cases found while searching for '{gdc.s_case}'")
        return df_vcf
          
    case_id_list = list(df_cases.case_id)
    case_id_list.sort()

    N_cases = len(case_id_list)
    print(f">>> {N_cases} cases")

    gdc.fname_vcf_files0 = 'vcf_files_for_%s.tsv'
    fname = gdc.fname_vcf_files0%(gdc.s_case)
    fname = title_replace(fname)
    filename = os.path.join(gdc.root_psi, fname)

    #-------------------------- batch loop ---------------------------
    all_hits = []
    from_ = 0

    size_ = batch_size
    total = None

    # print("Searching: ", end='')

    ini = -batch_cases
    end = 0

    while(True):
        ini += batch_cases
        end += batch_cases

        if ini >= N_cases:
            break
        
        if end > N_cases:
            end = N_cases

        print(f"{ini}-{end} ", end='')

        lista = case_id_list[ini: end]

        print('>>> 0a')
        filters = {
            "op": "and",
            "content": [
                {"op": "in",
                    "content": {"field": "cases.case_id", "value": lista}
                },
                {"op": "=",
                    "content": {"field": "files.data_format", "value": "VCF"}
                },
                {"op": "in",
                    "content": {"field": "files.data_type",
                                "value": [
                                    "Raw Simple Somatic Mutation",
                                    "Masked Somatic Mutation"
                                ]
                    }
                }
            ]
        }
    
        try:
            while True:
                print(".", end='')

                params = {
                    "filters": json.dumps(filters),
                    "fields": ",".join([
                        "file_id",
                        "file_name",
                        "data_type",
                        "data_format",
                        "analysis.workflow_type",
                        "cases.case_id",
                        "cases.submitter_id",
                        "cases.samples.sample_id",
                        "cases.samples.submitter_id",
                        "cases.samples.sample_type",
                    ]),
                    "format": "JSON",
                    "size": size_,
                    "from": from_
                }
                
                res = requests.get(gdc.url_gdc_files, params=params, timeout=timeout)
                """
                res.raise_for_status()   # raises if HTTP 4xx/5xx
                print("status:", res.status_code)
                print("content-type:", res.headers.get("Content-Type"))
                print("text:", res.text[:500])   # inspect response before parsing
                """
                response = res.json()

                if 'data' not in response.keys():
                    print(f"No data found while searching for '{gdc.psi_id}' cases {case_id_list}")
                    print(">>> response", response)
                    return df_vcf
            
                hits = response.get("data", {}).get("hits", [])

                if total is None:
                    total = response["data"]["pagination"]["total"]
                
                if not hits:
                    break

                all_hits.extend(hits)
                from_ += size_

            print("\n")

            if all_hits == []:
                print(f"No files were found for {psi_id} cases {case_id_list}")
                return df_vcf

            #------------ lost data? ------------------
            N = len(all_hits)

            if N < total:
                print(f"⚠️ Warning: results truncated — consider pagination - all hits = {N};  Total paginated {total} ")
            else:
                if verbose: print(f"👉 Returned {N} / Total paginated {total}")

            #------------ having all hits -------------
            records = []
            print('>>> 2')

            for hit in all_hits:
                for case in hit.get("cases", []):
                    for sample in case.get("samples", []):
                        records.append({
                            "case_id": case["case_id"],
                            "submitter_id": case["submitter_id"],
                            "sample_id":   sample["sample_id"],
                            "sample_type": sample["sample_type"],
                            "barcode_sample":  sample["submitter_id"],
                            "file_id":    hit["file_id"],
                            "file_name":  hit["file_name"],
                            "data_type":  hit["data_type"],
                            "data_format": hit["data_format"],
                            "workflow_type": hit["analysis"]["workflow_type"],
                        })
                        print('>>> 3')

            df_vcf = pd.DataFrame(records)
            cols = list(df_vcf.columns)

            # 🔹 Metadata 
            df_vcf['psi_id'] = psi_id
            df_vcf['subtype_global'] = subtype_global
            df_vcf['tumor_class'] = tumor_class
            df_vcf['subtype_tissue'] = subtype_tissue

            cols = ["psi_id", "subtype_global", "tumor_class", "subtype_tissue"] + cols

            df_vcf = df_vcf.sort_values(["case_id", "sample_type"], ascending=[False,False]).reset_index(drop=True)
            df_vcf.reset_index(drop=True, inplace=True)

            _ = pdwritecsv(df_vcf, fname, gdc.root_psi, verbose=verbose)

        except Exception as e:
            print(f"Error for searching files for {gdc.s_case}'. error: {e}")
            print("Trye to diminish the batch size - like ~20")
            return df_vcf

    gdc.df_vcf = df_vcf

    return df_vcf

In [ ]:
run_here = True

hits = []

if run_here:
    lista = list(case_id_list[:3])

    filters = {
        "op": "and",
        "content": [
            {"op": "in",
                "content": {"field": "cases.case_id", "value": lista}
            },
            {"op": "=",
                "content": {"field": "files.data_format", "value": "VCF"}
            },
            {"op": "in",
                "content": {"field": "files.data_type",
                            "value": [
                                "Raw Simple Somatic Mutation",
                                "Masked Somatic Mutation"
                            ]
                }
            }
        ]
    }

    params = {
        "filters": json.dumps(filters),
        "fields": ",".join([
            "file_id",
            "file_name",
            "data_type",
            "data_format",
            "analysis.workflow_type",
            "cases.case_id",
            "cases.submitter_id",
            "cases.samples.sample_id",
            "cases.samples.submitter_id",
            "cases.samples.sample_type",
        ]),
        "format": "JSON",
        "size": 2000
    }

    res = requests.get(gdc.url_gdc_files, params=params)

    response = res.json()

    if 'data' not in response.keys():
        print(f"No data found while searching for '{gdc.psi_id}' cases {case_id_list}")
        print(">>> response", response)
        hits = []
    else:
        hits = response.get("data", {}).get("hits", [])

    print(len(hits))
    hits[:3]

if hits:

    records = []

    for hit in hits:
        for case in hit.get("cases", []):
            for sample in case.get("samples", []):
                records.append({
                    "case_id": case["case_id"],
                    "submitter_id": case["submitter_id"],
                    "sample_id":   sample["sample_id"],
                    "sample_type": sample["sample_type"],
                    "barcode_sample":  sample["submitter_id"],
                    "file_id":    hit["file_id"],
                    "file_name":  hit["file_name"],
                    "data_type":  hit["data_type"],
                    "data_format": hit["data_format"],
                    "workflow_type": hit["analysis"]["workflow_type"],
                })

    df_vcf = pd.DataFrame(records)
    cols = list(df_vcf.columns)

    # 🔹 Metadata 
    df_vcf['psi_id'] = psi_id
    df_vcf['subtype_global'] = subtype_global
    df_vcf['tumor_class'] = tumor_class
    df_vcf['subtype_tissue'] = subtype_tissue
    # df_vcf['stage'] = gdc.get_stage_from_cases(df_vcf.case_id.tolist())

    cols = ["psi_id", "subtype_global", "tumor_class", "subtype_tissue", "stage"] + cols

    df_vcf = df_vcf.sort_values(["case_id", "sample_type"], ascending=[False,False]).reset_index(drop=True)
    df_vcf.reset_index(drop=True, inplace=True)