In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [3]:
root0 = '../data'
root0 = Path(root0)

gdc = GDC(root0=root0)

os.listdir(root0)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'gdc_programs.txt']

In [4]:
os.listdir(gdc.root_data)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'gdc_programs.txt']

### Get all programs

In [5]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

np.array(prog_list)

File read at './../data/gdc_programs.txt'

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
prog_id = 'TCGA'

df_psi = gdc.get_primary_sites(prog_id=prog_id, force=False, verbose=verbose)
print(len(df_psi))

df_psi.head(3)

Table opened ((33, 5)) at '../data/TCGA/primary_site_program_TCGA.tsv'
33

,psi_id,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma

In [8]:
term = 'TCGA_UCEC'

gdc.df_psi[gdc.df_psi.psi_id == 'TCGA-GBM']

,psi_id,primary_site,project_id,disease_type,name
4,TCGA-GBM,Brain,TCGA-GBM,"Not Reported, Gliomas",Glioblastoma Multiforme

In [9]:
i = 3

psi_id = df_psi.iloc[i].psi_id
gdc.set_primary_site(psi_id=psi_id)

gdc.psi_id, gdc.primary_site, gdc.disease_type, gdc.disease_name, gdc.root_psi

('TCGA-LGG', 'Brain', 'Gliomas', 3, PosixPath('../data/TCGA/TCGA-LGG'))

In [10]:
primary_site = df_psi.iloc[i].primary_site
gdc.set_primary_site(primary_site=primary_site)

gdc.psi_id, gdc.primary_site, gdc.disease_type, gdc.disease_name, gdc.root_psi

('TCGA-LGG', 'Brain', 'Gliomas', 3, PosixPath('../data/TCGA/TCGA-LGG'))

In [ ]:
for i, row in df_psi.iterrows():
    primary_site = row.primary_site
    print(">>>", primary_site)

    df_cases, df_samples, df_mut, barcode_list = gdc.get_filtered_tables(primary_site=primary_site)

    print('-->', len(df_cases), len(df_samples), len(df_mut), len(barcode_list), '\n')

>>> Adrenal gland
No mutation analysis file found for: TCGA-ACC_Adrenal_gland_subtype_sarcoma_tumor_sarcoma_subtype_tissue_sarcoma
Adrenal gland 90 5453 10778 51
>>> Adrenal gland, Retroperitoneum and peritoneum, Other endocrine glands and related structures, Other and ill-defined sites, Connective, subcutaneous and other soft tissues, Spinal cord, cranial nerves, and other parts of central nervous system, Heart, mediastinum, and pleura
Adrenal gland, Retroperitoneum and peritoneum, Other endocrine glands and related structures, Other and ill-defined sites, Connective, subcutaneous and other soft tissues, Spinal cord, cranial nerves, and other parts of central nervous system, Heart, mediastinum, and pleura 3 151 26 3
>>> Bladder
Bladder 34 7988 41267 34
>>> Brain
No cases found for primary site: Brain
No samples found for primary site: Brain
No mutations found for primary site: Brain
No barcodes found for primary site: Brain
Brain 0 0 0 0
>>> Brain
No cases found for primary site: Brain
No samples found for primary site: Brain
No mutations found for primary site: Brain
No barcodes found for primary site: Brain
Brain 0 0 0 0
>>> Breast
Breast 255 5747 3759 82
>>> Bronchus and lung
Bronchus and lung 413 25781 147588 57
>>> Bronchus and lung
Bronchus and lung 413 25781 147588 57
>>> Bronchus and lung, Heart, mediastinum, and pleura
Bronchus and lung, Heart, mediastinum, and pleura 2 110 4 2
>>> Cervix uteri, Ovary
Cervix uteri, Ovary 300 10835 16225 105
>>> Colon, Rectosigmoid junction
Colon, Rectosigmoid junction 394 30844 263311 63
>>> Colon, Rectosigmoid junction, Rectum, Connective, subcutaneous and other soft tissues, Unknown
Colon, Rectosigmoid junction, Rectum, Connective, subcutaneous and other soft tissues, Unknown 157 30456 103452 51
>>> Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
No cases found for primary site: Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
No samples found for primary site: Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
No mutations found for primary site: Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
No barcodes found for primary site: Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands 0 0 0 0
>>> Colon, Spinal cord, cranial nerves, and other parts of central nervous system, Vulva, Skin, Vagina, Bones, joints and articular cartilage of other and unspecified sites, Small intestine, Connective, subcutaneous and other soft tissues, Nasal cavity and middle ear, Anus and anal canal, Liver and intrahepatic bile ducts, Bronchus and lung, Other and ill-defined sites, Adrenal gland, Corpus uteri, Parotid gland, Retroperitoneum and peritoneum, Breast, Lymph nodes, Brain
Error: could not filter df_samples
Colon, Spinal cord, cranial nerves, and other parts of central nervous system, Vulva, Skin, Vagina, Bones, joints and articular cartilage of other and unspecified sites, Small intestine, Connective, subcutaneous and other soft tissues, Nasal cavity and middle ear, Anus and anal canal, Liver and intrahepatic bile ducts, Bronchus and lung, Other and ill-defined sites, Adrenal gland, Corpus uteri, Parotid gland, Retroperitoneum and peritoneum, Breast, Lymph nodes, Brain 2 1 696 1
>>> Esophagus, Stomach
Esophagus, Stomach 178 33578 68718 100
>>> Eye and adnexa
No cases found for primary site: Eye and adnexa
No samples found for primary site: Eye and adnexa
No mutations found for primary site: Eye and adnexa
No barcodes found for primary site: Eye and adnexa
Eye and adnexa 0 0 0 0
>>> Hematopoietic and reticuloendothelial systems
No cases found for primary site: Hematopoietic and reticuloendothelial systems
No samples found for primary site: Hematopoietic and reticuloendothelial systems
No mutations found for primary site: Hematopoietic and reticuloendothelial systems
No barcodes found for primary site: Hematopoietic and reticuloendothelial systems
Hematopoietic and reticuloendothelial systems 0 0 0 0
>>> Kidney
Kidney 2 224 64 2
>>> Kidney
Kidney 2 224 64 2
>>> Kidney
Kidney 2 224 64 2
>>> Lip, Tonsil, Gum, Bones, joints and articular cartilage of other and unspecified sites, Palate, Other and unspecified parts of tongue, Floor of mouth, Other and ill-defined sites in lip, oral cavity and pharynx, Larynx, Base of tongue, Other and unspecified parts of mouth, Oropharynx, Hypopharynx
Lip, Tonsil, Gum, Bones, joints and articular cartilage of other and unspecified sites, Palate, Other and unspecified parts of tongue, Floor of mouth, Other and ill-defined sites in lip, oral cavity and pharynx, Larynx, Base of tongue, Other and unspecified parts of mouth, Oropharynx, Hypopharynx 510 22808 50944 51
>>> Liver and intrahepatic bile ducts
Liver and intrahepatic bile ducts 14 1509 3075 14
>>> Liver and intrahepatic bile ducts, Other and unspecified parts of biliary tract, Pancreas
No mutation analysis file found for: TCGA-CHOL_Liver_and_intrahepatic_bile_ducts_Other_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_tissue_adenocarcinoma_generic
Liver and intrahepatic bile ducts, Other and unspecified parts of biliary tract, Pancreas 2 85 42 2
>>> Pancreas
Pancreas 32 1868 1033 32
>>> Prostate gland
Prostate gland 291 2785 7690 55
>>> Retroperitoneum and peritoneum, Colon, Other and unspecified male genital organs, Bones, joints and articular cartilage of limbs, Meninges, Stomach, Other and unspecified parts of tongue, Connective, subcutaneous and other soft tissues, Uterus, NOS, Kidney, Peripheral nerves and autonomic nervous system, Ovary, Corpus uteri
Retroperitoneum and peritoneum, Colon, Other and unspecified male genital organs, Bones, joints and articular cartilage of limbs, Meninges, Stomach, Other and unspecified parts of tongue, Connective, subcutaneous and other soft tissues, Uterus, NOS, Kidney, Peripheral nerves and autonomic nervous system, Ovary, Corpus uteri 222 2922 3901 54
>>> Retroperitoneum and peritoneum, Ovary
No mutation analysis file found for: TCGA-OV_Retroperitoneum_and_peritoneum_Ovary_subtype_serous_tumor_other_subtype_tissue_serous
Retroperitoneum and peritoneum, Ovary 561 2433 3364 55
>>> Stomach
Stomach 352 35532 201708 50
>>> Testis
No cases found for primary site: Testis
No samples found for primary site: Testis
No mutations found for primary site: Testis
No barcodes found for primary site: Testis
Testis 0 0 0 0
>>> Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
No cases found for primary site: Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
No samples found for primary site: Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
No mutations found for primary site: Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
No barcodes found for primary site: Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura 0 0 0 0
>>> Thyroid gland
Thyroid gland 353 19273 4332 58
>>> Uterus, NOS, Corpus uteri
Uterus, NOS, Corpus uteri 10 541 497 10
>>> Uterus, NOS, Corpus uteri
Uterus, NOS, Corpus uteri 10 541 497 10

In [ ]:
gdc.s_case

In [ ]:
gdc.df_cases

In [ ]:

def move_tables(primary_site: str,  verbose: bool=False):

    dfa = gdc.df_psi[gdc.df_psi.primary_site == primary_site]

    if dfa.empty:
        gdc.psi_id = ''
        print("No primary site information found for:", primary_site)
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), []
    
    row = dfa.iloc[0]
    gdc.set_primary_site(psi_id = row.pid)

    lista = [x for x in os.listdir(gdc.root_data) if f'_{gdc.psi_id}' in x]

    print(gdc.psi_id, len(lista))

    for fname in lista:
        filename_ori = gdc.root_data / fname
        filename_dest = gdc.root_psi / fname

        shutil.move(filename_ori, filename_dest)


for i, row in df_psi.iterrows():
    primary_site = row.primary_site
    print(">>>", primary_site)

    move_tables(primary_site)