In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv/perturb_agent
SRC added: /home/flavio/uv/perturb_agent/src

### Defaults

In [3]:
ROOT = Path().resolve().parent
root0 = ROOT / "data"

gdc = GDC(root0=root0)

os.listdir(root0)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'gdc_programs.txt']

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/gdc_programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=False

prog_id = 'TCGA'

gdc.set_program(prog_id)
df_psi = gdc.get_primary_sites(prog_id=prog_id, force=False, verbose=verbose)

i=0
primary_site = df_psi.iloc[i].primary_site
gdc.set_primary_site(primary_site=primary_site)

True

In [8]:
df_psi.loc[:, ('psi_id', 'primary_site')]

       psi_id                                       primary_site
0    TCGA-ACC                                      Adrenal gland
1   TCGA-PCPG  Adrenal gland, Retroperitoneum and peritoneum,...
2   TCGA-BLCA                                            Bladder
3    TCGA-LGG                                          Brain LGG
4    TCGA-GBM                                          Brain GBM
5   TCGA-BRCA                                        Breast BRCA
6   TCGA-LUAD                           Bronchus and lung – LUAD
7   TCGA-LUSC                           Bronchus and lung – LUSC
8   TCGA-MESO  Bronchus and lung, Heart, mediastinum, and pleura
9   TCGA-CESC                                Cervix uteri, Ovary
10  TCGA-COAD                Colon, Rectosigmoid junction – COAD
11  TCGA-READ  Colon, Rectosigmoid junction, Rectum, Connecti...
12  TCGA-DLBC  Colon, Retroperitoneum and peritoneum, Heart, ...
13  TCGA-SKCM  Colon, Spinal cord, cranial nerves, and other ...
14  TCGA-ESCA                                 Esophagus, Stomach
15   TCGA-UVM                                     Eye and adnexa
16  TCGA-LAML      Hematopoietic and reticuloendothelial systems
17  TCGA-KICH                                      Kidney – KICH
18  TCGA-KIRP                                      Kidney – KIRP
19  TCGA-KIRC                                      Kidney – KIRC
20  TCGA-HNSC  Lip, Tonsil, Gum, Bones, joints and articular ...
21  TCGA-LIHC           Liver and intrahepatic bile ducts – LIHC
22  TCGA-CHOL    Liver and intrahepatic bile ducts, other – CHOL
23  TCGA-PAAD                                           Pancreas
24  TCGA-PRAD                                     Prostate gland
25  TCGA-SARC  Retroperitoneum and peritoneum, Colon, Other a...
26    TCGA-OV              Retroperitoneum and peritoneum, Ovary
27  TCGA-STAD                                            Stomach
28  TCGA-TGCT                                             Testis
29  TCGA-THYM  Thymus, Other and ill-defined sites, Heart, me...
30  TCGA-THCA                                      Thyroid gland
31   TCGA-UCS                    Uterus, NOS, Corpus uteri – UCS
32  TCGA-UCEC                   Uterus, NOS, Corpus uteri – UCEC

In [ ]:
verbose=False

i=0
primary_site = df_psi.iloc[i].primary_site
print(">>", primary_site, end=" ")

cluster_type='UMAP'

dfw, dfh, dfstat, dfpiv = gdc.entropy_analysis_for_primary_site(cluster_type=cluster_type, primary_site=primary_site, Kmin=2, Kmax=10, min_barcodes=3, min_genes=5, verbose=verbose)

print(len(dfw))

print("\n----------- end ------------")

dfw

>> Breast BRCA Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_lobular_tumor_other_subtype_tissue_breast_lobular.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_ductal_tumor_adenocarcinoma_subtype_tissue_breast_ductal.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_clear_cell_tumor_other_subtype_tissue_clear_cell.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_ductal_tumor_other_subtype_tissue_breast_ductal.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_adenocarcinoma_generic_tumor_adenocarcinoma_subtype_tissue_adenocarcinoma_generic.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_ductal_tumor_other_subtype_tissue_breast_ductal.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_ductal_tumor_other_subtype_tissue_breast_ductal.tsv
Error: could not find samples file: /home/flavio/uv/perturb_agent/data/TCGA/TCGA-BRCA/samples_for_TCGA-BRCA_Breast_BRCA_subtype_neuroendocrine_tumor_neuroendocrine_tumor_subtype_tissue_neuroendocrine.tsv
No samples found for primary site: Breast BRCA
No mutations found for primary site: Breast BRCA
No barcodes found for primary site: Breast BRCA
0

----------- end ------------

Empty DataFrame
Columns: []
Index: []

In [ ]:
fig, embedding, labels = gdc.plot_HDBSCAN(dfpiv, k=8, figsize=(14, 10))

In [10]:
print(dfpiv.shape)

dfpiv.iloc[:30, :15]

(0, 0)

Empty DataFrame
Columns: []
Index: []

In [11]:
dfpiv.sum(axis=0)

Series([], dtype: float64)

In [12]:
gdc.dfpiv.shape

AttributeError: 'GDC' object has no attribute 'dfpiv'

In [ ]:
gdc.dfpiv