In [1]:
!python --version

Python 3.11.14

In [2]:
import os
import sys
from pathlib import Path

import pandas as pd

ROOT = Path().resolve().parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.Basic import *
from libs.tcga_gdc_lib import *

ROOT: /home/flavio/uv/perturb_agent
SRC added: /home/flavio/uv/perturb_agent/src

### Defaults

In [3]:
root0 = ROOT / "data"
gdc = GDC(root0=root0)

os.listdir(root0)[:10]

['cancer',
 'reactome_summary.tsv',
 'reactome',
 'vector_store',
 'reactome_pathways.tsv',
 'TCGA',
 'gdc_programs.txt']

### Get all programs

In [4]:
force = False
verbose = True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/gdc_programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.self.cancer.gov/projects'

In [7]:
prog_id = "TCGA"
df_psi = gdc.get_primary_sites(prog_id=prog_id, force=force, verbose=verbose)

psi_id_list = np.unique(df_psi.psi_id)
psi_id_list

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/TCGA/primary_site_program_TCGA.tsv'

array(['TCGA-ACC', 'TCGA-BLCA', 'TCGA-BRCA', 'TCGA-CESC', 'TCGA-CHOL',
       'TCGA-COAD', 'TCGA-DLBC', 'TCGA-ESCA', 'TCGA-GBM', 'TCGA-HNSC',
       'TCGA-KICH', 'TCGA-KIRC', 'TCGA-KIRP', 'TCGA-LAML', 'TCGA-LGG',
       'TCGA-LIHC', 'TCGA-LUAD', 'TCGA-LUSC', 'TCGA-MESO', 'TCGA-OV',
       'TCGA-PAAD', 'TCGA-PCPG', 'TCGA-PRAD', 'TCGA-READ', 'TCGA-SARC',
       'TCGA-SKCM', 'TCGA-STAD', 'TCGA-TGCT', 'TCGA-THCA', 'TCGA-THYM',
       'TCGA-UCEC', 'TCGA-UCS', 'TCGA-UVM'], dtype=object)

In [8]:
psi_id = "TCGA-LUAD"

gdc.set_primary_site(psi_id=psi_id)

primary_site = gdc.primary_site
psi_id = gdc.psi_id

psi_id, primary_site

('TCGA-LUAD', 'Bronchus and lung')

In [9]:
verbose = False

df_cases, df_tumor_samples, df_tummor_mut, tumor_barcode_list = gdc.get_filtered_tables(
    psi_id=psi_id, sample_type_term="Primary Tumor", verbose=verbose
)

In [10]:
verbose = False

df_cases, df_normal_samples, df_normal_mut, normal_barcode_list = gdc.get_filtered_tables(
    psi_id=psi_id, sample_type_term="Solid Tissue Normal", verbose=verbose
)

In [11]:
df_cases.head(2)

,primary_site,disease_type,case_id,diagnoses,psi_id,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,primary_site_norm,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac
0,Bronchus and lung,Adenomas and Adenocarcinomas,07b5663f-9a54-4462-b6c1-6fc8116b8714,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-LUAD,adenocarcinoma_generic,Stage IA,"Adenocarcinoma, NOS",NaN,NaN,...,bronchus and lung,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,lung_adenocarcinoma,ok,valid,1,0.001709
1,Bronchus and lung,Adenomas and Adenocarcinomas,ebb33753-9d38-4368-9033-3e55f129d00d,[{'primary_diagnosis': 'Adenocarcinoma with mi...,TCGA-LUAD,adenocarcinoma_generic,unknown,Adenocarcinoma with mixed subtypes,NaN,NaN,...,bronchus and lung,adenomas and adenocarcinomas,adenocarcinoma with mixed subtypes,adenocarcinoma,epithelial,lung_adenocarcinoma,ok,valid,1,0.001709

In [12]:
df_normal_samples.head(3)

,case_id,submitter_id,sample_id,sample_type,barcode_sample,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
0,2483621a-4db3-41ab-aa33-b9427ea8a0af,TCGA-38-4631,ff565f35-43c7-4694-b7d0-70f440732b1c,Solid Tissue Normal,TCGA-38-4631-11A,65c5ead3-ec7a-4f6e-90db-26bdd602ecbf,6bc28c73-b8f0-4af3-801a-075cc29cf49b.wxs.pinde...,Raw Simple Somatic Mutation,VCF,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB
1,2483621a-4db3-41ab-aa33-b9427ea8a0af,TCGA-38-4631,ff565f35-43c7-4694-b7d0-70f440732b1c,Solid Tissue Normal,TCGA-38-4631-11A,a41a3a0d-1cb8-4592-8986-4724403e8777,BURST_p_TCGA_b119_SNP_N_GenomeWideSNP_6_D06_78...,Copy Number Segment,TXT,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB
2,2483621a-4db3-41ab-aa33-b9427ea8a0af,TCGA-38-4631,ff565f35-43c7-4694-b7d0-70f440732b1c,Solid Tissue Normal,TCGA-38-4631-11A,374e13e1-98a8-4b65-94da-0d78ae51df5a,14826ad4-fe64-4f31-bb3e-8e2d57ad7f5f.wxs.aliqu...,Masked Somatic Mutation,MAF,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB

In [13]:
df_tumor_samples.groupby(["sample_type", "data_format", "data_format"]).size()

sample_type    data_format  data_format
Primary Tumor  BAM          BAM            2968
               BEDPE        BEDPE          1624
               CEL          CEL             492
               IDAT         IDAT           1008
               MAF          MAF            3168
               PDF          PDF             465
               SVS          SVS            1270
               TAR          TAR             347
               TSV          TSV            4055
               TXT          TXT            3671
               VCF          VCF            6713
dtype: int64

In [14]:
df_normal_samples.groupby(["sample_type", "data_format", "data_format"]).size()

sample_type          data_format  data_format
Solid Tissue Normal  BAM          BAM             799
                     BEDPE        BEDPE           384
                     CEL          CEL             244
                     IDAT         IDAT            234
                     MAF          MAF            1140
                     SVS          SVS             326
                     TAR          TAR              92
                     TSV          TSV             943
                     TXT          TXT            1106
                     VCF          VCF            2108
dtype: int64

### Cases with normal tissue

In [15]:
np.unique(df_tumor_samples.data_type)

array(['Aggregated Somatic Mutation', 'Aligned Reads',
       'Allele-specific Copy Number Segment',
       'Annotated Somatic Mutation', 'Copy Number Segment',
       'Gene Expression Quantification', 'Gene Level Copy Number',
       'Intermediate Analysis Archive',
       'Isoform Expression Quantification', 'Masked Copy Number Segment',
       'Masked Intensities', 'Masked Somatic Mutation',
       'Methylation Beta Value', 'Pathology Report',
       'Protein Expression Quantification', 'Raw Intensities',
       'Raw Simple Somatic Mutation', 'Simple Germline Variation',
       'Slide Image', 'Splice Junction Quantification',
       'Structural Rearrangement', 'Transcript Fusion',
       'miRNA Expression Quantification'], dtype=object)

In [31]:
dff_normal = df_normal_samples[df_normal_samples.data_type == "Gene Expression Quantification"]
dff_normal.reset_index(drop=True, inplace=True)

print(len(dff_normal))

100

In [32]:
case_id_list = np.unique(dff_normal.case_id)
print(len(case_id_list))

case_id_list[:3]

12

array(['07b5663f-9a54-4462-b6c1-6fc8116b8714',
       '0a45f302-5748-48f3-9dc9-66c01843a68e',
       '0b31dbdf-0623-48e4-a0ec-017650dceda7'], dtype=object)

In [33]:
dff_tumor = df_tumor_samples[df_tumor_samples.case_id.isin(case_id_list)].copy()
dff_tumor = dff_tumor[dff_tumor.data_type == "Gene Expression Quantification"]
dff_tumor.reset_index(drop=True, inplace=True)

print(len(dff_tumor))
dff_tumor.head(6)

109

,case_id,submitter_id,sample_id,sample_type,barcode_sample,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
0,21fb46f9-4bbb-441c-af19-a687e9138344,TCGA-49-6742,f0a4ae58-d5bc-4ab0-b1cf-0d951ea91fc7,Primary Tumor,TCGA-49-6742-01A,a03c9de0-7526-4942-8a7a-5fe03ea191f6,3ce23908-d2b9-42b0-a409-5fbd767496c2.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,unknown
1,195a5afb-b79f-44d2-9d12-884487630c2b,TCGA-73-4676,22434a49-eb8a-43ac-8c08-ae6dcbe6fbb8,Primary Tumor,TCGA-73-4676-01A,4320b770-69f3-4dd2-afea-8b7f7cdf44c2,32e5ef2b-4387-4d2c-8e62-d18b5106414f.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIA
2,15340dd3-84ae-49fb-989a-eb212f3e73da,TCGA-49-6744,a9d69d7e-298c-4ab6-b64f-1edc58832ccd,Primary Tumor,TCGA-49-6744-01A,1876b908-e911-464f-be23-2b4eae0a43b6,6efebff1-f165-415e-9001-45a782638785.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,unknown
3,12ccd581-a921-41bc-bcee-4e9be54532cc,TCGA-50-5931,16a2d381-75a0-423b-aac2-d5710afb183b,Primary Tumor,TCGA-50-5931-01A,69933ac8-e7a7-43b6-8231-2ecb35f88d52,c9d8385a-9f73-48f9-bca4-1c0647881bfd.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB
4,12b79b4f-c28c-418e-a1e7-e622f33fdcc2,TCGA-50-5939,6a27f5f8-f4ee-45c7-b953-ddd7d0291dbb,Primary Tumor,TCGA-50-5939-01A,8148f34c-1ddd-454a-8761-8b76e97e8534,4a39a182-e583-4ff0-a8f0-f73b0f5c4f20.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,unknown
5,0ea4920f-f4c8-4590-84b3-eb419824e144,TCGA-38-4625,cc72dc0d-9c39-4217-b5cb-8cad390d7e86,Primary Tumor,TCGA-38-4625-01A,242a2880-95da-453f-892d-fafd49a4865e,9301f86d-9d6f-4aa6-a640-a543b5aea5db.rna_seq.a...,Gene Expression Quantification,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB

### Preparing to get Gene Expression files from TCGA programa

In [35]:
verbose = False
force = False

dfexp = pd.DataFrame()

for i, row in dff_normal.iterrows():
    if int(i) % 10 == 0:
        print(i, end="")
    else:
        print(".", end="")
    case_id = row.case_id
    file_id = row.file_id

    dfexp = gdc.get_table_given_fileID(
        case_id=case_id,
        file_id=file_id,
        sample_type="normal",
        file_type="Gene Expression Quantification",
        verbose=verbose,
        force=force,
    )

print("")
print(len(dfexp))
dfexp.head(3)

0.........10.........20.........30.........40.........50.........60.........70.........80.........90.........
60660

,gene_id,symbol,gene_type,unstranded,counts,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,ENSG00000000003,TSPAN6,protein_coding,1281,619,662,28.7250,8.4838,9.4228
1,ENSG00000000005,TNMD,protein_coding,107,51,56,7.3736,2.1778,2.4188
2,ENSG00000000419,DPM1,protein_coding,1042,525,517,87.8100,25.9343,28.8047

In [26]:
len(dff_tumor)

109

In [36]:
verbose = False
force = False

dfexp = pd.DataFrame()

for i, row in dff_tumor.iterrows():
    if int(i) % 10 == 0:
        print(i, end="")
    else:
        print(".", end="")
    case_id = row.case_id
    file_id = row.file_id

    dfexp = gdc.get_table_given_fileID(
        case_id=case_id,
        file_id=file_id,
        sample_type="tumor",
        file_type="Gene Expression Quantification",
        verbose=verbose,
        force=force,
    )

print("")
print(len(dfexp))
dfexp.head(3)

0.........10.........20.........30.........40.........50.........60.........70.........80.........90.........100........
60660

,gene_id,symbol,gene_type,unstranded,counts,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,ENSG00000000003,TSPAN6,protein_coding,1085,522,563,21.6627,6.4049,6.1831
1,ENSG00000000005,TNMD,protein_coding,0,0,0,0.0000,0.0000,0.0000
2,ENSG00000000419,DPM1,protein_coding,1382,678,704,103.6947,30.6590,29.5970